XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/challenge/adjourn.js File Reference
/home/www/rubens/webclient/scripts/challenge/adjourn.js File Reference
Functions to parse adjourned games message and show result in interface.
Functions
function CHALLENGE_HandleAdjourn (XML)
Parse XML with adjourned games list and show in interface.
function CHALLENGE_HandlePresence (XML)
Parse presence to adjourn game user;.
function CHALLENGE_PostponePresence (Username, PresenceType)
Update status of user in postpone list.
function CHALLENGE_SendResumeGame (AdjournId)
Create and send a message to resume a game with some player.
function CHALLENGE_GetAdjournGames ()
Create and send message to get adjourned games list.
function CHALLENGE_RemovePostpone (Id)
Remove post pone from maindata and challenge menu.
Detailed Description
Functions to parse adjourned games message and show result in interface.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
See interface challenge menu (scripts/interface/challengemenu.js) and data methods to adjourn/postpone game list (scripts/data/data.js)
PS: Currently, adjourn and postpone games are considered the same thing.
Function Documentation
function CHALLENGE_GetAdjournGames ()
Create and send message to get adjourned games list.
Returns:
Empty string;
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_ChallengeGetAdjournList().
function CHALLENGE_HandleAdjourn (XML)
Parse XML with adjourned games list and show in interface.
Parameters:
XML XML with adjourned games
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References CHALLENGE_PostponePresence(), MainData, and USER_AddUser().
Referenced by PARSER_ParseIq().
function CHALLENGE_HandlePresence (XML)
Parse presence to adjourn game user;.
Parse presence to user in challenge list. I.E.: if user comes offline the adjourn game with this user turn unavailable to play.
Parameters:
XML XML with adjourned games
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References CHALLENGE_PostponePresence(), and MainData.
Referenced by PARSER_ParsePresence().
function CHALLENGE_PostponePresence (Username, PresenceType)
Update status of user in postpone list.
Parameters:
Username Name used by user
PresenceType User status (offline or others status)
Returns:
Empty string;
Author:
Rubens Suguimoto
References MainData.
Referenced by CHALLENGE_HandleAdjourn(), CHALLENGE_HandlePresence(), GAMECENTER_PostponeSortByCategory(), GAMECENTER_PostponeSortByDate(), GAMECENTER_PostponeSortByInc(), GAMECENTER_PostponeSortByRating(), GAMECENTER_PostponeSortByTime(), and GAMECENTER_PostponeSortByUsername().
function CHALLENGE_RemovePostpone (Id)
Remove post pone from maindata and challenge menu.
Parameters:
Id Adjourned/Postpone game Id
Returns:
Empty string;
Author:
Rubens Suguimoto
References MainData.
Referenced by CHALLENGE_SendResumeGame().
function CHALLENGE_SendResumeGame (AdjournId)
Create and send a message to resume a game with some player.
Parameters:
AdjournId Adjourned game Id;
Returns:
Empty string;
Author:
Rubens Suguimoto
References CHALLENGE_RemovePostpone(), CONNECTION_SendJabber(), MainData, and MESSAGE_ChallengeResumeGame().
Referenced by INTERFACE_UpdatePostpone(), and INTERFACE_UpdatePostponeItem().