XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/admin/admin.js File Reference
/home/www/rubens/webclient/scripts/admin/admin.js File Reference
Contains all parsers and actions to admin messages.
Functions
function ADMIN_HandleRoomAdmin (XML)
Parser admin messages for rooms.
function ADMIN_HandleAdmin (XML)
Parser administrative messages for admin.
function ADMIN_HandleAdminError (XML)
Parser administrative messages errors for admin.
function ADMIN_HandleInfo (XML)
Parser user type to idenfify admin.
function ADMIN_Notification (XML)
Parser and show notification of some action done by admin.
function ADMIN_HandleUserNotification (XML)
Parser and show notification of some action done by admin to normal user.
function ADMIN_HandleBanList (XML)
Parse and show banned user list to admin.
function ADMIN_HandleAddWord (XML)
Handle banned words added notification.
function ADMIN_HandleRemoveWord (XML)
Handle banned words removed notification.
function ADMIN_HandleBannedWordsList (XML)
Handle banned words list.
function ADMIN_KickUser (Username, Reason)
Create and send message to kick some user and reason;.
function ADMIN_BanUser (Username, Reason)
Create and send message to ban some user and reason;.
function ADMIN_UnbanUser (Username, Reason)
Create and send message to unban some user and reason;.
function ADMIN_GetBanList ()
Create and send message to get banned users's list.
function ADMIN_BanWord (Word)
Create and send message to ban some word.
function ADMIN_RemoveBannedWord (Word)
Create and send message to unban some word.
function ADMIN_GetBannedWords ()
Create and send message to get all banned words.
function ADMINCENTER_StartAdminCenter ()
Start admin center object.
function ADMINCENTER_ShowPunish ()
Show punish tab in admin center object.
function ADMINCENTER_ShowAdminLevel ()
Show admin level tab in admin center object.
function ADMINCENTER_ShowLevel ()
Show player's level tab in admin center object.
function ADMINCENTER_ShowAdjourn ()
Show adjourned games tab in admin center object.
function ADMINCENTER_ShowWords ()
Show banned words tab in admin center object.
function ADMINCENTER_ClearBannedWordsList ()
Clear banned words list in admin center object.
function ADMINCENTER_ClearPunishList ()
Clear punished players list in admin center object.
function ADMINCENTER_PunishSortByUsername ()
Sort punished players list by username.
function ADMINCENTER_PunishSortByPunish ()
Sort punished players list by punish.
function ADMINCENTER_PunishSortByIncident ()
Sort punished players list by incident.
function ADMINCENTER_PunishSortByDate ()
Sort punished players list by date.
function ADMINCENTER_PunishSortByPeriod ()
Sort punished players list by period.
function ADMINCENTER_PunishSortByReason ()
Sort punished players list by reason.
function ADMINCENTER_AdminLevelSortByUsername ()
Sort admin level list by username.
function ADMINCENTER_AdminLevelSortByLevel ()
Sort admin level list by level.
function ADMINCENTER_LevelSortByUsername ()
Sort level list by username.
function ADMINCENTER_LevelSortByLevel ()
Sort level list by level.
function ADMINCENTER_AdjournSortByWRating ()
Sort adjourn list by white player rating.
function ADMINCENTER_AdjournSortByBRating ()
Sort adjourn list by black player rating.
function ADMINCENTER_AdjournSortByWUsername ()
Sort adjourn list by white player username.
function ADMINCENTER_AdjournSortByBUsername ()
Sort adjourn list by black player username.
function ADMINCENTER_AdjournSortByCategory ()
Sort adjourn list by game category.
function ADMINCENTER_AdjournSortByTime ()
Sort adjourn list by game time.
function ADMINCENTER_AdjournSortByInc ()
Sort adjourn list by game time increment.
function ADMINCENTER_AdjournSortByRated ()
Sort adjourn list by game rated.
Detailed Description
Contains all parsers and actions to admin messages.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
See interface functions to admin (script/interface/admin.js)
Function Documentation
function ADMIN_BanUser (Username, Reason)
Create and send message to ban some user and reason;.
Create and send message to ban some user and reason to ban him/her;
Parameters:
Username User name used by user
Reason Reason to ban user
Returns:
Empty string;
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_BanUser().
Referenced by INTERFACE_BanUserWindow().
function ADMIN_BanWord (Word)
Create and send message to ban some word.
Create and send message to ban some word
Parameters:
Word String to ban
Returns:
Empty string;
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_AddBannedWord().
Referenced by INTERFACE_CreateAdminCenterWords().
function ADMIN_GetBanList ()
Create and send message to get banned users's list.
Create and send message to get all banned users from server
Returns:
Empty string
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_GetBanList().
Referenced by INTERFACE_CreateAdminCenter().
function ADMIN_GetBannedWords ()
Create and send message to get all banned words.
Create and send message to get all banned words
Returns:
Empty string
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_GetBannedWords().
Referenced by ADMINCENTER_StartAdminCenter(), and INTERFACE_CreateAdminCenter().
function ADMIN_HandleAddWord (XML)
Handle banned words added notification.
Parameters:
XML XML with banned words notification
Returns:
Empty string;
Author:
Rubens Suguimoto
References MainData, and WINDOW_Alert().
Referenced by ADMIN_HandleAdmin(), and ADMIN_HandleAdminError().
function ADMIN_HandleAdmin (XML)
Parser administrative messages for admin.
Parser messages with administrative commands
Parameters:
XML XML with admin datas
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References ADMIN_HandleAddWord(), ADMIN_HandleBanList(), ADMIN_HandleBannedWordsList(), ADMIN_HandleRemoveWord(), ADMIN_Notification(), and MainData.
Referenced by PARSER_ParseIq().
function ADMIN_HandleAdminError (XML)
Parser administrative messages errors for admin.
Parser messages with administrative commands result errors
Parameters:
XML XML with admin data erros
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References ADMIN_HandleAddWord(), ADMIN_HandleBanList(), ADMIN_HandleBannedWordsList(), ADMIN_HandleRemoveWord(), ADMIN_Notification(), and MainData.
Referenced by PARSER_ParseIq().
function ADMIN_HandleBanList (XML)
Parse and show banned user list to admin.
Parse admin message with banned users and show as list in interface to admin.
Parameters:
XML XML with banned users
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References MainData, and UTILS_GetNodeText().
Referenced by ADMIN_HandleAdmin(), and ADMIN_HandleAdminError().
function ADMIN_HandleBannedWordsList (XML)
Handle banned words list.
Parameters:
XML XML with banned words
Returns:
Empty string
Author:
Rubens Suguimoto
References MainData.
Referenced by ADMIN_HandleAdmin(), and ADMIN_HandleAdminError().
function ADMIN_HandleInfo (XML)
Parser user type to idenfify admin.
Parser user type to show menu item to access administrative tools.
Parameters:
XML XML with user type
Returns:
Empty string
See also:
INTERFACE_ShowAdminIcon
Author:
Rubens Suguimoto
References INTERFACE_ShowAdminIcon(), and MainData.
Referenced by PARSER_ParseIq().
function ADMIN_HandleRemoveWord (XML)
Handle banned words removed notification.
Parameters:
XML XML with banned words notification
Returns:
Empty string
Author:
Rubens Suguimoto
References MainData, and WINDOW_Alert().
Referenced by ADMIN_HandleAdmin(), and ADMIN_HandleAdminError().
function ADMIN_HandleRoomAdmin (XML)
Parser admin messages for rooms.
Parameters:
XML XML with admin commands results
Returns:
Buffer with other XMPP to send
Author:
Ulysses Bomfim
Referenced by PARSER_ParseIq().
function ADMIN_HandleUserNotification (XML)
Parser and show notification of some action done by admin to normal user.
Parse admin message with result of some action done and show in interface to normal user.
Parameters:
XML Xml with notification message
Returns:
Buffer with other XMPP to send;
Author:
Rubens Suguimoto
References UTILS_GetNodeText(), and UTILS_GetText().
Referenced by PARSER_ParseIq().
function ADMIN_KickUser (Username, Reason)
Create and send message to kick some user and reason;.
Create and send message to kick some user and reason to kick him/her;
Parameters:
Username User name used by user
Reason Reason to kick user
Returns:
Empty string
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_KickUser().
Referenced by INTERFACE_KickUserWindow().
function ADMIN_Notification (XML)
Parser and show notification of some action done by admin.
Parse admin message with result of some action done and show in interface.
Parameters:
XML Xml with the messages
Returns:
Empty string
Author:
Rubens Suguimoto
References UTILS_GetText(), and WINDOW_Alert().
Referenced by ADMIN_HandleAdmin(), and ADMIN_HandleAdminError().
function ADMIN_RemoveBannedWord (Word)
Create and send message to unban some word.
Create and send message to unban some word
Parameters:
Word String to ban
Returns:
Empty string
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_RemoveBannedWord().
Referenced by INTERFACE_AddWords().
function ADMIN_UnbanUser (Username, Reason)
Create and send message to unban some user and reason;.
Create and send message to unban some user and reason to unban him/her;
Parameters:
Username User name used by user
Reason Reason to unban user
Returns:
Empty string;
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_UnbanUser().
Referenced by INTERFACE_AddBannedUser(), INTERFACE_AddPunish(), and INTERFACE_UnbanUserWindow().
function ADMINCENTER_AdjournSortByBRating ()
Sort adjourn list by black player rating.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdjourn().
function ADMINCENTER_AdjournSortByBUsername ()
Sort adjourn list by black player username.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdjourn().
function ADMINCENTER_AdjournSortByCategory ()
Sort adjourn list by game category.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdjourn().
function ADMINCENTER_AdjournSortByInc ()
Sort adjourn list by game time increment.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdjourn().
function ADMINCENTER_AdjournSortByRated ()
Sort adjourn list by game rated.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdjourn().
function ADMINCENTER_AdjournSortByTime ()
Sort adjourn list by game time.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdjourn().
function ADMINCENTER_AdjournSortByWRating ()
Sort adjourn list by white player rating.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdjourn().
function ADMINCENTER_AdjournSortByWUsername ()
Sort adjourn list by white player username.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
function ADMINCENTER_AdminLevelSortByLevel ()
Sort admin level list by level.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdminLevel().
function ADMINCENTER_AdminLevelSortByUsername ()
Sort admin level list by username.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterAdminLevel().
function ADMINCENTER_ClearBannedWordsList ()
Clear banned words list in admin center object.
Remove all words in banned words list inside admin center object
Returns:
none
See also:
INTERFACE_CreateAdminCenter
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenter().
function ADMINCENTER_ClearPunishList ()
Clear punished players list in admin center object.
Remove all players in punished players list inside admin center object
Returns:
none
See also:
INTERFACE_CreateAdminCenter
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenter().
function ADMINCENTER_LevelSortByLevel ()
Sort level list by level.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterLevel().
function ADMINCENTER_LevelSortByUsername ()
Sort level list by username.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterLevel().
function ADMINCENTER_PunishSortByDate ()
Sort punished players list by date.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterPunish().
function ADMINCENTER_PunishSortByIncident ()
Sort punished players list by incident.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterPunish().
function ADMINCENTER_PunishSortByPeriod ()
Sort punished players list by period.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterPunish().
function ADMINCENTER_PunishSortByPunish ()
Sort punished players list by punish.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterPunish().
function ADMINCENTER_PunishSortByReason ()
Sort punished players list by reason.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterPunish().
function ADMINCENTER_PunishSortByUsername ()
Sort punished players list by username.
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenterPunish().
function ADMINCENTER_ShowAdjourn ()
Show adjourned games tab in admin center object.
Show adjourned games tab in admin center object and hide others tabs
Returns:
none
See also:
INTERFACE_CreateAdminCenter
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenter().
function ADMINCENTER_ShowAdminLevel ()
Show admin level tab in admin center object.
Show admin level tab in admin center object and hide others tabs
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenter().
function ADMINCENTER_ShowLevel ()
Show player's level tab in admin center object.
Show player's level tab in admin center object and hide others tabs
Returns:
none
See also:
INTERFACE_CreateAdminCenter
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenter().
function ADMINCENTER_ShowPunish ()
Show punish tab in admin center object.
Show punished players tab in admin center object and hide others tabs
Returns:
none
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenter().
function ADMINCENTER_ShowWords ()
Show banned words tab in admin center object.
Show banned words tab in admin center object and hide others tabs
Returns:
none
See also:
INTERFACE_CreateAdminCenter
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by INTERFACE_CreateAdminCenter().
function ADMINCENTER_StartAdminCenter ()
Start admin center object.
Create and show admin center object in interface. Get all banned words
Returns:
none
Author:
Rubens Suguimoto
References ADMIN_GetBannedWords(), AdminCenterObj(), and MainData.
Referenced by START_Webclient().