XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/admincenter.js File Reference
/home/www/rubens/webclient/scripts/interface/admincenter.js File Reference
Create window content object to admin tools.
Functions
function INTERFACE_ShowCreateAdminCenterWindow ()
Create admin center window.
function AdminCenterObj ()
function INTERFACE_ShowAdminCenter (Element)
function INTERFACE_HideAdminCenter ()
function INTERFACE_CreateAdminCenter ()
function PunishObj ()
function INTERFACE_AddPunish (Name, Punish, Incident, Date, Period, Reason)
function INTERFACE_RemovePunish (Name)
function INTERFACE_ShowPunishCenter (Element)
function INTERFACE_HidePunishCenter ()
function INTERFACE_ShowNoPunish ()
function INTERFACE_HideNoPunish ()
function INTERFACE_CreateAdminCenterPunish ()
function AdminLevelObj ()
function INTERFACE_AddAdminLevel (Name, AdminLevel)
function INTERFACE_RemoveAdminLevel (MatchId)
function INTERFACE_ShowAdminLevelCenter (Element)
function INTERFACE_HideAdminLevelCenter ()
function INTERFACE_ShowNoAdminLevel ()
function INTERFACE_HideNoAdminLevel ()
function INTERFACE_CreateAdminCenterAdminLevel ()
function LevelObj ()
function INTERFACE_AddLevel (Name, Level)
function INTERFACE_RemoveLevel (MatchId)
function INTERFACE_ShowLevelCenter (Element)
function INTERFACE_HideLevelCenter ()
function INTERFACE_ShowNoLevel ()
function INTERFACE_HideNoLevel ()
function INTERFACE_CreateAdminCenterLevel ()
function AdjournObj ()
function INTERFACE_AddAdjourn (WPlayerName, WRating, BPlayerName, BRating, Category, GameTime, Inc, Rated, AdjournId)
function INTERFACE_RemoveAdjourn (AdjournId)
function INTERFACE_ShowAdjournCenter (Element)
function INTERFACE_HideAdjournCenter ()
function INTERFACE_ShowNoAdjourn ()
function INTERFACE_HideNoAdjourn ()
function INTERFACE_CreateAdminCenterAdjourn ()
function WordsObj ()
function INTERFACE_AddWords (Word)
function INTERFACE_RemoveWords (MatchId)
function INTERFACE_ShowWordsCenter (Element)
function INTERFACE_HideWordsCenter ()
function INTERFACE_ShowNoWords ()
function INTERFACE_HideNoWords ()
function INTERFACE_CreateAdminCenterWords ()
Detailed Description
Create window content object to admin tools.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function AdjournObj ()
References INTERFACE_AddAdjourn(), INTERFACE_CreateAdminCenterAdjourn(), INTERFACE_HideAdjournCenter(), INTERFACE_HideNoAdjourn(), INTERFACE_RemoveAdjourn(), INTERFACE_ShowAdjournCenter(), and INTERFACE_ShowNoAdjourn().
Referenced by AdminCenterObj().
function AdminCenterObj ()
References AdjournObj(), AdminLevelObj(), INTERFACE_CreateAdminCenter(), INTERFACE_HideAdminCenter(), INTERFACE_ShowAdminCenter(), LevelObj(), PunishObj(), and WordsObj().
Referenced by ADMINCENTER_AdjournSortByBRating(), ADMINCENTER_AdjournSortByBUsername(), ADMINCENTER_AdjournSortByCategory(), ADMINCENTER_AdjournSortByInc(), ADMINCENTER_AdjournSortByRated(), ADMINCENTER_AdjournSortByTime(), ADMINCENTER_AdjournSortByWRating(), ADMINCENTER_AdjournSortByWUsername(), ADMINCENTER_AdminLevelSortByLevel(), ADMINCENTER_AdminLevelSortByUsername(), ADMINCENTER_ClearBannedWordsList(), ADMINCENTER_ClearPunishList(), ADMINCENTER_LevelSortByLevel(), ADMINCENTER_LevelSortByUsername(), ADMINCENTER_PunishSortByDate(), ADMINCENTER_PunishSortByIncident(), ADMINCENTER_PunishSortByPeriod(), ADMINCENTER_PunishSortByPunish(), ADMINCENTER_PunishSortByReason(), ADMINCENTER_PunishSortByUsername(), ADMINCENTER_ShowAdjourn(), ADMINCENTER_ShowAdminLevel(), ADMINCENTER_ShowLevel(), ADMINCENTER_ShowPunish(), ADMINCENTER_ShowWords(), ADMINCENTER_StartAdminCenter(), and UTILS_BannedWords().
function AdminLevelObj ()
References INTERFACE_AddAdminLevel(), INTERFACE_CreateAdminCenterAdminLevel(), INTERFACE_HideAdminLevelCenter(), INTERFACE_HideNoAdminLevel(), INTERFACE_RemoveAdminLevel(), INTERFACE_ShowAdminLevelCenter(), and INTERFACE_ShowNoAdminLevel().
Referenced by AdminCenterObj().
function INTERFACE_AddAdjourn (WPlayerName, WRating, BPlayerName, BRating, Category, GameTime, Inc, Rated, AdjournId)
References UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by AdjournObj().
function INTERFACE_AddAdminLevel (Name, AdminLevel)
References UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by AdminLevelObj().
function INTERFACE_AddLevel (Name, Level)
References UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by LevelObj().
function INTERFACE_AddPunish (Name, Punish, Incident, Date, Period, Reason)
References ADMIN_UnbanUser(), UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by PunishObj().
function INTERFACE_AddWords (Word)
References ADMIN_RemoveBannedWord(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by WordsObj().
function INTERFACE_CreateAdminCenter ()
References ADMIN_GetBanList(), ADMIN_GetBannedWords(), ADMINCENTER_ClearBannedWordsList(), ADMINCENTER_ClearPunishList(), ADMINCENTER_ShowAdjourn(), ADMINCENTER_ShowAdminLevel(), ADMINCENTER_ShowLevel(), ADMINCENTER_ShowPunish(), ADMINCENTER_ShowWords(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by AdminCenterObj().
function INTERFACE_CreateAdminCenterAdjourn ()
References ADMINCENTER_AdjournSortByBRating(), ADMINCENTER_AdjournSortByBUsername(), ADMINCENTER_AdjournSortByCategory(), ADMINCENTER_AdjournSortByInc(), ADMINCENTER_AdjournSortByRated(), ADMINCENTER_AdjournSortByTime(), ADMINCENTER_AdjournSortByWRating(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by AdjournObj().
function INTERFACE_CreateAdminCenterAdminLevel ()
References ADMINCENTER_AdminLevelSortByLevel(), ADMINCENTER_AdminLevelSortByUsername(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by AdminLevelObj().
function INTERFACE_CreateAdminCenterLevel ()
References ADMINCENTER_LevelSortByLevel(), ADMINCENTER_LevelSortByUsername(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by LevelObj().
function INTERFACE_CreateAdminCenterPunish ()
References ADMINCENTER_PunishSortByDate(), ADMINCENTER_PunishSortByIncident(), ADMINCENTER_PunishSortByPeriod(), ADMINCENTER_PunishSortByPunish(), ADMINCENTER_PunishSortByReason(), ADMINCENTER_PunishSortByUsername(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by PunishObj().
function INTERFACE_CreateAdminCenterWords ()
References ADMIN_BanWord(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by WordsObj().
function INTERFACE_HideAdjournCenter ()
Referenced by AdjournObj().
function INTERFACE_HideAdminCenter ()
Referenced by AdminCenterObj().
function INTERFACE_HideAdminLevelCenter ()
Referenced by AdminLevelObj().
function INTERFACE_HideLevelCenter ()
Referenced by LevelObj().
function INTERFACE_HideNoAdjourn ()
Referenced by AdjournObj().
function INTERFACE_HideNoAdminLevel ()
Referenced by AdminLevelObj().
function INTERFACE_HideNoLevel ()
Referenced by LevelObj().
function INTERFACE_HideNoPunish ()
Referenced by PunishObj().
function INTERFACE_HideNoWords ()
Referenced by WordsObj().
function INTERFACE_HidePunishCenter ()
Referenced by PunishObj().
function INTERFACE_HideWordsCenter ()
Referenced by WordsObj().
function INTERFACE_RemoveAdjourn (AdjournId)
Referenced by AdjournObj().
function INTERFACE_RemoveAdminLevel (MatchId)
Referenced by AdminLevelObj().
function INTERFACE_RemoveLevel (MatchId)
Referenced by LevelObj().
function INTERFACE_RemovePunish (Name)
Referenced by PunishObj().
function INTERFACE_RemoveWords (MatchId)
Referenced by WordsObj().
function INTERFACE_ShowAdjournCenter (Element)
Referenced by AdjournObj().
function INTERFACE_ShowAdminCenter (Element)
Referenced by AdminCenterObj().
function INTERFACE_ShowAdminLevelCenter (Element)
Referenced by AdminLevelObj().
function INTERFACE_ShowCreateAdminCenterWindow ()
Create admin center window.
Create temporary admin tools window content.
Returns:
Div element, Buttons elements and Elements that receive event
Author:
Rubens Suguimoto
See also:
WINDOW_CreateAdminCenter()
References MainData, and UTILS_CreateElement().
Referenced by WINDOW_CreateAdminCenter().
function INTERFACE_ShowLevelCenter (Element)
Referenced by LevelObj().
function INTERFACE_ShowNoAdjourn ()
Referenced by AdjournObj().
function INTERFACE_ShowNoAdminLevel ()
Referenced by AdminLevelObj().
function INTERFACE_ShowNoLevel ()
Referenced by LevelObj().
function INTERFACE_ShowNoPunish ()
Referenced by PunishObj().
function INTERFACE_ShowNoWords ()
Referenced by WordsObj().
function INTERFACE_ShowPunishCenter (Element)
Referenced by PunishObj().
function INTERFACE_ShowWordsCenter (Element)
Referenced by WordsObj().
function LevelObj ()
References INTERFACE_AddLevel(), INTERFACE_CreateAdminCenterLevel(), INTERFACE_HideLevelCenter(), INTERFACE_HideNoLevel(), INTERFACE_RemoveLevel(), INTERFACE_ShowLevelCenter(), and INTERFACE_ShowNoLevel().
Referenced by AdminCenterObj().
function PunishObj ()
References INTERFACE_AddPunish(), INTERFACE_CreateAdminCenterPunish(), INTERFACE_HideNoPunish(), INTERFACE_HidePunishCenter(), INTERFACE_RemovePunish(), INTERFACE_ShowNoPunish(), and INTERFACE_ShowPunishCenter().
Referenced by AdminCenterObj(), and DATA_AddPunish().
function WordsObj ()
References INTERFACE_AddWords(), INTERFACE_CreateAdminCenterWords(), INTERFACE_HideNoWords(), INTERFACE_HideWordsCenter(), INTERFACE_RemoveWords(), INTERFACE_ShowNoWords(), and INTERFACE_ShowWordsCenter().
Referenced by AdminCenterObj().