XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/board.js File Reference
/home/www/rubens/webclient/scripts/interface/board.js File Reference
Functions
function INTERFACE_CreateGame (GameId, WName, BName, MyColor, PieceSize, Observer)
Creating game div and set all attributes.
function INTERFACE_CreateBoard (MyColor, PieceSize, Observer)
Create a game board.
function INTERFACE_RemoveBlockEvents ()
Remove mouse event associated to board blocks.
function INTERFACE_CreateTimer ()
Create timer elements.
function INTERFACE_CreateGameOptions (GameID)
Create game options.
function INTERFACE_CreateMoveList ()
Create a move list.
function INTERFACE_CreatePhoto (WhitePlayer, BlackPlayer)
Create photo images and names.
function INTERFACE_CreateTab (Div1, Div2)
Create tabs with 2 divs.
function INTERFACE_CreateVerticalIndex (Color, Size)
Create vertical indexes of board.
function INTERFACE_CreateHorizontalIndex (Color, Size)
Create horizontal indexes of board.
function INTERFACE_NewPiece (Piece, PlayerColor, Size)
Create a new piece, with drag listener in pieces.
function INTERFACE_CreateOldGameMoveList ()
Create OldGame move list with buttons to review all game moves.
function INTERFACE_CreateOldGameTab (DivMoves)
Create tab with 1 div(this should be used in Observer and OldGame mode).
function INTERFACE_LastMove (Move)
Change board to last move done.
function INTERFACE_FindBlock (id)
Find a block with parameter Identificator.
function INTERFACE_ShowLoadingMove ()
Show loading move box.
function INTERFACE_HideLoadingMove ()
Hide loading move box.
function INTERFACE_ShowLeaveUser (Color)
Show leave user from game message.
function INTERFACE_HideLeaveUser ()
Hide leave user from game message.
function INTERFACE_SetBlockBorder (Block)
Set a border to block.
function INTERFACE_SetBlockClass (BlockId)
Set block class as selected.
function INTERFACE_RemoveBlockBorder (Block)
Remove border from block.
function INTERFACE_RemoveBlockClass (BlockId)
Remove select class from block and set its real color (black/white).
Function Documentation
function INTERFACE_CreateBoard (MyColor, PieceSize, Observer)
Create a game board.
Parameters:
MyColor Your player color in the game
PieceSize Board piece size
Observer Observer mode flag
Returns:
Board HTML DOM Div
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_CreateElement(), and UTILS_HorizontalIndex().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateGame (GameId, WName, BName, MyColor, PieceSize, Observer)
Creating game div and set all attributes.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Parameters:
GameId Game identification field
WName White user's name
BName Black user's name
MyColor Your color
PieceSize Size of piece in board
Observer Observer mode flag
Returns:
Game board elements
Author:
Rubens Suguimoto and Pedro Rocha
References GAME_RemoveGame(), INTERFACE_CreateBoard(), INTERFACE_CreateGameOptions(), INTERFACE_CreateHorizontalIndex(), INTERFACE_CreateMoveList(), INTERFACE_CreatePhoto(), INTERFACE_CreateTab(), INTERFACE_CreateTimer(), INTERFACE_CreateVerticalIndex(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_CreateGameOptions (GameID)
Create game options.
Parameters:
GameID Game identification
Returns:
Options Div and Array of html elements (game options)
Author:
Rubens Suguimoto and Pedro Rocha
References GAME_ChangePromotion(), GAME_SendAdjourn(), GAME_SendCancel(), GAME_SendDraw(), GAME_SendResign(), UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_Alert().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateHorizontalIndex (Color, Size)
Create horizontal indexes of board.
Parameters:
Color Your color
Size Size of blocks of each block in board
Returns:
Horizontal index HTML DOM List
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_CreateElement(), and UTILS_HorizontalIndex().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateMoveList ()
Create a move list.
Returns:
MoveListDiv HTML DOM Div and MoveList HTML DOM List
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_CreateElement().
Referenced by INTERFACE_CreateGame(), and INTERFACE_ObserverMode().
function INTERFACE_CreateOldGameMoveList ()
Create OldGame move list with buttons to review all game moves.
Returns:
MoveListDiv html div and MoveList html list
Author:
Rubens Suguimoto and Pedro Rocha
References OLDGAME_FirstBoard(), OLDGAME_LastBoard(), OLDGAME_NextBoard(), OLDGAME_PrevBoard(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_OldGameMode().
function INTERFACE_CreateOldGameTab (DivMoves)
Create tab with 1 div(this should be used in Observer and OldGame mode).
Parameters:
DivMoves Div in tab that contais history moves
Returns:
Tab html Div
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_ObserverMode(), and INTERFACE_OldGameMode().
function INTERFACE_CreatePhoto (WhitePlayer, BlackPlayer)
Create photo images and names.
Parameters:
WhitePlayer White player's name
BlackPlayer Black player's name
Returns:
Photo html div, WPhoto html img, BPhoto html img, WName html span and BName html span
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_CreateElement(), and UTILS_ShortString().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateTab (Div1, Div2)
Create tabs with 2 divs.
Parameters:
Div1 First div in tab
Div2 Second div in tab
Returns:
Tab HTML DOM Div
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_AddListener(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateTimer ()
Create timer elements.
Returns:
Timer div, White Timer span and Black Timer span
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_CreateElement().
Referenced by INTERFACE_CreateGame().
function INTERFACE_CreateVerticalIndex (Color, Size)
Create vertical indexes of board.
Parameters:
Color Your color
Size Size of blocks of each block in board
Returns:
Vertical index HTML DOM list
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_CreateElement().
Referenced by INTERFACE_CreateGame().
function INTERFACE_FindBlock (id)
Find a block with parameter Identificator.
Parameters:
id Block identificator
Returns:
Block HTML div element of null (if block not found)
Author:
Rubens Suguimoto
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_HideLeaveUser ()
Hide leave user from game message.
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_HideLoadingMove ()
Hide loading move box.
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_LastMove (Move)
Change board to last move done.
Parameters:
Move Move string (i.e: a2a3)
Returns:
none
Author:
Rubens Suguimoto
References UTILS_HorizontalIndex().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_NewPiece (Piece, PlayerColor, Size)
Create a new piece, with drag listener in pieces.
Parameters:
Piece Piece character
PlayerColor Your color
Size Size of blocks of each block in board
Returns:
Piece HTML DOM img
Author:
Rubens Suguimoto and Pedro Rocha
References MainData, UTILS_CreateElement(), UTILS_GetText(), and UTILS_StartDragPiece().
Referenced by INTERFACE_InsertPiece().
function INTERFACE_RemoveBlockBorder (Block)
Remove border from block.
Parameters:
Block Block element
Returns:
none
Author:
Danilo Yorinori
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_RemoveBlockClass (BlockId)
Remove select class from block and set its real color (black/white).
Parameters:
BlockId Id of block to search and change
Returns:
none
Author:
Danilo Yorinori
References UTILS_HorizontalIndex().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_RemoveBlockEvents ()
Remove mouse event associated to board blocks.
Returns:
none
Author:
Danilo Yorinori
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetBlockBorder (Block)
Set a border to block.
Parameters:
Block Block Div element
Returns:
none
Author:
Danilo Yorinori
References UTILS_CreateElement().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetBlockClass (BlockId)
Set block class as selected.
Parameters:
BlockId Id of block to search and change
Returns:
none
Author:
Danilo Yorinori
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_ShowLeaveUser (Color)
Show leave user from game message.
Returns:
none
Author:
Rubens Suguimoto
References UTILS_GetText().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_ShowLoadingMove ()
Show loading move box.
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_GameBoardObj().