XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/challenge/challenge.js File Reference
/home/www/rubens/webclient/scripts/challenge/challenge.js File Reference
Functions to parse challenges offered and receive.
Functions
function CHALLENGE_HandleChallenge (XML)
Handle challenge messages from server.
function CHALLENGE_HandleErrorChallenge (XML)
Handle errors challenge messages from server.
function CHALLENGE_HandleOffer (XML)
Parse challenge offer message.
function CHALLENGE_HandleAccept (XML)
Parse challenge accept.
function CHALLENGE_HandleDecline (XML)
Parse challenge decline.
function CHALLENGE_ChallengeError (XML)
Parse challenge errors.
function CHALLENGE_SendChallenge (Oponent, Color, Time, Inc, Category, Rated)
Send a challenge message to other user.
function CHALLENGE_SendReChallenge (Oponent, Color, Time, Inc, Category, Rated, MatchID)
Send a rematch to oponent and update challenge information in main data.
function CHALLENGE_AcceptChallenge (MatchID)
Accept the challenge with the specified MatchID.
function CHALLENGE_DeclineChallenge (MatchID)
function CHALLENGE_ClearChallenges ()
Remove all challenges from main data and interface.
Detailed Description
Functions to parse challenges offered and receive.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
See interface challenge menu (scripts/interface/challengemenu.js), data methods to challenge list (scripts/data/data.js) and window challenge (scripts/window/window.js).
Function Documentation
function CHALLENGE_AcceptChallenge (MatchID)
Accept the challenge with the specified MatchID.
Parameters:
MatchID Id of the match to be accepted
Returns:
none
Author:
Pedro Rocha
References CONNECTION_SendJabber(), and MESSAGE_ChallengeAccept().
Referenced by INTERFACE_ShowChallengeWindow(), and INTERFACE_ShowPostponeWindow().
function CHALLENGE_ChallengeError (XML)
Parse challenge errors.
Parameters:
XML XML with challenge parameters
Returns:
Empty string
Author:
Ulysses Bomfim
References MainData.
Referenced by CHALLENGE_HandleChallenge(), CHALLENGE_HandleErrorChallenge(), and CHALLENGE_HandleOffer().
function CHALLENGE_ClearChallenges ()
Remove all challenges from main data and interface.
Returns:
Empty string
Author:
Rubens Suguimoto
References CHALLENGE_DeclineChallenge(), and MainData.
Referenced by GAME_StartGame(), and INTERFACE_CreateGameCenterMatch().
function CHALLENGE_DeclineChallenge (MatchID)
Decline the challenge with the specified MatchID
Parameters:
MatchID Id of the match to be declined
Returns:
none
Author:
Pedro Rocha
References CONNECTION_SendJabber(), and MESSAGE_ChallengeDecline().
Referenced by CHALLENGE_ClearChallenges(), INTERFACE_AddMatchOffer(), INTERFACE_ShowPostponeWindow(), WINDOW_Challenge(), and WINDOW_Postpone().
function CHALLENGE_HandleAccept (XML)
Parse challenge accept.
Parameters:
XML XML with challenge parameters
Returns:
Buffer with XMPP to send
Author:
Ulysses Bomfim
References MainData, and MESSAGE_ChangeStatus().
Referenced by CHALLENGE_HandleChallenge().
function CHALLENGE_HandleChallenge (XML)
Handle challenge messages from server.
Parameters:
XML XML with challenge parameters
Returns:
Buffer with XMPP to send
Author:
Ulysses Bomfim
References CHALLENGE_ChallengeError(), CHALLENGE_HandleAccept(), CHALLENGE_HandleDecline(), and CHALLENGE_HandleOffer().
Referenced by PARSER_ParseIq().
function CHALLENGE_HandleDecline (XML)
Parse challenge decline.
Parameters:
XML XML with challenge parameters
Returns:
Buffer with XMPP to send
Author:
Ulysses Bomfim
References MainData, WINDOW_RemoveWindow(), and WindowObj().
Referenced by CHALLENGE_HandleChallenge().
function CHALLENGE_HandleErrorChallenge (XML)
Handle errors challenge messages from server.
Parameters:
XML XML with challenge parameters
Returns:
Buffer with XMPP to send
Author:
Rubens Suguimoto
References CHALLENGE_ChallengeError(), UTILS_GetText(), and WINDOW_Alert().
Referenced by PARSER_ParseIq().
function CHALLENGE_HandleOffer (XML)
Parse challenge offer message.
Parameters:
XML XML with challenge parameters
Returns:
Buffer Buffer with XMPP to send
Author:
Ulysses Bomfim
References CHALLENGE_ChallengeError(), MainData, WINDOW_Challenge(), and WINDOW_Postpone().
Referenced by CHALLENGE_HandleChallenge().
function CHALLENGE_SendChallenge (Oponent, Color, Time, Inc, Category, Rated)
Send a challenge message to other user.
Parameters:
Oponent Oponent username
Color Your color
Time Game time
Inc Game time increment
Category Game category
Rated Rated match (boolean)
Returns:
Empty string
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, and MESSAGE_Challenge().
Referenced by INTERFACE_ShowChallengeWindow().
function CHALLENGE_SendReChallenge (Oponent, Color, Time, Inc, Category, Rated, MatchID)
Send a rematch to oponent and update challenge information in main data.
Parameters:
Oponent Oponent username
Color Your color
Time Game time
Inc Game time increment
Category Game category
Rated Rated match (boolean)
MatchID Match identificator
Returns:
Empty string
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, and MESSAGE_Challenge().
Referenced by INTERFACE_ShowChallengeWindow().