XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/challenge/announce.js File Reference
/home/www/rubens/webclient/scripts/challenge/announce.js File Reference
Functions to parse announces offered and receive.
Functions
function ANNOUNCE_HandleAnnounce (XML)
Parse XML with announced games list and show in interface.
function ANNOUNCE_HandleAnnounceGame (XML)
Parse XML with start announced game.
function ANNOUNCE_HandleAnnounceError (XML)
Parse XML with announces errors.
function ANNOUNCE_SendAnnounce (Username, Color, Time, Inc, Category, Rated, Min, Max)
function ANNOUNCE_GetAnnounceGames ()
function ANNOUNCE_AddAnnounce (Username, Color, Time, Inc, Category, Rated, Private, AnnounceId)
function ANNOUNCE_RemoveAnnounce (Id)
function ANNOUNCE_CancelAnnounce (Id)
function ANNOUNCE_AcceptAnnounce (Id)
function ANNOUNCE_ClearAnnounce ()
Remove all announces from main data and interface.
function ANNOUNCE_CancelAllAnnounce ()
Cancel all announces made by you.
function ANNOUNCE_AcceptRandomAnnounce ()
Detailed Description
Functions to parse announces offered and receive.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
See interface announce window (scripts/interface/announce.js), data methods to announce list (scripts/data/data.js) and window announce (scripts/window/window.js).
Function Documentation
function ANNOUNCE_AcceptAnnounce (Id)
References CONNECTION_SendJabber(), and MESSAGE_AcceptAnnounceMatch().
Referenced by ANNOUNCE_AcceptRandomAnnounce(), and INTERFACE_AddAnnounce().
function ANNOUNCE_AcceptRandomAnnounce ()
References ANNOUNCE_AcceptAnnounce(), MainData, UTILS_GetText(), and WINDOW_Alert().
Referenced by INTERFACE_CreateGameCenterAnnounce().
function ANNOUNCE_AddAnnounce (Username, Color, Time, Inc, Category, Rated, Private, AnnounceId)
References MainData.
Referenced by ANNOUNCE_HandleAnnounce().
function ANNOUNCE_CancelAllAnnounce ()
Cancel all announces made by you.
Returns:
none
Author:
Rubens Suguimoto
References ANNOUNCE_CancelAnnounce(), and MainData.
Referenced by GAME_StartGame().
function ANNOUNCE_CancelAnnounce (Id)
References ANNOUNCE_RemoveAnnounce(), CONNECTION_SendJabber(), and MESSAGE_RemoveAnnounceMatch().
Referenced by ANNOUNCE_CancelAllAnnounce(), and INTERFACE_AddAnnounce().
function ANNOUNCE_ClearAnnounce ()
Remove all announces from main data and interface.
Don't send a message to cancel all announce
Returns:
none
Author:
Rubens Suguimoto
References ANNOUNCE_RemoveAnnounce(), and MainData.
Referenced by INTERFACE_AnnounceWindow(), and INTERFACE_CreateGameCenterAnnounce().
function ANNOUNCE_GetAnnounceGames ()
References CONNECTION_SendJabber(), and MESSAGE_GetAnnounceMatch().
Referenced by GAMECENTER_ShowAnnounce(), GAMECENTER_StartGameCenter(), and INTERFACE_AnnounceWindow().
function ANNOUNCE_HandleAnnounce (XML)
Parse XML with announced games list and show in interface.
Parameters:
XML XML with adjourned games
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References ANNOUNCE_AddAnnounce(), and MainData.
Referenced by PARSER_ParseIq().
function ANNOUNCE_HandleAnnounceError (XML)
Parse XML with announces errors.
Parameters:
XML XML with announce errors
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References ANNOUNCE_RemoveAnnounce(), MainData, UTILS_GetText(), and WINDOW_Alert().
Referenced by PARSER_ParseIq().
function ANNOUNCE_HandleAnnounceGame (XML)
Parse XML with start announced game.
Parse XML with announced game and start game with some player
Parameters:
XML XML with start announced game
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References CONTACT_ChangeStatus(), MainData, and MESSAGE_Presence().
Referenced by PARSER_ParseIq().
function ANNOUNCE_RemoveAnnounce (Id)
References MainData.
Referenced by ANNOUNCE_CancelAnnounce(), ANNOUNCE_ClearAnnounce(), and ANNOUNCE_HandleAnnounceError().
function ANNOUNCE_SendAnnounce (Username, Color, Time, Inc, Category, Rated, Min, Max)
References CONNECTION_SendJabber(), MESSAGE_AnnounceMatch(), UTILS_GetText(), and WINDOW_Alert().
Referenced by INTERFACE_AnnounceWindow().