XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/challengemenu.js File Reference
/home/www/rubens/webclient/scripts/interface/challengemenu.js File Reference
Functions
function ChallengeMenuObj ()
function INTERFACE_CreateChallengeMenu ()
function INTERFACE_AddMatchOffer (Oponent, Time, Inc, Rated, Private, MatchId)
function INTERFACE_RemoveMatch (MatchId)
function INTERFACE_AddAnnounce (Player, Time, Inc, Rated, Private, MatchId)
function INTERFACE_RemoveAnnounce (MatchId)
function INTERFACE_AddPostpone (Oponent, Category, Date, PostponeId)
function INTERFACE_RemovePostpone (PostponeId)
function INTERFACE_UpdatePostpone (OponentName, OponentStatus)
function INTERFACE_UpdatePostponeItem (Button, AdjournId)
function INTERFACE_ShowChallengeMenu (Left, Top)
function INTERFACE_ShowMatchOfferList ()
function INTERFACE_ShowAnnounceList ()
function INTERFACE_ShowPostponeList ()
function INTERFACE_HideChallengeMenu ()
function INTERFACE_HideMatchOfferList ()
function INTERFACE_HideAnnounceList ()
function INTERFACE_HidePostponeList ()
function INTERFACE_ShowNoMatch ()
function INTERFACE_HideNoMatch ()
function INTERFACE_ShowNoAnnounce ()
function INTERFACE_HideNoAnnounce ()
function INTERFACE_ShowNoPostpone ()
function INTERFACE_HideNoPostpone ()
function INTERFACE_ShowLoadingAnnounce ()
function INTERFACE_HideLoadingAnnounce ()
Function Documentation
function ChallengeMenuObj ()
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
References INTERFACE_AddAnnounce(), INTERFACE_AddMatchOffer(), INTERFACE_AddPostpone(), INTERFACE_CreateChallengeMenu(), INTERFACE_HideAnnounceList(), INTERFACE_HideChallengeMenu(), INTERFACE_HideLoadingAnnounce(), INTERFACE_HideMatchOfferList(), INTERFACE_HideNoAnnounce(), INTERFACE_HideNoMatch(), INTERFACE_HideNoPostpone(), INTERFACE_HidePostponeList(), INTERFACE_RemoveAnnounce(), INTERFACE_RemoveMatch(), INTERFACE_RemovePostpone(), INTERFACE_ShowAnnounceList(), INTERFACE_ShowChallengeMenu(), INTERFACE_ShowLoadingAnnounce(), INTERFACE_ShowMatchOfferList(), INTERFACE_ShowNoAnnounce(), INTERFACE_ShowNoMatch(), INTERFACE_ShowNoPostpone(), INTERFACE_ShowPostponeList(), and INTERFACE_UpdatePostpone().
function INTERFACE_AddAnnounce (Player, Time, Inc, Rated, Private, MatchId)
References ANNOUNCE_AcceptAnnounce(), ANNOUNCE_CancelAnnounce(), INTERFACE_CloseFullName(), INTERFACE_ShowFullName(), MainData, UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by AnnounceObj(), and ChallengeMenuObj().
function INTERFACE_AddMatchOffer (Oponent, Time, Inc, Rated, Private, MatchId)
References CHALLENGE_DeclineChallenge(), INTERFACE_CloseFullName(), INTERFACE_ShowFullName(), UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by ChallengeMenuObj(), and MatchOfferObj().
function INTERFACE_AddPostpone (Oponent, Category, Date, PostponeId)
References INTERFACE_CloseFullName(), INTERFACE_ShowFullName(), UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by ChallengeMenuObj(), and PostponeObj().
function INTERFACE_CreateChallengeMenu ()
References UTILS_CreateElement(), UTILS_GetText(), and WINDOW_AnnounceWindow().
Referenced by ChallengeMenuObj().
function INTERFACE_HideAnnounceList ()
Referenced by ChallengeMenuObj().
function INTERFACE_HideChallengeMenu ()
Referenced by ChallengeMenuObj().
function INTERFACE_HideLoadingAnnounce ()
Referenced by ChallengeMenuObj().
function INTERFACE_HideMatchOfferList ()
Referenced by ChallengeMenuObj().
function INTERFACE_HideNoAnnounce ()
Referenced by AnnounceObj(), and ChallengeMenuObj().
function INTERFACE_HideNoMatch ()
Referenced by ChallengeMenuObj(), and MatchOfferObj().
function INTERFACE_HideNoPostpone ()
Referenced by ChallengeMenuObj(), and PostponeObj().
function INTERFACE_HidePostponeList ()
Referenced by ChallengeMenuObj().
function INTERFACE_RemoveAnnounce (MatchId)
Referenced by AnnounceObj(), and ChallengeMenuObj().
function INTERFACE_RemoveMatch (MatchId)
Referenced by ChallengeMenuObj().
function INTERFACE_RemovePostpone (PostponeId)
Referenced by ChallengeMenuObj(), and PostponeObj().
function INTERFACE_ShowAnnounceList ()
Referenced by ChallengeMenuObj().
function INTERFACE_ShowChallengeMenu (Left, Top)
References MainData.
Referenced by ChallengeMenuObj().
function INTERFACE_ShowLoadingAnnounce ()
Referenced by ChallengeMenuObj().
function INTERFACE_ShowMatchOfferList ()
Referenced by ChallengeMenuObj().
function INTERFACE_ShowNoAnnounce ()
Referenced by AnnounceObj(), and ChallengeMenuObj().
function INTERFACE_ShowNoMatch ()
Referenced by ChallengeMenuObj(), and MatchOfferObj().
function INTERFACE_ShowNoPostpone ()
Referenced by ChallengeMenuObj(), and PostponeObj().
function INTERFACE_ShowPostponeList ()
Referenced by ChallengeMenuObj().
function INTERFACE_UpdatePostpone (OponentName, OponentStatus)
References INTERFACE_UpdatePostponeItem().
Referenced by ChallengeMenuObj(), and PostponeObj().
function INTERFACE_UpdatePostponeItem (Button, AdjournId)
References CHALLENGE_SendResumeGame().
Referenced by INTERFACE_UpdatePostpone().