XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/chat/chat.js File Reference
/home/www/rubens/webclient/scripts/chat/chat.js File Reference
Functions
function CHAT_HandleMessage (XML)
function CHAT_HandlePresence (XML)
Parse and show user chat presence.
function CHAT_HandleAnnounceMessage (XML)
Show announcement messages.
function CHAT_OpenChat (Username)
Open a chat with some user.
function CHAT_CloseChat (Username)
Close a chat window with other user.
function CHAT_ChangeChatState (Username)
Change visibility of chat window.
function CHAT_SendMessage (Username, Message)
Send a chat message.
function CHAT_ReceiveMessage (Username, Message)
Show a message received from another user.
function CHAT_ErrorMessageLength (Username)
Show message length error notification.
function CHAT_ChangeUserChatStatus (Username, Status)
Change chat window title accordly user status.
function CHAT_BlurChat (Username)
Remove focus from chat window.
Function Documentation
function CHAT_BlurChat (Username)
Remove focus from chat window.
Parameters:
Username Name used by user
Returns:
Empty string
Author:
Rubens Suguimoto
References ChatObj(), and MainData.
Referenced by INTERFACE_CreateChat().
function CHAT_ChangeChatState (Username)
Change visibility of chat window.
Parameters:
Username Name used by user
Returns:
Empty string
Author:
Pedro Rocha and Rubens Suguimoto
References ChatObj(), and MainData.
Referenced by INTERFACE_CreateChat().
function CHAT_ChangeUserChatStatus (Username, Status)
Change chat window title accordly user status.
Parameters:
Username Name used by user
Status User status (offline or others)
Returns:
Empty string
Author:
Rubens Suguimoto
References ChatObj(), and MainData.
Referenced by CHAT_HandlePresence().
function CHAT_CloseChat (Username)
Close a chat window with other user.
Parameters:
Username Name used by user
Returns:
Empty string
Author:
Pedro Rocha and Rubens Suguimoto
References ChatObj(), and MainData.
Referenced by INTERFACE_CreateChat().
function CHAT_ErrorMessageLength (Username)
Show message length error notification.
Show in window chat a message with length exceeded error
Parameters:
Username Name used by user
Returns:
Message with error notification
Author:
Rubens Suguimoto
References ChatObj(), MainData, and UTILS_GetText().
Referenced by INTERFACE_CreateChat().
function CHAT_HandleAnnounceMessage (XML)
Show announcement messages.
Parameters:
XML XML with announce message
Returns:
Buffer with other XMPP to send
Author:
Pedro Rocha
References MainData, UTILS_GetNodeText(), and WINDOW_Alert().
Referenced by PARSER_ParseChat().
function CHAT_HandleMessage (XML)
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
References CHAT_ReceiveMessage(), UTILS_ConvertChatString(), and UTILS_GetNodeText().
Referenced by PARSER_ParseChat().
function CHAT_HandlePresence (XML)
Parse and show user chat presence.
Parameters:
XML XML with presence
Returns:
Buffer with other XMPP to send
Author:
Rubens Suguimoto
References CHAT_ChangeUserChatStatus().
Referenced by PARSER_ParsePresence().
function CHAT_OpenChat (Username)
Open a chat with some user.
Parameters:
Username Name used by user
Returns:
Chat window object
Author:
Pedro Rocha and Rubens Suguimoto
References ChatObj(), MainData, UTILS_GetText(), and WINDOW_Alert().
Referenced by CHAT_ReceiveMessage(), CONTACT_ShowUserMenu(), INTERFACE_ShowPostponeWindow(), and WINDOW_Challenge().
function CHAT_ReceiveMessage (Username, Message)
Show a message received from another user.
Parameters:
Username Name used by user
Message Message received
Returns:
Empty string
Author:
Pedro Rocha
References CHAT_OpenChat(), ChatObj(), MainData, and UTILS_BannedWords().
Referenced by CHAT_HandleMessage().
function CHAT_SendMessage (Username, Message)
Send a chat message.
Parameters:
Username Name used by user
Message Message to send
Returns:
Empty string
Author:
Pedro Rocha
References ChatObj(), CONNECTION_SendJabber(), MainData, MESSAGE_Chat(), UTILS_BannedWords(), and UTILS_ConvertChatString().
Referenced by INTERFACE_CreateChat().