XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/connection/connection.js File Reference
/home/www/rubens/webclient/scripts/connection/connection.js File Reference
This file has all functions that is used to provide a connection with a Jabber Server.
Functions
function CONNECTION_ConnectJabber (XML)
Open connection with Jabber server.
function CONNECTION_SendJabber ()
Send a XML post.
function CONNECTION_ReceiveConnection (HttpRequest)
Receive Connection messages and make all steps to connect user.
function CONNECTION_ReceiveXml (HttpRequest)
Receive a Jabber message when user is already connected.
Detailed Description
This file has all functions that is used to provide a connection with a Jabber Server.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function CONNECTION_ConnectJabber (XML)
Open connection with Jabber server.
Returns:
Empty string;
Author:
Pedro Rocha
References CONNECTION_SendJabber(), LOGIN_LoginMsg(), MainData, MESSAGE_SendPasswd(), MESSAGE_SendUsername(), MESSAGE_StartConnection(), and UTILS_GetText().
Referenced by CONNECTION_ReceiveConnection(), and LOGIN_Login().
function CONNECTION_ReceiveConnection (HttpRequest)
Receive Connection messages and make all steps to connect user.
Returns:
Empty string
Author:
Pedro Rocha
References CONNECTION_ConnectJabber(), CONNECTION_SendJabber(), HttpRequest, LOAD_StartLoad(), LOGIN_LoginFailed(), MainData, MESSAGE_Wait(), and UTILS_GetText().
Referenced by CONNECTION_SendJabber().
function CONNECTION_ReceiveXml (HttpRequest)
Receive a Jabber message when user is already connected.
Returns:
Empty string
Author:
Pedro Rocha
References CONNECTION_SendJabber(), HttpRequest, MainData, MESSAGE_Wait(), PARSER_ParseXml(), START_Restart(), and UTILS_GetText().
Referenced by CONNECTION_SendJabber().
function CONNECTION_SendJabber ()
Send a XML post.
You can pass more than one XML message as parameter
Returns:
Empty string
Author:
Pedro Rocha
References CONNECTION_ReceiveConnection(), CONNECTION_ReceiveXml(), HttpRequest, MainData, and MESSAGE_MakeXMPP().
Referenced by ADMIN_BanUser(), ADMIN_BanWord(), ADMIN_GetBanList(), ADMIN_GetBannedWords(), ADMIN_KickUser(), ADMIN_RemoveBannedWord(), ADMIN_UnbanUser(), ANNOUNCE_AcceptAnnounce(), ANNOUNCE_CancelAnnounce(), ANNOUNCE_GetAnnounceGames(), ANNOUNCE_SendAnnounce(), CHALLENGE_AcceptChallenge(), CHALLENGE_DeclineChallenge(), CHALLENGE_GetAdjournGames(), CHALLENGE_SendChallenge(), CHALLENGE_SendReChallenge(), CHALLENGE_SendResumeGame(), CHAT_SendMessage(), CONNECTION_ConnectJabber(), CONNECTION_ReceiveConnection(), CONNECTION_ReceiveXml(), CONTACT_ChangeStatus(), CONTACT_InviteUser(), CONTACT_ReceiveSubscribe(), CONTACT_SendRemoveUser(), GAME_HandleAdjourn(), GAME_HandleCancel(), GAME_HandleDraw(), GAME_SearchCurrentGame(), GAME_SendAdjourn(), GAME_SendCancel(), GAME_SendDraw(), GAME_SendMove(), GAME_SendResign(), GAME_StartObserverGame(), GAMECENTER_ShowCurrentGames(), GAMECENTER_ShowPostpone(), INTERFACE_AddCurrentGames(), INTERFACE_AddOldGameResult(), INTERFACE_CreateGameCenterAnnounce(), INTERFACE_CreateGameCenterCurrentGames(), INTERFACE_SetNextButton(), INTERFACE_SetPrevButton(), INTERFACE_SetSearchButton(), INTERFACE_ShowCreateRoomWindow(), INTERFACE_ShowGameRoomList(), LOGIN_LeavePage(), LOGIN_Logout(), OLDGAME_OpenOldGameWindow(), PROFILE_SaveMyProfile(), PROFILE_StartProfile(), ROOM_EnterRoom(), ROOM_EnterRoomGame(), ROOM_ExitRoom(), ROOM_SendMessage(), ROOM_ShowRoomList(), START_Webclient(), and USER_UpdateUserList().