XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/contact/contact.js File Reference
/home/www/rubens/webclient/scripts/contact/contact.js File Reference
Handle all messages and functions to user's contact list.
Functions
function CONTACT_StartContactList ()
Create contact list object and hide contact list.
function CONTACT_HandleContactUserList (XML)
Handle user list received from jabber with yours contacts.
function CONTACT_HandleSetSubscribe (XML)
Handle receive subscribe from other user.
function CONTACT_HandleUserPresence (XML)
Handle a invite from some user and check his/her status.
function CONTACT_AddUser (Username, Status, Subs, Group)
Add user in contact list.
function CONTACT_RemoveUser (Username)
Remove user from your list.
function CONTACT_ShowUserMenu (Obj, Username)
Show user menu options.
function CONTACT_LoadUserContactList ()
Load contact list in interface.
function CONTACT_SortUsersByNick ()
Sort user contact list by nick name.
function CONTACT_SortUsersByRating (Category)
Sort user contact list by rating category.
function CONTACT_IsContact (Username)
Check if some user is in your contact list.
Detailed Description
Handle all messages and functions to user's contact list.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function CONTACT_AddUser (Username, Status, Subs, Group)
Add user in contact list.
Add user in MainData contact list, sort and show this user in interface.
Parameters:
Username User's name
Status User's status
Subs User's subscribe status
Group User's group in contact list
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References ContactObj(), and MainData.
Referenced by CONTACT_HandleContactUserList(), CONTACT_InviteUser(), CONTACT_ReceiveSubscribe(), and CONTACT_ReceiveSubscribed().
function CONTACT_HandleContactUserList (XML)
Handle user list received from jabber with yours contacts.
Parameters:
XML XML response with user's contact list
Returns:
XMPP message
Author:
Ulysses Bonfim
References CONTACT_AddUser(), CONTACT_RemoveUser(), MainData, MESSAGE_InviteAccept(), and UTILS_GetNodeText().
Referenced by PARSER_ParseIq().
function CONTACT_HandleSetSubscribe (XML)
Handle receive subscribe from other user.
Parameters:
XML XML message with contact list information
Returns:
XMPP message
Author:
Ulysses Bonfim
References CONTACT_RemoveUser(), and UTILS_GetNodeText().
Referenced by PARSER_ParseIq().
function CONTACT_HandleUserPresence (XML)
Handle a invite from some user and check his/her status.
Handle for accept or decline invite from some user and check user's status
Parameters:
XML XML message with contact list information
Returns:
XMPP message
Author:
Ulysses Bonfim
References CONTACT_ReceiveSubscribe(), CONTACT_ReceiveSubscribed(), CONTACT_ReceiveUnsubscribed(), CONTACT_SetUserStatus(), and UTILS_GetNodeText().
Referenced by PARSER_ParsePresence().
function CONTACT_IsContact (Username)
Check if some user is in your contact list.
Parameters:
Username User's name
Returns:
True or False
Author:
Rubens Suguimoto and Danilo Yorinori
References MainData.
Referenced by CONTACT_ShowUserMenu().
function CONTACT_LoadUserContactList ()
Load contact list in interface.
Returns:
none
Author:
Rubens Suguimoto
References ContactObj(), and MainData.
Referenced by START_Webclient().
function CONTACT_RemoveUser (Username)
Remove user from your list.
Parameters:
Username User's name
Author:
Rubens Suguimoto
Returns:
True
References ContactObj(), and MainData.
Referenced by CONTACT_HandleContactUserList(), and CONTACT_HandleSetSubscribe().
function CONTACT_ShowUserMenu (Obj, Username)
Show user menu options.
Show user menu to send private message, match, view profile, etc.
Parameters:
Obj DOM element to get position to show user menu
Username User's name
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
Setting options
References CHAT_OpenChat(), CONTACT_InviteUser(), CONTACT_IsContact(), CONTACT_SendRemoveUser(), INTERFACE_HideUserMenu(), INTERFACE_ShowUserMenu(), MainData, PROFILE_StartProfile(), USER_AddUser(), UTILS_AddListener(), UTILS_GetText(), UTILS_RemoveListener(), WINDOW_BanUser(), WINDOW_Challenge(), WINDOW_Confirm(), and WINDOW_KickUser().
Referenced by INTERFACE_CreateUser(), and INTERFACE_CreateUserElement().
function CONTACT_SortUsersByNick ()
Sort user contact list by nick name.
Sort user online list by nick name. Sort in MainData and for each user in MainData online user, remove and insert it.
Returns:
none
Author:
Rubens Suguimoto and Danilo Yorinori
References ContactObj(), and MainData.
Referenced by ContactObj().
function CONTACT_SortUsersByRating (Category)
Sort user contact list by rating category.
Sort user contact list by rating. Sort in MainData and for each user in MainData online user, remove and insert it.
Parameters:
Category Game category
Returns:
none
Author:
Rubens Suguimoto and Danilo Yorinori
References ContactObj(), and MainData.
Referenced by ContactObj().
function CONTACT_StartContactList ()
Create contact list object and hide contact list.
Returns:
none
Author:
Rubens Suguimoto
References ContactObj(), and MainData.
Referenced by START_Webclient().