XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/contact/user.js File Reference
/home/www/rubens/webclient/scripts/contact/user.js File Reference
Handle user messages.
Functions
function USER_HandleContactUserList (XML)
Handle user list received from jabber with yours contacts to list of users.
function USER_HandlePresence (XML)
Handle user's presence to list of users.
function USER_HandleRoomPresence (XML)
Handle user's room presence to list of users.
function USER_HandleInfo (XML)
Handle user's chess informations.
function USER_AddUser (Username, Status)
Add some user in user list.
function USER_StartUpdateUserList ()
Start counter to update list of user's chess informations.
function USER_StopUpdateUserList ()
Stop counter to update list of user's chess informations.
function USER_StartUpdateUserProfile ()
Start counter to update list of user's jabber informations.
function USER_StopUpdateUserProfile ()
Stop counter to update list of user's jabber informations.
function USER_UpdateUserList ()
Send message to update list of users.
Detailed Description
Handle user messages.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function USER_AddUser (Username, Status)
Add some user in user list.
Parameters:
Username User's name
Status User's status
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by CHALLENGE_HandleAdjourn(), CONTACT_ShowUserMenu(), PROFILE_StartProfile(), START_Webclient(), USER_HandleContactUserList(), and USER_HandlePresence().
function USER_HandleContactUserList (XML)
Handle user list received from jabber with yours contacts to list of users.
All functions listed in this file, access a list of users in main data. This struct store all online user's information.
Returns:
Empty string
Author:
Rubens Suguimoto
References USER_AddUser().
Referenced by PARSER_ParseIq().
function USER_HandleInfo (XML)
Handle user's chess informations.
Parameters:
XML XMPP with user's chess informations
Returns:
Empty string
Author:
Rubens Suguimoto
References MainData, and UTILS_ConvertTimeStamp().
Referenced by PARSER_ParseIq().
function USER_HandlePresence (XML)
Handle user's presence to list of users.
Parameters:
XML XMPP with presence
Returns:
Empty string
Author:
Rubens Suguimoto
References USER_AddUser(), and UTILS_GetNodeText().
Referenced by PARSER_ParsePresence().
function USER_HandleRoomPresence (XML)
Handle user's room presence to list of users.
Parameters:
XML XMPP with room presence
Returns:
Empty string
Author:
Rubens Suguimoto
References UTILS_GetNodeText().
Referenced by PARSER_ParsePresence().
function USER_StartUpdateUserList ()
Start counter to update list of user's chess informations.
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by START_Webclient().
function USER_StartUpdateUserProfile ()
Start counter to update list of user's jabber informations.
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by START_Webclient().
function USER_StopUpdateUserList ()
Stop counter to update list of user's chess informations.
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by START_Restart().
function USER_StopUpdateUserProfile ()
Stop counter to update list of user's jabber informations.
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by START_Restart().
function USER_UpdateUserList ()
Send message to update list of users.
Returns:
none
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, and MESSAGE_InfoProfile().