XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/game/currentgame.js File Reference
/home/www/rubens/webclient/scripts/game/currentgame.js File Reference
Functions
function CURRENTGAME_HandleGameRoomList (XML)
Handle game room list.
function CURRENTGAME_HandleGameRoomInfoList (XML)
Handle game room information.
function CURRENTGAME_HandleGameRoomInfoError (XML)
Handle game room information.
Function Documentation
function CURRENTGAME_HandleGameRoomInfoError (XML)
Handle game room information.
Get game room information and show in interface
Parameters:
XML XMPP with game room erros
Returns:
none
Author:
Rubens Suguimoto
References MainData, UTILS_GetText(), and WINDOW_Alert().
Referenced by PARSER_ParseIq().
function CURRENTGAME_HandleGameRoomInfoList (XML)
Handle game room information.
Get game room information and show in interface
Parameters:
XML XMPP with games rooms informations
Returns:
XMPP to send
Author:
Rubens Suguimoto
References GAME_StartObserverGame(), and MainData.
Referenced by PARSER_ParseIq().
function CURRENTGAME_HandleGameRoomList (XML)
Handle game room list.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. For each current game, send a request to get game information
Parameters:
XML XMPP with game rooms
Returns:
XMPP to send
Author:
Ulysses Bomfim and Rubens Suguimoto
References INTERFACE_NoGamesInGameList(), MainData, and MESSAGE_GameRoomInfoList().
Referenced by PARSER_ParseIq().