XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/data/data.js File Reference
/home/www/rubens/webclient/scripts/data/data.js File Reference
Class definition for main data structure.
Functions
function DATA (ConfFile, LangFile)
function DATA_AddHttpPost (PostObj)
function DATA_RemoveHttpPost (PostObj)
function DATA_FindHttpPost (PostObj)
function DATA_GetHttpRequestLength ()
function DATA_GetConnectionStatus ()
function DATA_SetConnectionStatus (Value)
function DATA_GetRID ()
function DATA_SetRID (Value)
function DATA_GetSID ()
function DATA_SetSID (Value)
function DATA_GetHost ()
function DATA_GetHostPost ()
function DATA_GetBrowser ()
function DATA_GetResource ()
function DATA_GetServer ()
function DATA_GetConferenceComponent ()
function DATA_GetSearchComponent ()
function DATA_GetText ()
function DATA_SetText (FileXML)
function DATA_GetDefaultText ()
function DATA_GetConst ()
function DATA_GetXmlns ()
function DATA_GetVersion ()
function DATA_GetCookieValidity ()
function DATA_GetLang ()
function DATA_SetLang (Lang)
function DATA_GetDefaultPHP ()
function DATA_GetUpdateRatingInterval ()
function DATA_GetUpdateGetMaxProfiles ()
function DATA_AddContactUser (Username, Status, Subs, Group)
function DATA_RemoveContactUser (Username)
function DATA_FindContactUser (Username)
function DATA_GetContactUser (Username)
function DATA_SortContactUserByNick ()
Sort Userlist into ascending or descending order.
function DATA_SortContactUserByRating ()
Sort Userlist into descending order by Rating selected in interface.
function DATA_GetContactUserList ()
function DATA_SetContactObj (Obj)
function DATA_GetContactObj ()
function DATA_SetContactOrderBy (NewValue)
function DATA_GetContactOrderBy ()
function DATA_SetContactCurrentRating (NewCategory)
function DATA_GetContactCurrentRating ()
function DATA_AddOnlineUser (Username, Status, Type)
function DATA_RemoveOnlineUser (Username)
function DATA_FindOnlineUser (Username)
function DATA_GetOnlineUser (Username)
function DATA_SortOnlineUserByNick ()
Sort Userlist into ascending or descending order.
function DATA_SortOnlineUserByRating ()
Sort Userlist into descending order by Rating selected in interface.
function DATA_GetOnlineUserList ()
function DATA_SetOnlineObj (Obj)
function DATA_GetOnlineObj ()
function DATA_SetOnlineOrderBy (NewValue)
function DATA_GetOnlineOrderBy ()
function DATA_SetOnlineCurrentRating (NewCategory)
function DATA_GetOnlineCurrentRating ()
function DATA_GetUsername ()
function DATA_SetStatus (NewStatus)
function DATA_GetStatus ()
function DATA_SetSubs (NewSubs)
function DATA_GetSubs ()
function DATA_SetGroup (NewGroup)
function DATA_GetGroup ()
function DATA_SetPhoto (NewPhoto)
function DATA_GetPhoto ()
function DATA_SetImg64 (Image)
function DATA_GetImg64 ()
function DATA_SetImgType (ImageType)
function DATA_GetImgType ()
function DATA_GetRatingList ()
function DATA_SetType (NewType)
function DATA_GetType ()
function DATA_SetRole (NewRole)
function DATA_GetRole ()
function DATA_SetAfilliation (NewAfilliation)
function DATA_GetAfilliation ()
function DATA_GetUpdateRating ()
function DATA_SetUpdateRating (Bool)
function DATA_GetUpdateProfile ()
function DATA_SetUpdateProfile (Bool)
function DATA_SetFullname (NewName)
function DATA_GetFullname ()
function DATA_SetDesc (NewDesc)
function DATA_GetDesc ()
function DATA_SetLastGame (LastGame)
function DATA_GetLastGame ()
function DATA_SetOnlineTime (Time)
function DATA_GetOnlineTime ()
function DATA_SetTotalTime (Time)
function DATA_GetTotalTime ()
function DATA_SetWarning (Warning)
function DATA_GetWarning ()
function DATA_SetTypeTitle (Title)
function DATA_GetTypeTitle ()
function DATA_SetProfileObj (ProfileObj)
function DATA_GetProfileObj ()
function DATA_RatingObject ()
function DATA_AddRating (Category, Value, RecordValue, RecordTime, Win, Draw, Losses)
function DATA_RemoveRating (Category)
function DATA_FindRating (Category)
function DATA_GetRating (Category)
function DATA_GetRatingValue (Category)
function DATA_SetRatingValue (Category, Value)
function DATA_GetRecordValue (Category)
function DATA_SetRecordValue (Category, Value)
function DATA_GetRecordTime (Category)
function DATA_SetRecordTime (Category, Time)
function DATA_GetRatingWin (Category)
function DATA_SetRatingWin (Category, Value)
function DATA_GetRatingDraw (Category)
function DATA_SetRatingDraw (Category, Value)
function DATA_GetRatingLosses (Category)
function DATA_SetRatingLosses (Category, Value)
function DATA_AddUser (Username, Status)
Add user to user list.
function DATA_RemoveUser (Username)
Remove user from user list.
function DATA_FindUser (Username)
Find user in user list.
function DATA_GetUser (Username)
function DATA_GetUserList ()
function DATA_SetUpdateTimer (Interval)
function DATA_GetUpdateTimer ()
function DATA_SetUpdateProfileTimer (Interval)
function DATA_GetUpdateProfileTimer ()
function DATA_AddRoom (RoomName, MsgTo, Role, Affiliation, RoomObj)
Create new room in room list.
function DATA_RemoveRoom (RoomName)
Delete a room in room list.
function DATA_FindRoom (RoomName)
Find room in room list.
function DATA_SetRoomInformation (RoomName, From, Affiliation, Role)
Set from, affiliation and role in 'RoomName' structure.
function DATA_GetRoomList ()
function DATA_GetEmoticonNum ()
function DATA_GetMaxRooms ()
function DATA_GetMaxRoomChar ()
function DATA_GetRoomDefault ()
function DATA_SetCurrentRoom (RoomObj)
function DATA_GetCurrentRoom ()
function DATA_AddUserInRoom (Username, Status, Type, Role, Affiliation)
Add user in user list of a room.
function DATA_FindUserInRoom (Username)
Find user in user list of a room.
function DATA_GetUserInRoom (Username)
Get user object in user list of room.
function DATA_SetUserInfoInRoom (Username, Status, Role, Affiliation)
Set user attibutes in 'RoomName'.
function DATA_RemoveUserInRoom (Username)
Delete user from user list of a room.
function DATA_GetUserRatingInRoom (Username, Category)
Get user's rating.
function DATA_SortUserByNickInRoom ()
Sort Userlist from Room into ascending or descending order.
function DATA_SortUserByRatingInRoom ()
Sort Userlist from Room into descending order by Rating.
function DATA_GetRoom (RoomName)
Get room from room list.
function DATA_SetRoomOrderBy (Value)
function DATA_GetRoomOrderBy ()
function DATA_SetRoomCurrentRating (RatingType)
function DATA_GetRoomCurrentRating ()
function DATA_AddChat (Username, ChatObj)
Add a chat in interface structure, with the other user name and his status.
function DATA_RemoveChat (Username)
Remove a chat with the user given from the structure.
function DATA_FindChat (Username)
Find a chat with ohter user.
function DATA_GetChat (Username)
function DATA_GetChatListLength ()
function DATA_SetMaxChats (NewMax)
function DATA_GetMaxChats ()
function DATA_SetMaxChatChar (MaxChar)
function DATA_GetMaxChatChar ()
function DATA_AddShowChat (ChatObj)
function DATA_RemoveShowChat (Username)
function DATA_AddChallenge (ChallengeId, Challenger, Challenged, Category, Rated, MatchId)
Add a challenge in 'ChallengeList'.
function DATA_UpdateChallenge (ChallengeId, Challenger, Challenged, Category, Rated, MatchId)
function DATA_RemoveChallenge (ChallengeId, MatchId)
Remove a challenge.
function DATA_FindChallenge (ChallengeId, MatchId)
Find a challenge.
function DATA_GetChallenge (ChallengeId, MatchId)
function DATA_AddChallengeWindow (Id, WindowObj)
Set a Challenge window pointer in challenge item.
function DATA_GetChallengeList ()
function DATA_SetChallengeMenu (MenuObj)
function DATA_GetChallengeMenu ()
function DATA_SetChallengeSequence (NewValue)
function DATA_GetChallengeSequence ()
function DATA_SetCurrentGame (Game)
Set current game.
function DATA_GetCurrentGame ()
Get current game.
function DATA_AddGame (Id, Player1, Player2, Color, GameDiv)
Add a game.
function DATA_RemoveGame (Id)
Remove a game.
function DATA_FindGame (Id)
Find game by game id.
function DATA_AddGameMove (BoardArray, Move, ShortMove, PWTime, PBTime, Turn)
Add a move in game.
function DATA_SetTurnGame (TurnColor)
Set your turn flag.
function DATA_GetGame (Id)
Get game item.
function DATA_SetCurrentOldGame (Game)
Set current oldgame.
function DATA_GetCurrentOldGame ()
Get current oldgame.
function DATA_AddOldGame (PWName, PBName, Color, GameDiv)
Add a oldgame.
function DATA_RemoveOldGame (Id)
Remove a oldgame.
function DATA_GetOldGame (Id)
Get old game item.
function DATA_PushGameToOldGame (GameObj)
Set a normal game as the current old game.
function DATA_AddSearchGameInfo (Id, Elements, User)
Add search game window parameters.
function DATA_RemoveSearchGameInfo (Id)
Remove search game window.
function DATA_FindSearchGameInfo (Id)
Find search game window.
function DATA_GetSearchGameInfo (Id)
function DATA_SetPassword (NewPassword)
function DATA_GetPassword ()
function DATA_SetMyUsername (Username)
function DATA_GetMyUsername ()
function DATA_SetAwayCounter (Counter)
function DATA_GetAwayCounter ()
function DATA_SetAwayInterval (Interval)
function DATA_GetAwayInterval ()
function DATA_AddWindow (WindowObj)
Add a WindowObject in WindowList.
function DATA_SetWindowFocus (WindowObj)
Set Window Object in focus.
function DATA_GetWindowFocus ()
function DATA_GetWindowListLength ()
function DATA_GetWindow (Index)
function DATA_RemoveWindow (WindowObj)
Remove a Window Object from WindowList.
function DATA_FindWindow (WindowObj)
Find Window Object positon in WindowList.
function DATA_SetLoadObj (Obj)
function DATA_GetLoadObj ()
function DATA_AddProfile (Jid, Username, ProfileWindow)
function DATA_FindProfile (Jid)
function DATA_RemoveProfile (Jid)
function DATA_GetProfile (Jid)
function DATA_SetMyProfile (Username, FullName, Desc, ImgType, Img64)
function DATA_AddSearchUserInfo (Elements)
Add search user window parameters.
function DATA_RemoveSearchUserInfo ()
Remove search user window.
function DATA_SortSearchUserByNick ()
Sort Userlist into ascending or descending order.
function DATA_SortSearchUserByName ()
Sort Userlist into descending order by Rating selected in interface.
function DATA_SetGamecenter (Obj)
function DATA_GetGamecenter ()
function DATA_AddAnnounce (Player, Rating, Time, Inc, Category, Rated, Private, AnnounceId)
function DATA_RemoveAnnounce (AnnounceId)
function DATA_FindAnnounce (AnnounceId)
function DATA_GetAnnounce (AnnounceId)
function DATA_GetAnnounceList ()
function DATA_AddPostpone (Player, Time, Inc, Category, Rating, Date, Status, PostponeId)
Add a postponed game.
function DATA_FindPostpone (PostponeId)
function DATA_RemovePostpone (PostponeId)
Remove a postpone challenge in 'PostponeList'.
function DATA_GetPostpone (PostponeId)
function DATA_GetPostponeList ()
function DATA_SetPostponeStatus (PostponeId, Status)
function DATA_AddCurrentGames (WPlayer, WRating, BPlayer, BRating, Category, Time, Rated, Moves, CurrentGamesId)
Add a current game.
function DATA_FindCurrentGames (CurrentGamesId)
function DATA_RemoveCurrentGames (CurrentGamesId)
Remove a current game.
function DATA_GetCurrentGames (CurrentGamesId)
function DATA_GetCurrentGamesList ()
function DATA_AddMatchOffer (Player, Time, Inc, Category, Rated, Private, MatchOfferId)
Add a offered match.
function DATA_FindMatchOffer (MatchOfferId)
function DATA_RemoveMatchOffer (MatchOfferId)
Remove a offered match.
function DATA_GetMatchOffer (MatchOfferId)
function DATA_GetMatchOfferList ()
function DATA_SetAdmincenter (Obj)
function DATA_GetAdmincenter ()
function DATA_AddPunish (Name, Punish, Incident, Date, Period, Reason)
function DATA_RemovePunish (PunishId)
function DATA_FindPunish (PunishId)
function DATA_GetPunish (PunishId)
function DATA_GetPunishList ()
function DATA_AddLevel (Name, Level)
function DATA_RemoveLevel (LevelId)
function DATA_FindLevel (LevelId)
function DATA_GetLevel (LevelId)
function DATA_GetLevelList ()
function DATA_AddAdminLevel (Name, Level)
function DATA_RemoveAdminLevel (AdminLevelId)
function DATA_FindAdminLevel (AdminLevelId)
function DATA_GetAdminLevel (AdminLevelId)
function DATA_GetAdminLevelList ()
function DATA_AddAdjourn (WName, WRating, BName, BRating, Category, GameTime, Inc, Rated, AdjournId)
function DATA_RemoveAdjourn (AdjournId)
function DATA_FindAdjourn (AdjournId)
function DATA_GetAdjourn (AdjournId)
function DATA_GetAdjournList ()
function DATA_AddWords (WordString)
function DATA_RemoveWords (WordId)
function DATA_FindWords (WordId)
function DATA_GetWords (WordId)
function DATA_GetWordsList ()
Variables
DATA prototype AddHttpPost = DATA_AddHttpPost
DATA prototype RemoveHttpPost = DATA_RemoveHttpPost
DATA prototype FindHttpPost = DATA_FindHttpPost
DATA prototype GetHttpRequestLength = DATA_GetHttpRequestLength
DATA prototype GetConnectionStatus = DATA_GetConnectionStatus
DATA prototype SetConnectionStatus = DATA_SetConnectionStatus
DATA prototype GetRID = DATA_GetRID
DATA prototype SetRID = DATA_SetRID
DATA prototype GetSID = DATA_GetSID
DATA prototype SetSID = DATA_SetSID
DATA prototype GetHost = DATA_GetHost
DATA prototype GetHostPost = DATA_GetHostPost
DATA prototype GetBrowser = DATA_GetBrowser
DATA prototype GetResource = DATA_GetResource
DATA prototype GetServer = DATA_GetServer
DATA prototype GetConferenceComponent = DATA_GetConferenceComponent
DATA prototype GetSearchComponent = DATA_GetSearchComponent
DATA prototype GetText = DATA_GetText
DATA prototype SetText = DATA_SetText
DATA prototype GetDefaultText = DATA_GetDefaultText
DATA prototype GetConst = DATA_GetConst
DATA prototype GetXmlns = DATA_GetXmlns
DATA prototype GetVersion = DATA_GetVersion
DATA prototype GetCookieValidity = DATA_GetCookieValidity
DATA prototype GetLang = DATA_GetLang
DATA prototype SetLang = DATA_SetLang
DATA prototype GetDefaultPHP = DATA_GetDefaultPHP
DATA prototype GetUpdateRatingInterval = DATA_GetUpdateRatingInterval
DATA prototype GetUpdateGetMaxProfiles = DATA_GetUpdateGetMaxProfiles
DATA prototype AddContactUser = DATA_AddContactUser
DATA prototype RemoveContactUser = DATA_RemoveContactUser
DATA prototype FindContactUser = DATA_FindContactUser
DATA prototype GetContactUser = DATA_GetContactUser
DATA prototype SortContactUserByNick = DATA_SortContactUserByNick
DATA prototype SortContactUserByRating = DATA_SortContactUserByRating
DATA prototype GetContactUserList = DATA_GetContactUserList
DATA prototype SetContactObj = DATA_SetContactObj
DATA prototype GetContactObj = DATA_GetContactObj
DATA prototype SetContactOrderBy = DATA_SetContactOrderBy
DATA prototype GetContactOrderBy = DATA_GetContactOrderBy
DATA prototype SetContactCurrentRating = DATA_SetContactCurrentRating
DATA prototype GetContactCurrentRating = DATA_GetContactCurrentRating
DATA prototype AddOnlineUser = DATA_AddOnlineUser
DATA prototype RemoveOnlineUser = DATA_RemoveOnlineUser
DATA prototype FindOnlineUser = DATA_FindOnlineUser
DATA prototype GetOnlineUser = DATA_GetOnlineUser
DATA prototype SortOnlineUserByNick = DATA_SortOnlineUserByNick
DATA prototype SortOnlineUserByRating = DATA_SortOnlineUserByRating
DATA prototype GetOnlineUserList = DATA_GetOnlineUserList
DATA prototype SetOnlineObj = DATA_SetOnlineObj
DATA prototype GetOnlineObj = DATA_GetOnlineObj
DATA prototype SetOnlineOrderBy = DATA_SetOnlineOrderBy
DATA prototype GetOnlineOrderBy = DATA_GetOnlineOrderBy
DATA prototype SetOnlineCurrentRating = DATA_SetOnlineCurrentRating
DATA prototype GetOnlineCurrentRating = DATA_GetOnlineCurrentRating
DATA prototype AddUser = DATA_AddUser
DATA prototype RemoveUser = DATA_RemoveUser
DATA prototype FindUser = DATA_FindUser
DATA prototype GetUser = DATA_GetUser
DATA prototype GetUserList = DATA_GetUserList
DATA prototype SetUpdateTimer = DATA_SetUpdateTimer
DATA prototype GetUpdateTimer = DATA_GetUpdateTimer
DATA prototype SetUpdateProfileTimer = DATA_SetUpdateProfileTimer
DATA prototype GetUpdateProfileTimer = DATA_GetUpdateProfileTimer
DATA prototype AddRoom = DATA_AddRoom
DATA prototype RemoveRoom = DATA_RemoveRoom
DATA prototype FindRoom = DATA_FindRoom
DATA prototype SetRoomInformation = DATA_SetRoomInformation
DATA prototype GetRoomList = DATA_GetRoomList
DATA prototype GetEmoticonNum = DATA_GetEmoticonNum
DATA prototype GetMaxRooms = DATA_GetMaxRooms
DATA prototype GetMaxRoomChar = DATA_GetMaxRoomChar
DATA prototype GetRoomDefault = DATA_GetRoomDefault
DATA prototype SetCurrentRoom = DATA_SetCurrentRoom
DATA prototype GetCurrentRoom = DATA_GetCurrentRoom
DATA prototype GetRoom = DATA_GetRoom
DATA prototype AddChat = DATA_AddChat
DATA prototype RemoveChat = DATA_RemoveChat
DATA prototype FindChat = DATA_FindChat
DATA prototype GetChat = DATA_GetChat
DATA prototype GetChatListLength = DATA_GetChatListLength
DATA prototype SetMaxChats = DATA_SetMaxChats
DATA prototype GetMaxChats = DATA_GetMaxChats
DATA prototype SetMaxChatChar = DATA_SetMaxChatChar
DATA prototype GetMaxChatChar = DATA_GetMaxChatChar
DATA prototype AddShowChat = DATA_AddShowChat
DATA prototype RemoveShowChat = DATA_RemoveShowChat
DATA prototype AddChallenge = DATA_AddChallenge
DATA prototype RemoveChallenge = DATA_RemoveChallenge
DATA prototype FindChallenge = DATA_FindChallenge
DATA prototype GetChallenge = DATA_GetChallenge
DATA prototype UpdateChallenge = DATA_UpdateChallenge
DATA prototype AddChallengeWindow = DATA_AddChallengeWindow
DATA prototype GetChallengeList = DATA_GetChallengeList
DATA prototype SetChallengeMenu = DATA_SetChallengeMenu
DATA prototype GetChallengeMenu = DATA_GetChallengeMenu
DATA prototype SetChallengeSequence = DATA_SetChallengeSequence
DATA prototype GetChallengeSequence = DATA_GetChallengeSequence
DATA prototype AddGame = DATA_AddGame
DATA prototype RemoveGame = DATA_RemoveGame
DATA prototype FindGame = DATA_FindGame
DATA prototype AddGameMove = DATA_AddGameMove
DATA prototype SetCurrentGame = DATA_SetCurrentGame
DATA prototype GetCurrentGame = DATA_GetCurrentGame
DATA prototype SetTurn = DATA_SetTurnGame
DATA prototype GetGame = DATA_GetGame
DATA prototype AddOldGame = DATA_AddOldGame
DATA prototype RemoveOldGame = DATA_RemoveOldGame
DATA prototype SetCurrentOldGame = DATA_SetCurrentOldGame
DATA prototype GetCurrentOldGame = DATA_GetCurrentOldGame
DATA prototype PushOldGame = DATA_PushGameToOldGame
DATA prototype GetOldGame = DATA_GetOldGame
DATA prototype AddSearchGameInfo = DATA_AddSearchGameInfo
DATA prototype RemoveSearchGameInfo = DATA_RemoveSearchGameInfo
DATA prototype FindSearchGameInfo = DATA_FindSearchGameInfo
DATA prototype GetSearchGameInfo = DATA_GetSearchGameInfo
DATA prototype AddSearchUserInfo = DATA_AddSearchUserInfo
DATA prototype RemoveSearchUserInfo = DATA_RemoveSearchUserInfo
DATA prototype SortSearchUserByNick = DATA_SortSearchUserByNick
DATA prototype SortSearchUserByName = DATA_SortSearchUserByName
DATA prototype SetPassword = DATA_SetPassword
DATA prototype GetPassword = DATA_GetPassword
DATA prototype SetUsername = DATA_SetMyUsername
DATA prototype GetUsername = DATA_GetMyUsername
DATA prototype SetAwayCounter = DATA_SetAwayCounter
DATA prototype GetAwayCounter = DATA_GetAwayCounter
DATA prototype SetAwayInterval = DATA_SetAwayInterval
DATA prototype GetAwayInterval = DATA_GetAwayInterval
DATA prototype AddWindow = DATA_AddWindow
DATA prototype RemoveWindow = DATA_RemoveWindow
DATA prototype FindWindow = DATA_FindWindow
DATA prototype GetWindow = DATA_GetWindow
DATA prototype SetWindowFocus = DATA_SetWindowFocus
DATA prototype GetWindowFocus = DATA_GetWindowFocus
DATA prototype GetWindowListLength = DATA_GetWindowListLength
DATA prototype SetLoadObj = DATA_SetLoadObj
DATA prototype GetLoadObj = DATA_GetLoadObj
DATA prototype SetGamecenter = DATA_SetGamecenter
DATA prototype GetGamecenter = DATA_GetGamecenter
DATA prototype AddPostpone = DATA_AddPostpone
DATA prototype RemovePostpone = DATA_RemovePostpone
DATA prototype FindPostpone = DATA_FindPostpone
DATA prototype GetPostpone = DATA_GetPostpone
DATA prototype GetPostponeList = DATA_GetPostponeList
DATA prototype SetPostponeStatus = DATA_SetPostponeStatus
DATA prototype AddAnnounce = DATA_AddAnnounce
DATA prototype RemoveAnnounce = DATA_RemoveAnnounce
DATA prototype FindAnnounce = DATA_FindAnnounce
DATA prototype GetAnnounce = DATA_GetAnnounce
DATA prototype GetAnnounceList = DATA_GetAnnounceList
DATA prototype AddCurrentGames = DATA_AddCurrentGames
DATA prototype RemoveCurrentGames = DATA_RemoveCurrentGames
DATA prototype FindCurrentGames = DATA_FindCurrentGames
DATA prototype GetCurrentGames = DATA_GetCurrentGames
DATA prototype GetCurrentGamesList = DATA_GetCurrentGamesList
DATA prototype AddMatchOffer = DATA_AddMatchOffer
DATA prototype RemoveMatchOffer = DATA_RemoveMatchOffer
DATA prototype FindMatchOffer = DATA_FindMatchOffer
DATA prototype GetMatchOffer = DATA_GetMatchOffer
DATA prototype GetMatchOfferList = DATA_GetMatchOfferList
DATA prototype SetAdmincenter = DATA_SetAdmincenter
DATA prototype GetAdmincenter = DATA_GetAdmincenter
DATA prototype AddPunish = DATA_AddPunish
DATA prototype RemovePunish = DATA_RemovePunish
DATA prototype FindPunish = DATA_FindPunish
DATA prototype GetPunish = DATA_GetPunish
DATA prototype GetPunishList = DATA_GetPunishList
DATA prototype AddLevel = DATA_AddLevel
DATA prototype RemoveLevel = DATA_RemoveLevel
DATA prototype FindLevel = DATA_FindLevel
DATA prototype GetLevel = DATA_GetLevel
DATA prototype GetLevelList = DATA_GetLevelList
DATA prototype AddAdminLevel = DATA_AddAdminLevel
DATA prototype RemoveAdminLevel = DATA_RemoveAdminLevel
DATA prototype FindAdminLevel = DATA_FindAdminLevel
DATA prototype GetAdminLevel = DATA_GetAdminLevel
DATA prototype GetAdminLevelList = DATA_GetAdminLevelList
DATA prototype AddAdjourn = DATA_AddAdjourn
DATA prototype RemoveAdjourn = DATA_RemoveAdjourn
DATA prototype FindAdjourn = DATA_FindAdjourn
DATA prototype GetAdjourn = DATA_GetAdjourn
DATA prototype GetAdjournList = DATA_GetAdjournList
DATA prototype AddWords = DATA_AddWords
DATA prototype RemoveWords = DATA_RemoveWords
DATA prototype FindWords = DATA_FindWords
DATA prototype GetWords = DATA_GetWords
DATA prototype GetWordsList = DATA_GetWordsList
Detailed Description
Class definition for main data structure.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Read the config file (scripts/data/conf.xml) and load all data structure
Function Documentation
function DATA (ConfFile, LangFile)
References DATA_SetConsts(), LoadObj(), UTILS_GetTag(), UTILS_IdentifyBrowser(), and UTILS_OpenXMLFile().
Referenced by START_StartPage().
function DATA_AddAdjourn (WName, WRating, BName, BRating, Category, GameTime, Inc, Rated, AdjournId)
References FindAdjourn.
function DATA_AddAdminLevel (Name, Level)
References FindAdminLevel.
function DATA_AddAnnounce (Player, Rating, Time, Inc, Category, Rated, Private, AnnounceId)
References FindAnnounce.
function DATA_AddChallenge (ChallengeId, Challenger, Challenged, Category, Rated, MatchId)
Add a challenge in 'ChallengeList'.
ChallengeID is used temporary to identify challenge in challenge list when match id was not defined
Parameters:
ChallengeId Identification number of challenge in maindata
Challenged Who receive a challenge
Challenger Who make a challenge
Category Game category
Rated Flag to set rated game
MatchId Identification number of challenge in chess server
Author:
Ulysses Bonfim and Rubens Suguimoto
Returns:
Boolean
References FindChallenge.
function DATA_AddChallengeWindow (Id, WindowObj)
Set a Challenge window pointer in challenge item.
Parameters:
Id Challenge identification number
WindowObj Window Object with challenge content
Author:
Ulysses Bonfim and Rubens Suguimoto
Returns:
none
See also:
DATA_FindChallengeById
References GetChallenge, and WindowObj().
function DATA_AddChat (Username, ChatObj)
Add a chat in interface structure, with the other user name and his status.
Parameters:
Username User's name
ChatObj Chat window object
Author:
Ulysses Bonfim and Rubens Suguimoto
Returns:
Boolean
See also:
DATA_FindChat
References ChatObj().
function DATA_AddContactUser (Username, Status, Subs, Group)
References DATA_GetGroup(), DATA_GetRatingList(), DATA_GetStatus(), DATA_GetSubs(), DATA_GetType(), DATA_GetUsername(), DATA_RatingObject(), DATA_SetGroup(), DATA_SetStatus(), DATA_SetSubs(), and DATA_SetType().
function DATA_AddCurrentGames (WPlayer, WRating, BPlayer, BRating, Category, Time, Rated, Moves, CurrentGamesId)
Add a current game.
Parameters:
WPlayer White player object
WRating White player rating
BPlayer Black player object
BRating Black player rating
Category Game category
Time Game time
Rated Game rated flag
Moves Number of moves done
CurrentGamesId Current game identification number
Author:
Rubens Suguimoto
Returns:
True if game was added or null(if current game already exist)
References FindCurrentGames.
function DATA_AddGame (Id, Player1, Player2, Color, GameDiv)
Add a game.
Parameters:
Id Game identification number (integer)
Player1 First player's name
Player2 Second player's name
Color Your color on game
GameDiv Board object
Returns:
New Game structure
Author:
Rubens Suguimoto
See also:
DATA_SetCurrentGame
References AddGameMove, MainData, SetCurrentGame, and SetTurn.
function DATA_AddGameMove (BoardArray, Move, ShortMove, PWTime, PBTime, Turn)
Add a move in game.
Parameters:
BoardArray Board Array
Move Game move done
ShortMove Move done in short format
PWTime White player's time
PBTime Balck player's time
Turn Who did the move
Returns:
none
Author:
Rubens Suguimoto
function DATA_AddHttpPost (PostObj)
function DATA_AddLevel (Name, Level)
References FindLevel.
function DATA_AddMatchOffer (Player, Time, Inc, Category, Rated, Private, MatchOfferId)
Add a offered match.
Parameters:
Player Player object
Time Game time
Inc Game time increment
Category Game category
Rated Rated game flag
Private Private game flag
MatchOfferId Offered match identification number
Author:
Rubens Suguimoto
Returns:
True if game was added or null(if current game already exist)
References FindMatchOffer.
function DATA_AddOldGame (PWName, PBName, Color, GameDiv)
Add a oldgame.
Parameters:
PWName White player's name
PBName Black player's name
Color Your color
GameDiv Board object
Author:
Rubens Suguimoto
Returns:
none
See also:
DATA_SetCurrentOldGame
References AddGameMove, MainData, and SetTurn.
function DATA_AddOnlineUser (Username, Status, Type)
References DATA_GetRatingList(), DATA_GetStatus(), DATA_GetType(), DATA_GetUsername(), DATA_RatingObject(), DATA_SetStatus(), and DATA_SetType().
function DATA_AddPostpone (Player, Time, Inc, Category, Rating, Date, Status, PostponeId)
Add a postponed game.
Parameters:
Player Oponent player's object
Time Game time
Inc Game time increment
Category Game category
Rating Rating current category value
Date Date of adjourned match
Status Oponent player status
PostponeId Postponed game identification number
Author:
Rubens Suguimoto
Returns:
Boolean
References FindPostpone.
function DATA_AddProfile (Jid, Username, ProfileWindow)
function DATA_AddPunish (Name, Punish, Incident, Date, Period, Reason)
References FindPunish, and PunishObj().
function DATA_AddRating (Category, Value, RecordValue, RecordTime, Win, Draw, Losses)
Referenced by DATA_RatingObject().
function DATA_AddRoom (RoomName, MsgTo, Role, Affiliation, RoomObj)
Create new room in room list.
Parameters:
RoomName New room's name
MsgTo Where the messages will be send
Role Your role in room
Affiliation Your affiliation in room
RoomObj Room object, used to control the interface
Author:
Pedro Rocha
Returns:
The new room object
See also:
DATA_FindRoom
References DATA_AddUserInRoom(), DATA_FindUserInRoom(), DATA_GetRoomCurrentRating(), DATA_GetRoomOrderBy(), DATA_GetUserInRoom(), DATA_GetUserRatingInRoom(), DATA_RemoveUserInRoom(), DATA_SetRoomCurrentRating(), DATA_SetRoomOrderBy(), DATA_SetUserInfoInRoom(), DATA_SortUserByNickInRoom(), DATA_SortUserByRatingInRoom(), and RoomObj().
function DATA_AddSearchGameInfo (Id, Elements, User)
Add search game window parameters.
Parameters:
Id Game ID
Elements HTML DOM elements list
User User's name
Author:
Danilo Yorinori
Returns:
boolean
function DATA_AddSearchUserInfo (Elements)
Add search user window parameters.
Parameters:
Elements HTML DOM elements
Author:
Danilo Yorinori
Returns:
boolean
function DATA_AddShowChat (ChatObj)
References ChatObj().
function DATA_AddUser (Username, Status)
Add user to user list.
Search the user in DATA.UserList, if the user wasn't found, add the user in the list with a blank photo and a empty rating.
Parameters:
Username The user's name to add in structure
Status The user's status
Returns:
false - User already on list, true otherwise
Author:
Ulysses Bonfim and Rubens Suguimoto
References DATA_GetDesc(), DATA_GetFullname(), DATA_GetImg64(), DATA_GetImgType(), DATA_GetLastGame(), DATA_GetOnlineTime(), DATA_GetPhoto(), DATA_GetProfileObj(), DATA_GetRatingList(), DATA_GetStatus(), DATA_GetTotalTime(), DATA_GetType(), DATA_GetTypeTitle(), DATA_GetUpdateProfile(), DATA_GetUpdateRating(), DATA_GetUsername(), DATA_GetWarning(), DATA_RatingObject(), DATA_SetDesc(), DATA_SetFullname(), DATA_SetImg64(), DATA_SetImgType(), DATA_SetLastGame(), DATA_SetOnlineTime(), DATA_SetPhoto(), DATA_SetProfileObj(), DATA_SetStatus(), DATA_SetTotalTime(), DATA_SetType(), DATA_SetTypeTitle(), DATA_SetUpdateProfile(), DATA_SetUpdateRating(), and DATA_SetWarning().
function DATA_AddUserInRoom (Username, Status, Type, Role, Affiliation)
Add user in user list of a room.
Parameters:
Username User's name
Status New user's status
Type New user's type
Role New user's role
Affiliation New user's affiliation
Author:
Pedro Rocha and Rubens Suguimoto
Returns:
true
See also:
DATA_FindRoom DATA_FindUser
References DATA_GetAfilliation(), DATA_GetPhoto(), DATA_GetRatingList(), DATA_GetRole(), DATA_GetStatus(), DATA_GetType(), DATA_GetUsername(), DATA_RatingObject(), DATA_SetAfilliation(), DATA_SetPhoto(), DATA_SetRole(), DATA_SetStatus(), DATA_SetType(), and MainData.
Referenced by DATA_AddRoom().
function DATA_AddWindow (WindowObj)
Add a WindowObject in WindowList.
Parameters:
WindowObj Window object
Returns:
none
Author:
Rubens Suguimoto
References WindowObj().
function DATA_AddWords (WordString)
References FindWords.
function DATA_FindAdjourn (AdjournId)
function DATA_FindAdminLevel (AdminLevelId)
function DATA_FindAnnounce (AnnounceId)
function DATA_FindChallenge (ChallengeId, MatchId)
Find a challenge.
You can find a challenge by ChallengeId or MatchId; This is used because interface create a instance of challenge before get match id from server. If server send a error, this function is able to find challenge in challenge list;
Parameters:
MatchId Identification number of challenge in chess server
ChallengeId Identification number of challenge in maindata
Returns:
Challenge position (integer) or null if not founded
Author:
Ulysses Bonfim
function DATA_FindChat (Username)
Find a chat with ohter user.
Parameters:
Username User's name
Author:
Ulysses Bonfim and Rubens Suguimoto
Returns:
Position of the chat in chat list (integer)
function DATA_FindContactUser (Username)
function DATA_FindCurrentGames (CurrentGamesId)
function DATA_FindGame (Id)
Find game by game id.
Parameters:
Id Game identification
Returns:
Game index or null (if not founded)
Author:
Rubens Suguimoto
See also:
DATA_FindGame DATA_SetCurrentGame
function DATA_FindHttpPost (PostObj)
function DATA_FindLevel (LevelId)
function DATA_FindMatchOffer (MatchOfferId)
function DATA_FindOnlineUser (Username)
function DATA_FindPostpone (PostponeId)
function DATA_FindProfile (Jid)
function DATA_FindPunish (PunishId)
function DATA_FindRating (Category)
Referenced by DATA_RatingObject().
function DATA_FindRoom (RoomName)
Find room in room list.
Parameters:
RoomName Room name to find
Author:
Pedro Eugenio
Returns:
Room structure founded or null
function DATA_FindSearchGameInfo (Id)
Find search game window.
Parameters:
Id Old game chess server identification number
Author:
Danilo Yorinori
Returns:
Game's position
function DATA_FindUser (Username)
Find user in user list.
Parameters:
Username User's name to search
Author:
Pedro Rocha
Returns:
null if user is not on your list, the structure User otherwise
function DATA_FindUserInRoom (Username)
Find user in user list of a room.
Parameters:
Username User to find
Author:
Pedro Rocha and Rubens Suguimoto
Returns:
User's position on room user list, or null, if not found
See also:
DATA_FindRoom
Referenced by DATA_AddRoom().
function DATA_FindWindow (WindowObj)
Find Window Object positon in WindowList.
Parameters:
WindowObj Window Object
Returns:
Window object position or null (if not founded)
Author:
Rubens Suguimoto
References WindowObj().
function DATA_FindWords (WordId)
function DATA_GetAdjourn (AdjournId)
References FindAdjourn.
function DATA_GetAdjournList ()
function DATA_GetAdmincenter ()
function DATA_GetAdminLevel (AdminLevelId)
References FindAdminLevel.
function DATA_GetAdminLevelList ()
function DATA_GetAfilliation ()
Referenced by DATA_AddUserInRoom().
function DATA_GetAnnounce (AnnounceId)
References FindAnnounce.
function DATA_GetAnnounceList ()
function DATA_GetAwayCounter ()
function DATA_GetAwayInterval ()
function DATA_GetBrowser ()
function DATA_GetChallenge (ChallengeId, MatchId)
References FindChallenge.
function DATA_GetChallengeList ()
function DATA_GetChallengeMenu ()
function DATA_GetChallengeSequence ()
function DATA_GetChat (Username)
References FindChat.
function DATA_GetChatListLength ()
function DATA_GetConferenceComponent ()
function DATA_GetConnectionStatus ()
function DATA_GetConst ()
function DATA_GetContactCurrentRating ()
function DATA_GetContactObj ()
function DATA_GetContactOrderBy ()
function DATA_GetContactUser (Username)
References MainData.
function DATA_GetContactUserList ()
function DATA_GetCookieValidity ()
function DATA_GetCurrentGame ()
Get current game.
Returns:
Current game object
Author:
Rubens Suguimoto
function DATA_GetCurrentGames (CurrentGamesId)
References FindCurrentGames.
function DATA_GetCurrentGamesList ()
function DATA_GetCurrentOldGame ()
Get current oldgame.
Author:
Rubens Suguimoto
Returns:
Oldgame item
function DATA_GetCurrentRoom ()
function DATA_GetDefaultPHP ()
function DATA_GetDefaultText ()
function DATA_GetDesc ()
Referenced by DATA_AddUser().
function DATA_GetEmoticonNum ()
function DATA_GetFullname ()
Referenced by DATA_AddUser().
function DATA_GetGame (Id)
Get game item.
Parameters:
Id Game identification number
Author:
Rubens Suguimoto
Returns:
Game item or null (if was not founded)
function DATA_GetGamecenter ()
function DATA_GetGroup ()
Referenced by DATA_AddContactUser().
function DATA_GetHost ()
function DATA_GetHostPost ()
function DATA_GetHttpRequestLength ()
function DATA_GetImg64 ()
Referenced by DATA_AddUser().
function DATA_GetImgType ()
Referenced by DATA_AddUser().
function DATA_GetLang ()
function DATA_GetLastGame ()
Referenced by DATA_AddUser().
function DATA_GetLevel (LevelId)
References FindLevel.
function DATA_GetLevelList ()
function DATA_GetLoadObj ()
References LoadObj().
function DATA_GetMatchOffer (MatchOfferId)
References FindMatchOffer.
function DATA_GetMatchOfferList ()
function DATA_GetMaxChatChar ()
function DATA_GetMaxChats ()
function DATA_GetMaxRoomChar ()
function DATA_GetMaxRooms ()
function DATA_GetMyUsername ()
function DATA_GetOldGame (Id)
Get old game item.
Parameters:
Id Game identification number
Author:
Rubens Suguimoto
Returns:
The game structure
function DATA_GetOnlineCurrentRating ()
function DATA_GetOnlineObj ()
function DATA_GetOnlineOrderBy ()
function DATA_GetOnlineTime ()
Referenced by DATA_AddUser().
function DATA_GetOnlineUser (Username)
References MainData.
function DATA_GetOnlineUserList ()
function DATA_GetPassword ()
function DATA_GetPhoto ()
Referenced by DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_GetPostpone (PostponeId)
References FindPostpone.
function DATA_GetPostponeList ()
function DATA_GetProfile (Jid)
function DATA_GetProfileObj ()
Referenced by DATA_AddUser().
function DATA_GetPunish (PunishId)
References FindPunish.
function DATA_GetPunishList ()
function DATA_GetRating (Category)
Referenced by DATA_RatingObject().
function DATA_GetRatingDraw (Category)
Referenced by DATA_RatingObject().
function DATA_GetRatingList ()
Referenced by DATA_AddContactUser(), DATA_AddOnlineUser(), DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_GetRatingLosses (Category)
Referenced by DATA_RatingObject().
function DATA_GetRatingValue (Category)
Referenced by DATA_RatingObject().
function DATA_GetRatingWin (Category)
Referenced by DATA_RatingObject().
function DATA_GetRecordTime (Category)
Referenced by DATA_RatingObject().
function DATA_GetRecordValue (Category)
Referenced by DATA_RatingObject().
function DATA_GetResource ()
function DATA_GetRID ()
function DATA_GetRole ()
Referenced by DATA_AddUserInRoom().
function DATA_GetRoom (RoomName)
Get room from room list.
Parameters:
RoomName Room's name
Author:
Danilo Yorinori
Returns:
Boolean
See also:
DATA_FindRooom
References FindRoom.
function DATA_GetRoomCurrentRating ()
Referenced by DATA_AddRoom().
function DATA_GetRoomDefault ()
function DATA_GetRoomList ()
function DATA_GetRoomOrderBy ()
Referenced by DATA_AddRoom().
function DATA_GetSearchComponent ()
function DATA_GetSearchGameInfo (Id)
function DATA_GetServer ()
function DATA_GetSID ()
function DATA_GetStatus ()
Referenced by DATA_AddContactUser(), DATA_AddOnlineUser(), DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_GetSubs ()
Referenced by DATA_AddContactUser().
function DATA_GetText ()
function DATA_GetTotalTime ()
Referenced by DATA_AddUser().
function DATA_GetType ()
Referenced by DATA_AddContactUser(), DATA_AddOnlineUser(), DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_GetTypeTitle ()
Referenced by DATA_AddUser().
function DATA_GetUpdateGetMaxProfiles ()
function DATA_GetUpdateProfile ()
Referenced by DATA_AddUser().
function DATA_GetUpdateProfileTimer ()
function DATA_GetUpdateRating ()
Referenced by DATA_AddUser().
function DATA_GetUpdateRatingInterval ()
function DATA_GetUpdateTimer ()
function DATA_GetUser (Username)
References FindUser.
function DATA_GetUserInRoom (Username)
Get user object in user list of room.
Parameters:
Username User's name to find
Author:
Pedro Rocha and Rubens Suguimoto
Returns:
User object or null, if not found
References FindUser.
Referenced by DATA_AddRoom().
function DATA_GetUserList ()
function DATA_GetUsername ()
Referenced by DATA_AddContactUser(), DATA_AddOnlineUser(), DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_GetUserRatingInRoom (Username, Category)
Get user's rating.
Return Category's Rating from Username in Room (Based on fact that's all online users are connected to 'geral' room
TODO -> REMOVE THIS FUNCTION WHEN USERSLIST WAS DONE*
Parameters:
Username User name
Category Category which rating will be returned
Author:
Danilo Yorinori
Returns:
Rating's value
See also:
DATA_FindRoom DATA_FinUserInRoom
References GetUser, and MainData.
Referenced by DATA_AddRoom().
function DATA_GetVersion ()
function DATA_GetWarning ()
Referenced by DATA_AddUser().
function DATA_GetWindow (Index)
function DATA_GetWindowFocus ()
function DATA_GetWindowListLength ()
function DATA_GetWords (WordId)
References FindWords.
function DATA_GetWordsList ()
function DATA_GetXmlns ()
function DATA_PushGameToOldGame (GameObj)
Set a normal game as the current old game.
Parameters:
GameObj The normal game object
Author:
Rubens Suguimoto
Returns:
Oldgame position in old game list
See also:
DATA_SetCurrentOldGame
References MainData.
function DATA_RatingObject ()
References DATA_AddRating(), DATA_FindRating(), DATA_GetRating(), DATA_GetRatingDraw(), DATA_GetRatingLosses(), DATA_GetRatingValue(), DATA_GetRatingWin(), DATA_GetRecordTime(), DATA_GetRecordValue(), DATA_RemoveRating(), DATA_SetRatingDraw(), DATA_SetRatingLosses(), DATA_SetRatingValue(), DATA_SetRatingWin(), DATA_SetRecordTime(), and DATA_SetRecordValue().
Referenced by DATA_AddContactUser(), DATA_AddOnlineUser(), DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_RemoveAdjourn (AdjournId)
References FindAdjourn.
function DATA_RemoveAdminLevel (AdminLevelId)
References FindAdminLevel.
function DATA_RemoveAnnounce (AnnounceId)
References FindAnnounce.
function DATA_RemoveChallenge (ChallengeId, MatchId)
Remove a challenge.
Parameters:
MatchId Identification number of challenge in chess server
ChallengeId Identification number of challenge in maindata
Author:
Ulysses Bonfim and Rubens Suguimoto
Returns:
Empty string
See also:
DATA_FindChallenge
References FindChallenge.
function DATA_RemoveChat (Username)
Remove a chat with the user given from the structure.
Parameters:
Username User's name
Author:
Ulysses Bonfim and Rubens Suguimoto
Returns:
True if removed or null if not founded
See also:
DATA_FindChat
References FindChat.
function DATA_RemoveContactUser (Username)
References MainData.
function DATA_RemoveCurrentGames (CurrentGamesId)
Remove a current game.
Parameters:
CurrentGamesId Current game identification number
Author:
Rubens Suguimoto
Returns:
Empty string
See also:
DATA_FindCurrentGames
References FindCurrentGames.
function DATA_RemoveGame (Id)
Remove a game.
Parameters:
Id Game identification number
Returns:
Removed game item
Author:
Rubens Suguimoto
See also:
DATA_FindGame DATA_SetCurrentGame
References MainData.
function DATA_RemoveHttpPost (PostObj)
References FindHttpPost.
function DATA_RemoveLevel (LevelId)
References FindLevel.
function DATA_RemoveMatchOffer (MatchOfferId)
Remove a offered match.
Parameters:
MatchOfferId Offered match identification number
Author:
Rubens Suguimoto
Returns:
Empty string
See also:
DATA_FindMatchOffer
References FindMatchOffer.
function DATA_RemoveOldGame (Id)
Remove a oldgame.
Parameters:
Id Oldgame identification
Author:
Rubens Suguimoto
Returns:
Oldgame removed item
See also:
DATA_SetCurrentOldGame
References MainData.
function DATA_RemoveOnlineUser (Username)
References MainData.
function DATA_RemovePostpone (PostponeId)
Remove a postpone challenge in 'PostponeList'.
Parameters:
PostponeId Postponed game identification number
Author:
Rubens Suguimoto
Returns:
Postponed game item or null (if not found)
See also:
DATA_FindPostpone
References FindPostpone.
function DATA_RemoveProfile (Jid)
function DATA_RemovePunish (PunishId)
References FindPunish.
function DATA_RemoveRating (Category)
Referenced by DATA_RatingObject().
function DATA_RemoveRoom (RoomName)
Delete a room in room list.
Parameters:
RoomName Room name to remove
Author:
Pedro Rucha
Returns:
True if removed, or False if not found
See also:
DATA_FindRoom
References FindRoom.
function DATA_RemoveSearchGameInfo (Id)
Remove search game window.
Parameters:
Id Old game chess server identification number
Author:
Danilo Yorinori
Returns:
boolean
References FindSearchGameInfo.
function DATA_RemoveSearchUserInfo ()
Remove search user window.
Author:
Danilo Yorinori
Returns:
boolean
function DATA_RemoveShowChat (Username)
References FindChat.
function DATA_RemoveUser (Username)
Remove user from user list.
Search and remove the user of DATA.UserList
Parameters:
Username User's name to remove of structure
Author:
Pedro Rocha and Rubens Suguimoto
Returns:
null if user is not on your list, true otherwise
See also:
DATA_FindUser
References FindUser.
function DATA_RemoveUserInRoom (Username)
Delete user from user list of a room.
Parameters:
Username User to remove
Author:
Danilo Yorinori
Returns:
Boolean
See also:
DATA_FindRoom DATA_FindUserInRoom
References FindUser.
Referenced by DATA_AddRoom().
function DATA_RemoveWindow (WindowObj)
Remove a Window Object from WindowList.
Parameters:
WindowObj Window Object
Returns:
none
Author:
Rubens Suguimoto
References FindWindow, GetWindowListLength, SetWindowFocus, and WindowObj().
function DATA_RemoveWords (WordId)
References FindWords.
function DATA_SetAdmincenter (Obj)
function DATA_SetAfilliation (NewAfilliation)
Referenced by DATA_AddUserInRoom().
function DATA_SetAwayCounter (Counter)
function DATA_SetAwayInterval (Interval)
function DATA_SetChallengeMenu (MenuObj)
function DATA_SetChallengeSequence (NewValue)
function DATA_SetConnectionStatus (Value)
function DATA_SetContactCurrentRating (NewCategory)
function DATA_SetContactObj (Obj)
function DATA_SetContactOrderBy (NewValue)
function DATA_SetCurrentGame (Game)
Set current game.
Parameters:
Game Game object to be a current game
Author:
Rubens Suguimoto
Returns:
none
function DATA_SetCurrentOldGame (Game)
Set current oldgame.
Parameters:
Game Oldgame item
Author:
Rubens Suguimoto
Returns:
none
function DATA_SetCurrentRoom (RoomObj)
References RoomObj().
function DATA_SetDesc (NewDesc)
Referenced by DATA_AddUser().
function DATA_SetFullname (NewName)
Referenced by DATA_AddUser().
function DATA_SetGamecenter (Obj)
function DATA_SetGroup (NewGroup)
Referenced by DATA_AddContactUser().
function DATA_SetImg64 (Image)
Referenced by DATA_AddUser().
function DATA_SetImgType (ImageType)
Referenced by DATA_AddUser().
function DATA_SetLang (Lang)
function DATA_SetLastGame (LastGame)
Referenced by DATA_AddUser().
function DATA_SetLoadObj (Obj)
References LoadObj().
function DATA_SetMaxChatChar (MaxChar)
function DATA_SetMaxChats (NewMax)
function DATA_SetMyProfile (Username, FullName, Desc, ImgType, Img64)
function DATA_SetMyUsername (Username)
function DATA_SetOnlineCurrentRating (NewCategory)
function DATA_SetOnlineObj (Obj)
function DATA_SetOnlineOrderBy (NewValue)
function DATA_SetOnlineTime (Time)
Referenced by DATA_AddUser().
function DATA_SetPassword (NewPassword)
function DATA_SetPhoto (NewPhoto)
Referenced by DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_SetPostponeStatus (PostponeId, Status)
References GetPostpone.
function DATA_SetProfileObj (ProfileObj)
Referenced by DATA_AddUser().
function DATA_SetRatingDraw (Category, Value)
Referenced by DATA_RatingObject().
function DATA_SetRatingLosses (Category, Value)
Referenced by DATA_RatingObject().
function DATA_SetRatingValue (Category, Value)
Referenced by DATA_RatingObject().
function DATA_SetRatingWin (Category, Value)
Referenced by DATA_RatingObject().
function DATA_SetRecordTime (Category, Time)
Referenced by DATA_RatingObject().
function DATA_SetRecordValue (Category, Value)
Referenced by DATA_RatingObject().
function DATA_SetRID (Value)
function DATA_SetRole (NewRole)
Referenced by DATA_AddUserInRoom().
function DATA_SetRoomCurrentRating (RatingType)
Referenced by DATA_AddRoom().
function DATA_SetRoomInformation (RoomName, From, Affiliation, Role)
Set from, affiliation and role in 'RoomName' structure.
Only for interface user
Parameters:
RoomName Room's name
From Where the messages will be send
Affiliation New room's affiliation
Role New room's role
Author:
Pedro Eugenio
Returns:
null, if the room doesn't exist, true otherwise
See also:
DATA_FindRoom
References FindRoom, and MainData.
function DATA_SetRoomOrderBy (Value)
Referenced by DATA_AddRoom().
function DATA_SetSID (Value)
function DATA_SetStatus (NewStatus)
Referenced by DATA_AddContactUser(), DATA_AddOnlineUser(), DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_SetSubs (NewSubs)
Referenced by DATA_AddContactUser().
function DATA_SetText (FileXML)
function DATA_SetTotalTime (Time)
Referenced by DATA_AddUser().
function DATA_SetTurnGame (TurnColor)
Set your turn flag.
Parameters:
TurnColor Player's color
Author:
Rubens Suguimoto
Returns:
none
function DATA_SetType (NewType)
Referenced by DATA_AddContactUser(), DATA_AddOnlineUser(), DATA_AddUser(), and DATA_AddUserInRoom().
function DATA_SetTypeTitle (Title)
Referenced by DATA_AddUser().
function DATA_SetUpdateProfile (Bool)
Referenced by DATA_AddUser().
function DATA_SetUpdateProfileTimer (Interval)
function DATA_SetUpdateRating (Bool)
Referenced by DATA_AddUser().
function DATA_SetUpdateTimer (Interval)
function DATA_SetUserInfoInRoom (Username, Status, Role, Affiliation)
Set user attibutes in 'RoomName'.
Parameters:
Username Base user to set
Status New user's status
Role New user's Role
Affiliation New user's Affiliation
Author:
Danilo Yorinori
Returns:
Boolean
See also:
DATA_FindRoom DATA_FindUserInRoom
References GetUser.
Referenced by DATA_AddRoom().
function DATA_SetWarning (Warning)
Referenced by DATA_AddUser().
function DATA_SetWindowFocus (WindowObj)
Set Window Object in focus.
Parameters:
WindowObj Window object
Returns:
Window Object
Author:
Rubens Suguimoto
References WindowObj().
function DATA_SortContactUserByNick ()
Sort Userlist into ascending or descending order.
Author:
Danilo Yorinori
Returns:
boolean
See also:
UTILS_SortByUsernameAsc UTILS_SortByUsernameDsc
function DATA_SortContactUserByRating ()
Sort Userlist into descending order by Rating selected in interface.
Author:
Danilo Yorinori
Returns:
boolean
See also:
UTILS_SortByRatingDsc
function DATA_SortOnlineUserByNick ()
Sort Userlist into ascending or descending order.
Author:
Danilo Yorinori
Returns:
boolean
See also:
UTILS_SortByUsernameAsc UTILS_SortByUsernameDsc
function DATA_SortOnlineUserByRating ()
Sort Userlist into descending order by Rating selected in interface.
Author:
Danilo Yorinori
Returns:
boolean
See also:
UTILS_SortByRatingDsc
function DATA_SortSearchUserByName ()
Sort Userlist into descending order by Rating selected in interface.
Author:
Danilo Yorinori
Returns:
boolean
See also:
UTILS_SortByRatingDsc
function DATA_SortSearchUserByNick ()
Sort Userlist into ascending or descending order.
Author:
Danilo Yorinori
Returns:
boolean
See also:
UTILS_SortByUsernameAsc UTILS_SortByUsernameDsc
function DATA_SortUserByNickInRoom ()
Sort Userlist from Room into ascending or descending order.
Author:
Danilo Yorinori
Returns:
Boolean
See also:
DATA_FindRoom UTILS_SortByUsernameAsc UTILS_SortByUsernameDsc
Referenced by DATA_AddRoom().
function DATA_SortUserByRatingInRoom ()
Sort Userlist from Room into descending order by Rating.
Author:
Danilo Yorinori
Returns:
Boolean
See also:
DATA_FindRoom UTILS_SortByUsernameDsc
Referenced by DATA_AddRoom().
function DATA_UpdateChallenge (ChallengeId, Challenger, Challenged, Category, Rated, MatchId)
References GetChallenge.
Variable Documentation
DATA prototype AddAdjourn = DATA_AddAdjourn
DATA prototype AddAdminLevel = DATA_AddAdminLevel
DATA prototype AddAnnounce = DATA_AddAnnounce
DATA prototype AddChallenge = DATA_AddChallenge
DATA prototype AddChallengeWindow = DATA_AddChallengeWindow
DATA prototype AddChat = DATA_AddChat
DATA prototype AddContactUser = DATA_AddContactUser
DATA prototype AddCurrentGames = DATA_AddCurrentGames
DATA prototype AddGame = DATA_AddGame
DATA prototype AddGameMove = DATA_AddGameMove
Referenced by DATA_AddGame(), and DATA_AddOldGame().
DATA prototype AddHttpPost = DATA_AddHttpPost
DATA prototype AddLevel = DATA_AddLevel
DATA prototype AddMatchOffer = DATA_AddMatchOffer
DATA prototype AddOldGame = DATA_AddOldGame
DATA prototype AddOnlineUser = DATA_AddOnlineUser
DATA prototype AddPostpone = DATA_AddPostpone
DATA prototype AddPunish = DATA_AddPunish
DATA prototype AddRoom = DATA_AddRoom
DATA prototype AddSearchGameInfo = DATA_AddSearchGameInfo
DATA prototype AddSearchUserInfo = DATA_AddSearchUserInfo
DATA prototype AddShowChat = DATA_AddShowChat
DATA prototype AddUser = DATA_AddUser
DATA prototype AddWindow = DATA_AddWindow
DATA prototype AddWords = DATA_AddWords
DATA prototype FindAdjourn = DATA_FindAdjourn
Referenced by DATA_AddAdjourn(), DATA_GetAdjourn(), and DATA_RemoveAdjourn().
DATA prototype FindAdminLevel = DATA_FindAdminLevel
Referenced by DATA_AddAdminLevel(), DATA_GetAdminLevel(), and DATA_RemoveAdminLevel().
DATA prototype FindAnnounce = DATA_FindAnnounce
Referenced by DATA_AddAnnounce(), DATA_GetAnnounce(), and DATA_RemoveAnnounce().
DATA prototype FindChallenge = DATA_FindChallenge
Referenced by DATA_AddChallenge(), DATA_GetChallenge(), and DATA_RemoveChallenge().
DATA prototype FindChat = DATA_FindChat
Referenced by DATA_GetChat(), DATA_RemoveChat(), and DATA_RemoveShowChat().
DATA prototype FindContactUser = DATA_FindContactUser
DATA prototype FindCurrentGames = DATA_FindCurrentGames
Referenced by DATA_AddCurrentGames(), DATA_GetCurrentGames(), and DATA_RemoveCurrentGames().
DATA prototype FindGame = DATA_FindGame
DATA prototype FindHttpPost = DATA_FindHttpPost
Referenced by DATA_RemoveHttpPost().
DATA prototype FindLevel = DATA_FindLevel
Referenced by DATA_AddLevel(), DATA_GetLevel(), and DATA_RemoveLevel().
DATA prototype FindMatchOffer = DATA_FindMatchOffer
Referenced by DATA_AddMatchOffer(), DATA_GetMatchOffer(), and DATA_RemoveMatchOffer().
DATA prototype FindOnlineUser = DATA_FindOnlineUser
DATA prototype FindPostpone = DATA_FindPostpone
Referenced by DATA_AddPostpone(), DATA_GetPostpone(), and DATA_RemovePostpone().
DATA prototype FindPunish = DATA_FindPunish
Referenced by DATA_AddPunish(), DATA_GetPunish(), and DATA_RemovePunish().
DATA prototype FindRoom = DATA_FindRoom
Referenced by DATA_GetRoom(), DATA_RemoveRoom(), and DATA_SetRoomInformation().
DATA prototype FindSearchGameInfo = DATA_FindSearchGameInfo
Referenced by DATA_RemoveSearchGameInfo().
DATA prototype FindUser = DATA_FindUser
Referenced by DATA_GetUser(), DATA_GetUserInRoom(), DATA_RemoveUser(), and DATA_RemoveUserInRoom().
DATA prototype FindWindow = DATA_FindWindow
Referenced by DATA_RemoveWindow().
DATA prototype FindWords = DATA_FindWords
Referenced by DATA_AddWords(), DATA_GetWords(), and DATA_RemoveWords().
DATA prototype GetAdjourn = DATA_GetAdjourn
DATA prototype GetAdjournList = DATA_GetAdjournList
DATA prototype GetAdmincenter = DATA_GetAdmincenter
DATA prototype GetAdminLevel = DATA_GetAdminLevel
DATA prototype GetAdminLevelList = DATA_GetAdminLevelList
DATA prototype GetAnnounce = DATA_GetAnnounce
DATA prototype GetAnnounceList = DATA_GetAnnounceList
DATA prototype GetAwayCounter = DATA_GetAwayCounter
DATA prototype GetAwayInterval = DATA_GetAwayInterval
DATA prototype GetBrowser = DATA_GetBrowser
DATA prototype GetChallenge = DATA_GetChallenge
Referenced by DATA_AddChallengeWindow(), and DATA_UpdateChallenge().
DATA prototype GetChallengeList = DATA_GetChallengeList
DATA prototype GetChallengeMenu = DATA_GetChallengeMenu
DATA prototype GetChallengeSequence = DATA_GetChallengeSequence
DATA prototype GetChat = DATA_GetChat
DATA prototype GetChatListLength = DATA_GetChatListLength
DATA prototype GetConferenceComponent = DATA_GetConferenceComponent
DATA prototype GetConnectionStatus = DATA_GetConnectionStatus
DATA prototype GetConst = DATA_GetConst
DATA prototype GetContactCurrentRating = DATA_GetContactCurrentRating
DATA prototype GetContactObj = DATA_GetContactObj
DATA prototype GetContactOrderBy = DATA_GetContactOrderBy
DATA prototype GetContactUser = DATA_GetContactUser
DATA prototype GetContactUserList = DATA_GetContactUserList
DATA prototype GetCookieValidity = DATA_GetCookieValidity
DATA prototype GetCurrentGame = DATA_GetCurrentGame
DATA prototype GetCurrentGames = DATA_GetCurrentGames
DATA prototype GetCurrentGamesList = DATA_GetCurrentGamesList
DATA prototype GetCurrentOldGame = DATA_GetCurrentOldGame
DATA prototype GetCurrentRoom = DATA_GetCurrentRoom
DATA prototype GetDefaultPHP = DATA_GetDefaultPHP
DATA prototype GetDefaultText = DATA_GetDefaultText
DATA prototype GetEmoticonNum = DATA_GetEmoticonNum
DATA prototype GetGame = DATA_GetGame
DATA prototype GetGamecenter = DATA_GetGamecenter
DATA prototype GetHost = DATA_GetHost
DATA prototype GetHostPost = DATA_GetHostPost
DATA prototype GetHttpRequestLength = DATA_GetHttpRequestLength
DATA prototype GetLang = DATA_GetLang
DATA prototype GetLevel = DATA_GetLevel
DATA prototype GetLevelList = DATA_GetLevelList
DATA prototype GetLoadObj = DATA_GetLoadObj
DATA prototype GetMatchOffer = DATA_GetMatchOffer
DATA prototype GetMatchOfferList = DATA_GetMatchOfferList
DATA prototype GetMaxChatChar = DATA_GetMaxChatChar
DATA prototype GetMaxChats = DATA_GetMaxChats
DATA prototype GetMaxRoomChar = DATA_GetMaxRoomChar
DATA prototype GetMaxRooms = DATA_GetMaxRooms
DATA prototype GetOldGame = DATA_GetOldGame
DATA prototype GetOnlineCurrentRating = DATA_GetOnlineCurrentRating
DATA prototype GetOnlineObj = DATA_GetOnlineObj
DATA prototype GetOnlineOrderBy = DATA_GetOnlineOrderBy
DATA prototype GetOnlineUser = DATA_GetOnlineUser
DATA prototype GetOnlineUserList = DATA_GetOnlineUserList
DATA prototype GetPassword = DATA_GetPassword
DATA prototype GetPostpone = DATA_GetPostpone
Referenced by DATA_SetPostponeStatus().
DATA prototype GetPostponeList = DATA_GetPostponeList
DATA prototype GetPunish = DATA_GetPunish
DATA prototype GetPunishList = DATA_GetPunishList
DATA prototype GetResource = DATA_GetResource
DATA prototype GetRID = DATA_GetRID
DATA prototype GetRoom = DATA_GetRoom
DATA prototype GetRoomDefault = DATA_GetRoomDefault
DATA prototype GetRoomList = DATA_GetRoomList
DATA prototype GetSearchComponent = DATA_GetSearchComponent
DATA prototype GetSearchGameInfo = DATA_GetSearchGameInfo
DATA prototype GetServer = DATA_GetServer
DATA prototype GetSID = DATA_GetSID
DATA prototype GetText = DATA_GetText
DATA prototype GetUpdateGetMaxProfiles = DATA_GetUpdateGetMaxProfiles
DATA prototype GetUpdateProfileTimer = DATA_GetUpdateProfileTimer
DATA prototype GetUpdateRatingInterval = DATA_GetUpdateRatingInterval
DATA prototype GetUpdateTimer = DATA_GetUpdateTimer
DATA prototype GetUser = DATA_GetUser
Referenced by DATA_GetUserRatingInRoom(), and DATA_SetUserInfoInRoom().
DATA prototype GetUserList = DATA_GetUserList
DATA prototype GetUsername = DATA_GetMyUsername
DATA prototype GetVersion = DATA_GetVersion
DATA prototype GetWindow = DATA_GetWindow
DATA prototype GetWindowFocus = DATA_GetWindowFocus
DATA prototype GetWindowListLength = DATA_GetWindowListLength
Referenced by DATA_RemoveWindow().
DATA prototype GetWords = DATA_GetWords
DATA prototype GetWordsList = DATA_GetWordsList
DATA prototype GetXmlns = DATA_GetXmlns
DATA prototype PushOldGame = DATA_PushGameToOldGame
DATA prototype RemoveAdjourn = DATA_RemoveAdjourn
DATA prototype RemoveAdminLevel = DATA_RemoveAdminLevel
DATA prototype RemoveAnnounce = DATA_RemoveAnnounce
DATA prototype RemoveChallenge = DATA_RemoveChallenge
DATA prototype RemoveChat = DATA_RemoveChat
DATA prototype RemoveContactUser = DATA_RemoveContactUser
DATA prototype RemoveCurrentGames = DATA_RemoveCurrentGames
DATA prototype RemoveGame = DATA_RemoveGame
DATA prototype RemoveHttpPost = DATA_RemoveHttpPost
DATA prototype RemoveLevel = DATA_RemoveLevel
DATA prototype RemoveMatchOffer = DATA_RemoveMatchOffer
DATA prototype RemoveOldGame = DATA_RemoveOldGame
DATA prototype RemoveOnlineUser = DATA_RemoveOnlineUser
DATA prototype RemovePostpone = DATA_RemovePostpone
DATA prototype RemovePunish = DATA_RemovePunish
DATA prototype RemoveRoom = DATA_RemoveRoom
DATA prototype RemoveSearchGameInfo = DATA_RemoveSearchGameInfo
DATA prototype RemoveSearchUserInfo = DATA_RemoveSearchUserInfo
DATA prototype RemoveShowChat = DATA_RemoveShowChat
DATA prototype RemoveUser = DATA_RemoveUser
DATA prototype RemoveWindow = DATA_RemoveWindow
DATA prototype RemoveWords = DATA_RemoveWords
DATA prototype SetAdmincenter = DATA_SetAdmincenter
DATA prototype SetAwayCounter = DATA_SetAwayCounter
DATA prototype SetAwayInterval = DATA_SetAwayInterval
DATA prototype SetChallengeMenu = DATA_SetChallengeMenu
DATA prototype SetChallengeSequence = DATA_SetChallengeSequence
DATA prototype SetConnectionStatus = DATA_SetConnectionStatus
DATA prototype SetContactCurrentRating = DATA_SetContactCurrentRating
DATA prototype SetContactObj = DATA_SetContactObj
DATA prototype SetContactOrderBy = DATA_SetContactOrderBy
DATA prototype SetCurrentGame = DATA_SetCurrentGame
Referenced by DATA_AddGame().
DATA prototype SetCurrentOldGame = DATA_SetCurrentOldGame
DATA prototype SetCurrentRoom = DATA_SetCurrentRoom
DATA prototype SetGamecenter = DATA_SetGamecenter
DATA prototype SetLang = DATA_SetLang
DATA prototype SetLoadObj = DATA_SetLoadObj
DATA prototype SetMaxChatChar = DATA_SetMaxChatChar
DATA prototype SetMaxChats = DATA_SetMaxChats
DATA prototype SetOnlineCurrentRating = DATA_SetOnlineCurrentRating
DATA prototype SetOnlineObj = DATA_SetOnlineObj
DATA prototype SetOnlineOrderBy = DATA_SetOnlineOrderBy
DATA prototype SetPassword = DATA_SetPassword
DATA prototype SetPostponeStatus = DATA_SetPostponeStatus
DATA prototype SetRID = DATA_SetRID
DATA prototype SetRoomInformation = DATA_SetRoomInformation
DATA prototype SetSID = DATA_SetSID
DATA prototype SetText = DATA_SetText
DATA prototype SetTurn = DATA_SetTurnGame
Referenced by DATA_AddGame(), DATA_AddOldGame(), and INTERFACE_GameBoardObj().
DATA prototype SetUpdateProfileTimer = DATA_SetUpdateProfileTimer
DATA prototype SetUpdateTimer = DATA_SetUpdateTimer
DATA prototype SetUsername = DATA_SetMyUsername
DATA prototype SetWindowFocus = DATA_SetWindowFocus
Referenced by DATA_RemoveWindow().
DATA prototype SortContactUserByNick = DATA_SortContactUserByNick
DATA prototype SortContactUserByRating = DATA_SortContactUserByRating
DATA prototype SortOnlineUserByNick = DATA_SortOnlineUserByNick
DATA prototype SortOnlineUserByRating = DATA_SortOnlineUserByRating
DATA prototype SortSearchUserByName = DATA_SortSearchUserByName
DATA prototype SortSearchUserByNick = DATA_SortSearchUserByNick
DATA prototype UpdateChallenge = DATA_UpdateChallenge