XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/utils/dragpiece.js File Reference
/home/www/rubens/webclient/scripts/utils/dragpiece.js File Reference
Drag and drop game board pieces.
Functions
function UTILS_StartDragPiece (Obj, Size, event)
Drag and drop piece board Start drag a piece when click or click and hold button a button over a piece. If click for second time(without hold button) then release piece and send move to server. If click and hold button was set and release the button drop piece and send move to server;.
function UTILS_GetMouseCoords (ev)
Get mouse coords.
Variables
var OldPos
Detailed Description
Drag and drop game board pieces.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function UTILS_GetMouseCoords (ev)
Get mouse coords.
Parameters:
ev Javascript Event
Returns:
Tuple with X and Y position (in pixels)
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by UTILS_StartDragPiece(), and UTILS_StartDragWindow().
function UTILS_StartDragPiece (Obj, Size, event)
Drag and drop piece board Start drag a piece when click or click and hold button a button over a piece. If click for second time(without hold button) then release piece and send move to server. If click and hold button was set and release the button drop piece and send move to server;.
Parameters:
Obj DOM Element
Size Piece size
event Javascript Event
Returns:
True of False
Author:
Rubens Suguimoto
References GAME_RemoveBlockBorder(), GAME_RemoveBlockClass(), GAME_SendMove(), GAME_SetBlockClass(), GAME_ShowLoadingMove(), MainData, OldPos, UTILS_GetMouseCoords(), and UTILS_GetOffset().
Referenced by INTERFACE_NewPiece().
Variable Documentation
var OldPos
Referenced by UTILS_StartDragPiece(), and UTILS_StartDragWindow().