XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/game/game.js File Reference
/home/www/rubens/webclient/scripts/game/game.js File Reference
This file will handle all kind of game massages.
Functions
function GAME_HandleGame (XML)
Handle Game Messages.
function GAME_HandlePresence (XML)
Handle game presence.
function GAME_Move (XML)
Handle Game Move.
function GAME_HandleGameResult (XML)
Handle Game Result.
function GAME_State (XML)
Handle Game State.
function GAME_HandleDraw (XML, Xmlns)
Handle Draw Request.
function GAME_HandleCancel (XML, Xmlns)
Handle Cancel Request.
function GAME_HandleAdjourn (XML, Xmlns)
Handle Adjourn Request.
function GAME_End (XML)
Handle a game over message.
function GAME_HandleGameError (XML)
Handle Game Error.
function GAME_StartGame (GameId, P1, P2)
Start some game.
function GAME_StartObserverGame (GameId, P1, P2)
Start Game in Observer Mode.
function GAME_UpdateBoard (GameId, BoardStr, Move, ShortMove, P1, P2, TurnColor)
Update board in data struct and interface.
function GAME_RemoveGame (GameID)
Remove a game from data struct and interface.
function GAME_SendMove (OldLine, OldCol, NewLine, NewCol)
Send a game movement to server.
function GAME_SendDraw (GameID)
Send a draw message request to oponent.
function GAME_SendCancel (GameID)
Send a adjourn message to oponent.
function GAME_SendAdjourn (GameID)
Send a adjourn message to oponent.
function GAME_SearchCurrentGame ()
function GAME_ChangePromotion (Piece)
Change current game piece promotion.
function GAME_SendResign (GameID)
Send a resign message request to oponent.
function GAME_LoadGameHistory (GameID, HistoryXml, Player1, Player2)
Load all game history moves done in the game.
function GAME_HandleVCardPhoto (XML)
Handle Game Players Photo.
function GAME_SetLeftTime (GameID, WTime, BTime)
function GAME_ShowLoadingMove (Id)
function GAME_HideLoadingMove (Id)
function GAME_SetBlockBorder (Line, Col)
function GAME_SetBlockClass (Line, Col)
function GAME_RemoveBlockBorder (Line, Col)
function GAME_GetOponent (GameId)
function GAME_RemoveBlockClass (Line, Col)
Detailed Description
This file will handle all kind of game massages.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function GAME_ChangePromotion (Piece)
Change current game piece promotion.
Parameters:
Piece Piece character
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_CreateGameOptions().
function GAME_End (XML)
Handle a game over message.
Parameters:
XML The xml that contains the ending game message
Returns:
XMPP to send
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONTACT_ChangeStatus(), MainData, OLDGAME_EndGame(), UTILS_GetText(), and WINDOW_Alert().
Referenced by GAME_HandleGame().
function GAME_GetOponent (GameId)
References MainData.
Referenced by GAME_HandleAdjourn(), GAME_HandleCancel(), and GAME_HandleDraw().
function GAME_HandleAdjourn (XML, Xmlns)
Handle Adjourn Request.
Assume adjourn and postpone the samething here
Parameters:
XML The xml that contains the adjourn message
Xmlns Xml namespace string
Returns:
Empty string
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONNECTION_SendJabber(), GAME_GetOponent(), MESSAGE_GameAdjournAccept(), MESSAGE_GameAdjournDeny(), UTILS_GetText(), WINDOW_Alert(), and WINDOW_Confirm().
Referenced by GAME_HandleGame().
function GAME_HandleCancel (XML, Xmlns)
Handle Cancel Request.
Parameters:
XML The xml that contains the cancel game message
Xmlns Xml namespace string
Returns:
Empty string
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONNECTION_SendJabber(), GAME_GetOponent(), MESSAGE_GameCancelAccept(), MESSAGE_GameCancelDeny(), UTILS_GetText(), WINDOW_Alert(), and WINDOW_Confirm().
Referenced by GAME_HandleGame().
function GAME_HandleDraw (XML, Xmlns)
Handle Draw Request.
Parameters:
XML Xml that contains the draw message
Xmlns Xml namespace string
Returns:
Empty string
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONNECTION_SendJabber(), GAME_GetOponent(), MESSAGE_GameDrawAccept(), MESSAGE_GameDrawDeny(), UTILS_GetText(), WINDOW_Alert(), and WINDOW_Confirm().
Referenced by GAME_HandleGame().
function GAME_HandleGame (XML)
Handle Game Messages.
Parameters:
XML XMPP with game messages
Returns:
Buffer with XMPP that must be send
Author:
Ulysses Bomfim and Rubens Suguimoto
References GAME_End(), GAME_HandleAdjourn(), GAME_HandleCancel(), GAME_HandleDraw(), GAME_Move(), and GAME_State().
Referenced by PARSER_ParseIq().
function GAME_HandleGameError (XML)
Handle Game Error.
Parameters:
XML The xml that contains the error message
Returns:
XMPP to be send
Author:
Pedro Rocha and Rubens Suguimoto
References GAME_HideLoadingMove(), MainData, OLDGAME_EndGame(), UTILS_GetText(), and WINDOW_Alert().
Referenced by PARSER_ParseIq().
function GAME_HandleGameResult (XML)
Handle Game Result.
This code is used to parse games that player is playing. Used to enter automatically in some game that player is playing.
Parameters:
XML The xml that contains the game result
Returns:
XMPP to be send
Author:
Rubens Suguimoto
References MainData, and MESSAGE_Presence().
Referenced by PARSER_ParseIq().
function GAME_HandlePresence (XML)
Handle game presence.
Parameters:
XML XMPP with game messages
Returns:
Buffer with XMPP that must be send
Author:
Rubens Suguimoto
References MainData.
Referenced by PARSER_ParsePresence().
function GAME_HandleVCardPhoto (XML)
Handle Game Players Photo.
Parameters:
XML XMPP that contains vCard photo
Returns:
none
Author:
Rubens Suguimoto
References MainData, and UTILS_GetNodeText().
Referenced by PARSER_ParseIq().
function GAME_HideLoadingMove (Id)
References MainData.
Referenced by GAME_HandleGameError().
function GAME_LoadGameHistory (GameID, HistoryXml, Player1, Player2)
Load all game history moves done in the game.
Parameters:
GameID Game identification number
HistoryXml XML that contains all games states
Player1 First player object (Name, Time, Color, Inc)
Player2 Second player object (Name, Time, Color, Inc)
Returns:
none
Author:
Rubens Suguimoto
References GAME_UpdateBoard().
Referenced by GAME_State().
function GAME_Move (XML)
Handle Game Move.
Parameters:
XML The XMPP that contains the game move
Returns:
none
Author:
Ulysses Bomfim and Rubens Suguimoto
References GAME_StartGame(), GAME_UpdateBoard(), and MainData.
Referenced by GAME_HandleGame(), and GAME_State().
function GAME_RemoveBlockBorder (Line, Col)
References MainData, and UTILS_HorizontalIndex().
Referenced by UTILS_StartDragPiece().
function GAME_RemoveBlockClass (Line, Col)
References MainData, and UTILS_HorizontalIndex().
Referenced by UTILS_StartDragPiece().
function GAME_RemoveGame (GameID)
Remove a game from data struct and interface.
Parameters:
GameID Game identification number
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
References GAMECENTER_ShowGameCenter(), MainData, ROOM_ExitRoom(), UTILS_GetText(), and WINDOW_Alert().
Referenced by GAME_StartObserverGame(), and INTERFACE_CreateGame().
function GAME_SearchCurrentGame ()
References CONNECTION_SendJabber(), and MESSAGE_GameSearchCurrentGame().
Referenced by START_Webclient().
function GAME_SendAdjourn (GameID)
Send a adjourn message to oponent.
Parameters:
GameID Game identification number
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_GameRequestAdjourn().
Referenced by INTERFACE_CreateGameOptions().
function GAME_SendCancel (GameID)
Send a adjourn message to oponent.
Parameters:
GameID Game identification number
Returns:
none
Author:
Pedro
References CONNECTION_SendJabber(), and MESSAGE_GameRequestCancel().
Referenced by INTERFACE_CreateGameOptions().
function GAME_SendDraw (GameID)
Send a draw message request to oponent.
Parameters:
GameID Game identification number
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_GameRequestDraw().
Referenced by INTERFACE_CreateGameOptions().
function GAME_SendMove (OldLine, OldCol, NewLine, NewCol)
Send a game movement to server.
Parameters:
OldLine Line origin position
OldCol Column origin position
NewLine Line dest position
NewCol Column dest position
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, MESSAGE_GameMove(), and UTILS_HorizontalIndex().
Referenced by UTILS_StartDragPiece().
function GAME_SendResign (GameID)
Send a resign message request to oponent.
Parameters:
GameID Game identification number
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References CONNECTION_SendJabber(), MESSAGE_GameResign(), UTILS_GetText(), and WINDOW_Confirm().
Referenced by INTERFACE_CreateGameOptions().
function GAME_SetBlockBorder (Line, Col)
References MainData, and UTILS_HorizontalIndex().
function GAME_SetBlockClass (Line, Col)
References MainData, and UTILS_HorizontalIndex().
Referenced by UTILS_StartDragPiece().
function GAME_SetLeftTime (GameID, WTime, BTime)
References MainData.
Referenced by GAME_State().
function GAME_ShowLoadingMove (Id)
References MainData.
Referenced by UTILS_StartDragPiece().
function GAME_StartGame (GameId, P1, P2)
Start some game.
Parameters:
GameId Game identification number
P1 First Player Object (Name, Time, Color, Inc)
P2 Second Player Object (Name, Time, Color, Inc)
Returns:
XMPP to be send
Author:
Rubens Suguimoto
References ANNOUNCE_CancelAllAnnounce(), CHALLENGE_ClearChallenges(), CONTACT_ChangeStatus(), GAMECENTER_HideGameCenter(), INTERFACE_GameBoardObj(), MainData, MESSAGE_GetProfile(), and MESSAGE_Unavailable().
Referenced by GAME_Move(), GAME_State(), INTERFACE_AddCurrentGames(), and INTERFACE_ShowGameRoomList().
function GAME_StartObserverGame (GameId, P1, P2)
Start Game in Observer Mode.
Parameters:
GameId Game identification number
P1 White player object
P2 Black player object
Returns:
none
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), GAME_RemoveGame(), GAMECENTER_HideGameCenter(), INTERFACE_GameBoardObj(), MainData, MESSAGE_GetProfile(), OLDGAME_RemoveOldGame(), and ROOM_EnterRoomGame().
Referenced by CURRENTGAME_HandleGameRoomInfoList(), and INTERFACE_ShowGameRoomList().
function GAME_State (XML)
Handle Game State.
Parameters:
XML The xml that contains the game state
Returns:
XMPP to be send
Author:
Ulysses Bomfim and Rubens Suguimoto
References GAME_LoadGameHistory(), GAME_Move(), GAME_SetLeftTime(), GAME_StartGame(), and MainData.
Referenced by GAME_HandleGame().
function GAME_UpdateBoard (GameId, BoardStr, Move, ShortMove, P1, P2, TurnColor)
Update board in data struct and interface.
Parameters:
GameId Game identification number
BoardStr Board status in a string
Move Chess Move (Piece/Orig-Dest)
ShortMove Move in short notation
P1 First player object (Name, Time, Color, Inc)
P2 Second player object (Name, Time, Color, Inc)
TurnColor Turn's Color("white"/"black")
Returns:
Empty string
Author:
Rubens Suguimoto
References MainData, and UTILS_String2Board().
Referenced by GAME_LoadGameHistory(), and GAME_Move().