XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/game/oldgame.js File Reference
/home/www/rubens/webclient/scripts/game/oldgame.js File Reference
This file contains old game functions.
Functions
function OLDGAME_HandleSearchOldGame (XML)
Handle search old games messages.
function OLDGAME_StartOldGame (OldGameId, P1, P2)
Start Game in OldGame Mode.
function OLDGAME_FetchOldGame (XML)
Handle old game states.
function OLDGAME_LoadGameHistory (GamePos, HistoryXml, Player1, Player2)
Load all game history moves done in the game.
function OLDGAME_UpdateBoard (GamePos, BoardStr, Move, ShortMove, P1, P2, TurnColor)
Update board in data struct and interface.
function OLDGAME_EndGame (Id)
Change board GameMode to OldGame Mode when game was over.
function OLDGAME_HandleVCardPhoto (XML)
Handle game players photos.
function OLDGAME_RemoveOldGame (Index)
Remove OldGame board from interface and OldGameList.
function OLDGAME_FirstBoard ()
Change current board state to first game board state.
function OLDGAME_PrevBoard ()
Change current board state to previous game board state.
function OLDGAME_NextBoard ()
Change current board state to next game board state.
function OLDGAME_LastBoard ()
Change current board state to last game board state.
function OLDGAME_GotoBoard (NumBoard)
Change current board state to some game board state.
function OLDGAME_OpenOldGameWindow (User)
Create search old game window and get old game list.
function OLDGAME_CloseWindow (Id)
Remove Search Game Info in data struct and set new old game window max id count.
function OLDGAME_GameResult (Result)
Return apropriate result text according to old game result.
Detailed Description
This file contains old game functions.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function OLDGAME_CloseWindow (Id)
Remove Search Game Info in data struct and set new old game window max id count.
Parameters:
Id Window's id
Returns:
void
Author:
Danilo Yorinori
References MainData.
Referenced by INTERFACE_OldGameSetTable(), and WINDOW_OldGame().
function OLDGAME_EndGame (Id)
Change board GameMode to OldGame Mode when game was over.
Parameters:
Id Game identification number
Returns:
none
Author:
Rubens Suguimoto
References MainData, OLDGAME_LastBoard(), and OLDGAME_RemoveOldGame().
Referenced by GAME_End(), and GAME_HandleGameError().
function OLDGAME_FetchOldGame (XML)
Handle old game states.
Parameters:
XML XMPP that contains the game state
Returns:
XMPP to send
Author:
Ulysses Bomfim and Rubens Suguimoto
References OLDGAME_LoadGameHistory(), and OLDGAME_StartOldGame().
Referenced by PARSER_ParseIq().
function OLDGAME_FirstBoard ()
Change current board state to first game board state.
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_CreateOldGameMoveList(), and OLDGAME_LoadGameHistory().
function OLDGAME_GameResult (Result)
Return apropriate result text according to old game result.
Parameters:
Result Result's string
Returns:
Result text string
See also:
OLDGAME_HandleSearchOldGame
Author:
Danilo Yorinori
References UTILS_GetText().
Referenced by OLDGAME_HandleSearchOldGame().
function OLDGAME_GotoBoard (NumBoard)
Change current board state to some game board state.
Parameters:
NumBoard Board number state
Returns:
void
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_AddMove().
function OLDGAME_HandleSearchOldGame (XML)
Handle search old games messages.
Parameters:
XML XMPP that contains search game data result
Returns:
XMPP to be send
Author:
Rubens Suguimoto
References INTERFACE_HideOldgameLoading(), MainData, OLDGAME_GameResult(), and UTILS_ConvertTimeStamp().
Referenced by PARSER_ParseIq().
function OLDGAME_HandleVCardPhoto (XML)
Handle game players photos.
Parameters:
XML XMPP that contains vCard photo
Returns:
Empty string
Author:
Rubens Suguimoto
References MainData, and UTILS_GetNodeText().
Referenced by PARSER_ParseIq().
function OLDGAME_LastBoard ()
Change current board state to last game board state.
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_CreateOldGameMoveList(), and OLDGAME_EndGame().
function OLDGAME_LoadGameHistory (GamePos, HistoryXml, Player1, Player2)
Load all game history moves done in the game.
Parameters:
GamePos Game identification number (index)
HistoryXml XML that contains all games states
Player1 First Player object (Name, Time, Color, Inc)
Player2 Second Player object (Name, Time, Color, Inc)
Returns:
XMPP to send
Author:
Rubens Suguimoto
References MainData, OLDGAME_FirstBoard(), OLDGAME_UpdateBoard(), UTILS_GetText(), and WINDOW_Alert().
Referenced by OLDGAME_FetchOldGame().
function OLDGAME_NextBoard ()
Change current board state to next game board state.
Returns:
False (if not found a next state) or True otherwise
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_CreateOldGameMoveList().
function OLDGAME_OpenOldGameWindow (User)
Create search old game window and get old game list.
Returns:
none
Author:
Danilo Yorinori
References CONNECTION_SendJabber(), MainData, MESSAGE_GetOldGames(), and WINDOW_OldGame().
Referenced by INTERFACE_CreateTop(), and INTERFACE_ShowProfileWindow().
function OLDGAME_PrevBoard ()
Change current board state to previous game board state.
Returns:
False (if not found a previous state) or True otherwise
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_CreateOldGameMoveList().
function OLDGAME_RemoveOldGame (Index)
Remove OldGame board from interface and OldGameList.
Parameters:
Index OldGame identification number (index)
Returns:
none
Author:
Rubens Suguimoto
References GAMECENTER_ShowGameCenter(), MainData, and ROOM_ExitRoom().
Referenced by GAME_StartObserverGame(), OLDGAME_EndGame(), and OLDGAME_StartOldGame().
function OLDGAME_StartOldGame (OldGameId, P1, P2)
Start Game in OldGame Mode.
Parameters:
OldGameId Old game identification number (index)
P1 First player object (Name, Time, Color, Inc)
P2 Second player object (Name, Time, Color, Inc)
Returns:
XMPP to send
Author:
Rubens Suguimoto
References GAMECENTER_HideGameCenter(), INTERFACE_GameBoardObj(), MainData, MESSAGE_GetProfile(), and OLDGAME_RemoveOldGame().
Referenced by OLDGAME_FetchOldGame().
function OLDGAME_UpdateBoard (GamePos, BoardStr, Move, ShortMove, P1, P2, TurnColor)
Update board in data struct and interface.
Parameters:
GamePos Game identification number (index)
BoardStr Board status in a string
Move Chess game move (Piece/Orig-Dest)
ShortMove Move in short format
P1 First player object (Name, Time, Color, Inc)
P2 Second player object (Name, Time, Color, Inc)
TurnColor Game turn color ("white"/"black")
Returns:
Empty string
Author:
Rubens Suguimoto
References MainData, and UTILS_String2Board().
Referenced by OLDGAME_LoadGameHistory().