XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/gamecenter/gamecenter.js File Reference
/home/www/rubens/webclient/scripts/gamecenter/gamecenter.js File Reference
Functions
function GAMECENTER_StartGameCenter ()
Start game center object and show in web interface.
function GAMECENTER_ShowGameCenter ()
Show game center object.
function GAMECENTER_HideGameCenter ()
Hide game center object.
function GAMECENTER_ShowAnnounce ()
Show announced games in game center object and hide others tabs.
function GAMECENTER_ShowPostpone ()
Show postponed games in game center object and hide others tabs.
function GAMECENTER_ShowMatchOffer ()
Show received and send challenges in game center object and hide others tabs.
function GAMECENTER_ShowTourney ()
Show tourneys created in game center object and hide others tabs.
function GAMECENTER_ShowCurrentGames ()
Show playing games in game center object and hide others tabs.
function GAMECENTER_ClearCurrentGames ()
Remove all playing games in game center object.
function GAMECENTER_AnnounceSortByUsername ()
Sort announced games by username.
function GAMECENTER_AnnounceSortByCategory ()
Sort announced games by category.
function GAMECENTER_AnnounceSortByRating ()
Sort announced games by user's rating.
function GAMECENTER_AnnounceSortByTime ()
Sort announced games by game time.
function GAMECENTER_AnnounceSortByInc ()
Sort announced games by game increment.
function GAMECENTER_AnnounceSortByRated ()
Sort announced games by game rated.
function GAMECENTER_AnnounceSortByPrivate ()
Sort announced games by game private.
function GAMECENTER_PostponeSortByUsername ()
Sort postponed games by username.
function GAMECENTER_PostponeSortByRating ()
Sort postponed games by user's rating.
function GAMECENTER_PostponeSortByCategory ()
Sort postponed games by game category.
function GAMECENTER_PostponeSortByTime ()
Sort postponed games by game time.
function GAMECENTER_PostponeSortByInc ()
Sort postponed games by game increment.
function GAMECENTER_PostponeSortByDate ()
Sort postponed games by game postpone date.
function GAMECENTER_CurrentGamesSortByWRating ()
Sort current games by white player's rating.
function GAMECENTER_CurrentGamesSortByBRating ()
Sort current games by black player's rating.
function GAMECENTER_CurrentGamesSortByCategory ()
Sort current games by game category.
function GAMECENTER_CurrentGamesSortByTime ()
Sort current games by game time.
function GAMECENTER_CurrentGamesSortByMoves ()
Sort current games by players moves done.
function GAMECENTER_CurrentGamesSortByRated ()
Sort current games by game rated.
function GAMECENTER_MatchOfferSortByUsername ()
Sort challenges by username.
function GAMECENTER_MatchOfferSortByTime ()
Sort challenges by game time.
function GAMECENTER_MatchOfferSortByInc ()
Sort challenges by game increment.
function GAMECENTER_MatchOfferSortByCategory ()
Sort challenges by game category.
function GAMECENTER_MatchOfferSortByRating ()
Sort challenges by user's rating.
function GAMECENTER_MatchOfferSortByRated ()
Sort challenges by game rated.
function GAMECENTER_MatchOfferSortByPrivate ()
Sort challenges by game private.
Function Documentation
function GAMECENTER_AnnounceSortByCategory ()
Sort announced games by category.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterAnnounce().
function GAMECENTER_AnnounceSortByInc ()
Sort announced games by game increment.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterAnnounce().
function GAMECENTER_AnnounceSortByPrivate ()
Sort announced games by game private.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterAnnounce().
function GAMECENTER_AnnounceSortByRated ()
Sort announced games by game rated.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterAnnounce().
function GAMECENTER_AnnounceSortByRating ()
Sort announced games by user's rating.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterAnnounce().
function GAMECENTER_AnnounceSortByTime ()
Sort announced games by game time.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterAnnounce().
function GAMECENTER_AnnounceSortByUsername ()
Sort announced games by username.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterAnnounce().
function GAMECENTER_ClearCurrentGames ()
Remove all playing games in game center object.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by GAMECENTER_ShowCurrentGames(), and INTERFACE_CreateGameCenterCurrentGames().
function GAMECENTER_CurrentGamesSortByBRating ()
Sort current games by black player's rating.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterCurrentGames().
function GAMECENTER_CurrentGamesSortByCategory ()
Sort current games by game category.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterCurrentGames().
function GAMECENTER_CurrentGamesSortByMoves ()
Sort current games by players moves done.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterCurrentGames().
function GAMECENTER_CurrentGamesSortByRated ()
Sort current games by game rated.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterCurrentGames().
function GAMECENTER_CurrentGamesSortByTime ()
Sort current games by game time.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterCurrentGames().
function GAMECENTER_CurrentGamesSortByWRating ()
Sort current games by white player's rating.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterCurrentGames().
function GAMECENTER_HideGameCenter ()
Hide game center object.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by GAME_StartGame(), GAME_StartObserverGame(), and OLDGAME_StartOldGame().
function GAMECENTER_MatchOfferSortByCategory ()
Sort challenges by game category.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterMatch().
function GAMECENTER_MatchOfferSortByInc ()
Sort challenges by game increment.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterMatch().
function GAMECENTER_MatchOfferSortByPrivate ()
Sort challenges by game private.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterMatch().
function GAMECENTER_MatchOfferSortByRated ()
Sort challenges by game rated.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterMatch().
function GAMECENTER_MatchOfferSortByRating ()
Sort challenges by user's rating.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterMatch().
function GAMECENTER_MatchOfferSortByTime ()
Sort challenges by game time.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterMatch().
function GAMECENTER_MatchOfferSortByUsername ()
Sort challenges by username.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterMatch().
function GAMECENTER_PostponeSortByCategory ()
Sort postponed games by game category.
Returns:
none
Author:
Rubens
References CHALLENGE_PostponePresence(), GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterPostpone().
function GAMECENTER_PostponeSortByDate ()
Sort postponed games by game postpone date.
Returns:
none
Author:
Rubens
References CHALLENGE_PostponePresence(), GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterPostpone().
function GAMECENTER_PostponeSortByInc ()
Sort postponed games by game increment.
Returns:
none
Author:
Rubens
References CHALLENGE_PostponePresence(), GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterPostpone().
function GAMECENTER_PostponeSortByRating ()
Sort postponed games by user's rating.
Returns:
none
Author:
Rubens
References CHALLENGE_PostponePresence(), GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterPostpone().
function GAMECENTER_PostponeSortByTime ()
Sort postponed games by game time.
Returns:
none
Author:
Rubens
References CHALLENGE_PostponePresence(), GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterPostpone().
function GAMECENTER_PostponeSortByUsername ()
Sort postponed games by username.
Returns:
none
Author:
Rubens
References CHALLENGE_PostponePresence(), GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenterPostpone().
function GAMECENTER_ShowAnnounce ()
Show announced games in game center object and hide others tabs.
Returns:
none
Author:
Rubens
References ANNOUNCE_GetAnnounceGames(), GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenter().
function GAMECENTER_ShowCurrentGames ()
Show playing games in game center object and hide others tabs.
Returns:
none
Author:
Rubens
References CONNECTION_SendJabber(), GAMECENTER_ClearCurrentGames(), GameCenterObj(), MainData, and MESSAGE_GameRoomList().
Referenced by INTERFACE_CreateGameCenter().
function GAMECENTER_ShowGameCenter ()
Show game center object.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by GAME_RemoveGame(), and OLDGAME_RemoveOldGame().
function GAMECENTER_ShowMatchOffer ()
Show received and send challenges in game center object and hide others tabs.
Returns:
none
Author:
Rubens
References GameCenterObj(), and MainData.
Referenced by INTERFACE_CreateGameCenter().
function GAMECENTER_ShowPostpone ()
Show postponed games in game center object and hide others tabs.
Returns:
none
Author:
Rubens
References CONNECTION_SendJabber(), GameCenterObj(), MainData, and MESSAGE_ChallengeGetAdjournList().
Referenced by INTERFACE_CreateGameCenter().
function GAMECENTER_ShowTourney ()
Show tourneys created in game center object and hide others tabs.
Returns:
none
Author:
Rubens
References GameCenterObj().
function GAMECENTER_StartGameCenter ()
Start game center object and show in web interface.
Returns:
none
Author:
Rubens
References ANNOUNCE_GetAnnounceGames(), GameCenterObj(), and MainData.
Referenced by START_Webclient().