XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/help.js File Reference
/home/www/rubens/webclient/scripts/interface/help.js File Reference
Create window content to show help and auxiliar functions.
Functions
function INTERFACE_HelpWindow ()
Create temporary help window content.
function INTERFACE_CreateHelpContent (Text)
Create help content div and set text passed as parameter.
function INTERFACE_ShowHideHelpContent (ObjId)
Show or hide help content of section with Id passed as parameter.
function INTERFACE_ShowLinkContent (ObjId)
Show help content of linked section with Id passed as parameter.
function INTERFACE_HelpDisplay (Obj, Id)
Set help section title element action to open content and not be selected when clicked.
Detailed Description
Create window content to show help and auxiliar functions.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function INTERFACE_CreateHelpContent (Text)
Create help content div and set text passed as parameter.
Parameters:
Text Text to be insert in div content
Returns:
HTML DOM Div Element
Author:
Danilo Yorinori
See also:
INTERFACE_HelpWindow
References UTILS_CreateElement().
Referenced by INTERFACE_HelpWindow().
function INTERFACE_HelpDisplay (Obj, Id)
Set help section title element action to open content and not be selected when clicked.
Parameters:
Obj Help section title element
Id Section's Id
Returns:
none
Author:
Danilo Yorinori
See also:
INTERFACE_HelpWindow
References INTERFACE_DisableSelect(), INTERFACE_ReEnableSelect(), and INTERFACE_ShowHideHelpContent().
Referenced by INTERFACE_HelpWindow().
function INTERFACE_HelpWindow ()
Create temporary help window content.
Returns:
Main Div content and Buttons array
Author:
Danilo Yorinori
See also:
Texts (lang), WINDOW_Help();
References INTERFACE_CreateHelpContent(), INTERFACE_HelpDisplay(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_Help().
function INTERFACE_ShowHideHelpContent (ObjId)
Show or hide help content of section with Id passed as parameter.
Parameters:
ObjId Section's Id
Returns:
True if sucess or false if not found ObjId
Author:
Danilo Yorinori
See also:
INTERFACE_HelpDisplay
Referenced by INTERFACE_HelpDisplay().
function INTERFACE_ShowLinkContent (ObjId)
Show help content of linked section with Id passed as parameter.
Parameters:
ObjId Section's Id
Returns:
True if sucess or false if not found ObjId
Author:
Danilo Yorinori
See also:
INTERFACE_HelpWindow