XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/utils/images.js File Reference
/home/www/rubens/webclient/scripts/utils/images.js File Reference
This file contais all function used to decode/encode images to base64.
Functions
function IMAGE_CreateFormToEncode (FormId, Action)
Create input file to user.
function IMAGE_ImageDecode (ImgSrc)
This function is used to show image base64 in IE6.
function IMAGE_ImageEncode (FormId)
This function get image and convert to base64.
function IMAGE_B64Img (Image, Type)
When image is loaded this function is called.
Detailed Description
This file contais all function used to decode/encode images to base64.
Function Documentation
function IMAGE_B64Img (Image, Type)
When image is loaded this function is called.
Parameters:
Image is the image base 64
Type is the image type
Returns:
void
Author:
Fabiano Kuss and Rubens Suguimoto
References MainData, UTILS_GetText(), and WINDOW_Alert().
function IMAGE_CreateFormToEncode (FormId, Action)
Create input file to user.
Parameters:
FormId is Form identificator
Action is script source
Returns:
Form HTML element
Author:
Fabiano Kuss and Rubens Suguimoto
Referenced by WINDOW_CreateImageSend().
function IMAGE_ImageDecode (ImgSrc)
This function is used to show image base64 in IE6.
Parameters:
ImgSrc is the image source in base64 Firefox standart
Returns:
Image base64 in IE Format
Author:
Fabiano Kuss and Rubens Suguimoto
References MainData.
Referenced by INTERFACE_ProfileSetUserImg(), INTERFACE_SetBPhoto(), INTERFACE_SetUserImage(), and INTERFACE_SetWPhoto().
function IMAGE_ImageEncode (FormId)
This function get image and convert to base64.
Parameters:
FormId is Form identificator
Returns:
void
Author:
Fabiano Kuss and Rubens Suguimoto
Referenced by WINDOW_CreateImageSend().