XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/contact/info.js File Reference
/home/www/rubens/webclient/scripts/contact/info.js File Reference
Handle user information to contact list(rating an type).
Functions
function CONTACT_HandleInfo (XML)
Receive a info message and update new information in contact list.
function CONTACT_SetUserType (Username, NewType)
Change user's type of some user in contact list.
function CONTACT_SetUserRating (Username, Category, Rating)
Change user's rating of some user in contact list.
Detailed Description
Handle user information to contact list(rating an type).
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function CONTACT_HandleInfo (XML)
Receive a info message and update new information in contact list.
Parameters:
XML XMPP with chess server user's info
Returns:
Empty string
Author:
Rubens Suguimoto
References CONTACT_SetUserRating(), CONTACT_SetUserType(), and MainData.
Referenced by PARSER_ParseIq().
function CONTACT_SetUserRating (Username, Category, Rating)
Change user's rating of some user in contact list.
Parameters:
Username User's name
Category Rating game category
Rating Rating value to be update
Returns:
none
Author:
Rubens Suguimoto
References ContactObj(), and MainData.
Referenced by CONTACT_HandleInfo().
function CONTACT_SetUserType (Username, NewType)
Change user's type of some user in contact list.
Parameters:
Username User's name
NewType New user's type
Returns:
none
Author:
Rubens Suguimoto
References ContactObj(), and MainData.
Referenced by CONTACT_HandleInfo().