XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/chat.js File Reference
/home/www/rubens/webclient/scripts/interface/chat.js File Reference
Interface functions for chat.
Functions
function ChatObj (Username, Position)
function INTERFACE_ShowChat (Element)
Show chat window.
function INTERFACE_HideChat ()
Hide chat window.
function INTERFACE_CloseChat ()
Close a chat.
function INTERFACE_FocusChat ()
Giving focus to a chat window.
function INTERFACE_BlurChat ()
Remove focus of a chat window.
function INTERFACE_MinimizeChat ()
Minimize a chat window.
function INTERFACE_MaximizeChat ()
Maximize chat window.
function INTERFACE_AddChatMessage (Username, Message)
Show a message in a open chat.
function INTERFACE_AddChatMessageError (Message)
function INTERFACE_InputChatFocus ()
function INTERFACE_SetChatPosition (Num)
function INTERFACE_SetChatTitle (Str)
function INTERFACE_CreateChat (Username)
Create chat HTML DOM elements.
function INTERFACE_CreateChatList ()
Create chat list elements.
function INTERFACE_ChatListPositioning ()
Set chat list position automatically when move scroll.
Detailed Description
Interface functions for chat.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function ChatObj (Username, Position)
References INTERFACE_AddChatMessage(), INTERFACE_AddChatMessageError(), INTERFACE_BlurChat(), INTERFACE_CloseChat(), INTERFACE_CreateChat(), INTERFACE_FocusChat(), INTERFACE_HideChat(), INTERFACE_InputChatFocus(), INTERFACE_MaximizeChat(), INTERFACE_MinimizeChat(), INTERFACE_SetChatPosition(), INTERFACE_SetChatTitle(), and INTERFACE_ShowChat().
Referenced by CHAT_BlurChat(), CHAT_ChangeChatState(), CHAT_ChangeUserChatStatus(), CHAT_CloseChat(), CHAT_ErrorMessageLength(), CHAT_OpenChat(), CHAT_ReceiveMessage(), CHAT_SendMessage(), DATA_AddChat(), and DATA_AddShowChat().
function INTERFACE_AddChatMessage (Username, Message)
Show a message in a open chat.
Parameters:
Username User's name
Message User's message text
Returns:
True
Author:
Pedro Rocha and Rubens Suguimoto
References UTILS_CreateElement(), and UTILS_GetTime().
Referenced by ChatObj().
function INTERFACE_AddChatMessageError (Message)
References UTILS_CreateElement().
Referenced by ChatObj().
function INTERFACE_BlurChat ()
Remove focus of a chat window.
Returns:
none
Author:
Rubens Suguimoto
Referenced by ChatObj().
function INTERFACE_ChatListPositioning ()
Set chat list position automatically when move scroll.
Returns:
True if moved or false if chat list not found
Author:
Pedro Rocha and Rubens Suguimoto
Referenced by INTERFACE_CreateChatList().
function INTERFACE_CloseChat ()
Close a chat.
Returns:
none
Author:
Rubens Suguimoto
Referenced by ChatObj().
function INTERFACE_CreateChat (Username)
Create chat HTML DOM elements.
Parameters:
Username User's name
Returns:
Chat HTML DOM elements
Author:
Rubens Suguimoto
References CHAT_BlurChat(), CHAT_ChangeChatState(), CHAT_CloseChat(), CHAT_ErrorMessageLength(), CHAT_SendMessage(), MainData, UTILS_CreateElement(), and UTILS_ReturnKeyCode().
Referenced by ChatObj().
function INTERFACE_CreateChatList ()
Create chat list elements.
Returns:
Chat HTML DOM Div
Author:
Pedro Rocha and Rubens Suguimoto
References INTERFACE_ChatListPositioning(), and UTILS_CreateElement().
Referenced by INTERFACE_CreateInterface().
function INTERFACE_FocusChat ()
Giving focus to a chat window.
Returns:
none
Author:
Rubens Suguimoto
Referenced by ChatObj().
function INTERFACE_HideChat ()
Hide chat window.
Returns:
none
Author:
Rubens Suguimoto
Referenced by ChatObj().
function INTERFACE_InputChatFocus ()
Referenced by ChatObj().
function INTERFACE_MaximizeChat ()
Maximize chat window.
Returns:
none
Author:
Rubens Suguimoto
Referenced by ChatObj().
function INTERFACE_MinimizeChat ()
Minimize a chat window.
Returns:
none
Author:
Rubens Suguimoto
Referenced by ChatObj().
function INTERFACE_SetChatPosition (Num)
Referenced by ChatObj().
function INTERFACE_SetChatTitle (Str)
Referenced by ChatObj().
function INTERFACE_ShowChat (Element)
Show chat window.
Parameters:
Element HTML DOM Element
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
Referenced by ChatObj().