XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/gamecenter.js File Reference
/home/www/rubens/webclient/scripts/interface/gamecenter.js File Reference
Control interface game center.
Functions
function GameCenterObj ()
function INTERFACE_ShowGameCenter (Element)
function INTERFACE_HideGameCenter ()
function INTERFACE_CreateGameCenter ()
function AnnounceObj ()
function INTERFACE_AddAnnounce (Player, Rating, Time, Inc, Category, Rated, Private, MatchId)
function INTERFACE_RemoveAnnounce (MatchId)
function INTERFACE_ShowAnnounceCenter (Element)
function INTERFACE_HideAnnounceCenter ()
function INTERFACE_ShowNoAnnounce ()
function INTERFACE_HideNoAnnounce ()
function INTERFACE_CreateGameCenterAnnounce ()
function MatchOfferObj ()
function INTERFACE_AddMatchOffer (Player, Time, Inc, Category, Rated, Private, MatchId)
function INTERFACE_RemoveMatchOffer (MatchId)
function INTERFACE_ShowMatchCenter (Element)
function INTERFACE_HideMatchCenter ()
function INTERFACE_ShowNoMatch ()
function INTERFACE_HideNoMatch ()
function INTERFACE_CreateGameCenterMatch ()
function PostponeObj ()
function INTERFACE_AddPostpone (Player, Time, Inc, Category, Rating, Date, PostponeId)
function INTERFACE_RemovePostpone (PostponeId)
function INTERFACE_UpdatePostpone (OponentName, OponentStatus)
function INTERFACE_ShowPostponeCenter (Element)
function INTERFACE_HidePostponeCenter ()
function INTERFACE_ShowNoPostpone ()
function INTERFACE_HideNoPostpone ()
function INTERFACE_CreateGameCenterPostpone ()
function CurrentGamesObj ()
function INTERFACE_AddCurrentGames (WPlayer, WRating, BPlayer, BRating, Category, GameTime, Rated, Moves, CurrentGamesId)
function INTERFACE_RemoveCurrentGames (CurrentGamesId)
function INTERFACE_ShowCurrentGamesCenter (Element)
function INTERFACE_HideCurrentGamesCenter ()
function INTERFACE_ShowNoCurrentGames ()
function INTERFACE_HideNoCurrentGames ()
function INTERFACE_CreateGameCenterCurrentGames ()
Detailed Description
Control interface game center.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function AnnounceObj ()
References INTERFACE_AddAnnounce(), INTERFACE_CreateGameCenterAnnounce(), INTERFACE_HideAnnounceCenter(), INTERFACE_HideNoAnnounce(), INTERFACE_RemoveAnnounce(), INTERFACE_ShowAnnounceCenter(), and INTERFACE_ShowNoAnnounce().
Referenced by GameCenterObj().
function CurrentGamesObj ()
References INTERFACE_AddCurrentGames(), INTERFACE_CreateGameCenterCurrentGames(), INTERFACE_HideCurrentGamesCenter(), INTERFACE_HideNoCurrentGames(), INTERFACE_RemoveCurrentGames(), INTERFACE_ShowCurrentGamesCenter(), and INTERFACE_ShowNoCurrentGames().
Referenced by GameCenterObj().
function GameCenterObj ()
References AnnounceObj(), CurrentGamesObj(), INTERFACE_CreateGameCenter(), INTERFACE_HideGameCenter(), INTERFACE_ShowGameCenter(), MatchOfferObj(), and PostponeObj().
Referenced by GAMECENTER_AnnounceSortByCategory(), GAMECENTER_AnnounceSortByInc(), GAMECENTER_AnnounceSortByPrivate(), GAMECENTER_AnnounceSortByRated(), GAMECENTER_AnnounceSortByRating(), GAMECENTER_AnnounceSortByTime(), GAMECENTER_AnnounceSortByUsername(), GAMECENTER_ClearCurrentGames(), GAMECENTER_CurrentGamesSortByBRating(), GAMECENTER_CurrentGamesSortByCategory(), GAMECENTER_CurrentGamesSortByMoves(), GAMECENTER_CurrentGamesSortByRated(), GAMECENTER_CurrentGamesSortByTime(), GAMECENTER_CurrentGamesSortByWRating(), GAMECENTER_HideGameCenter(), GAMECENTER_MatchOfferSortByCategory(), GAMECENTER_MatchOfferSortByInc(), GAMECENTER_MatchOfferSortByPrivate(), GAMECENTER_MatchOfferSortByRated(), GAMECENTER_MatchOfferSortByRating(), GAMECENTER_MatchOfferSortByTime(), GAMECENTER_MatchOfferSortByUsername(), GAMECENTER_PostponeSortByCategory(), GAMECENTER_PostponeSortByDate(), GAMECENTER_PostponeSortByInc(), GAMECENTER_PostponeSortByRating(), GAMECENTER_PostponeSortByTime(), GAMECENTER_PostponeSortByUsername(), GAMECENTER_ShowAnnounce(), GAMECENTER_ShowCurrentGames(), GAMECENTER_ShowGameCenter(), GAMECENTER_ShowMatchOffer(), GAMECENTER_ShowPostpone(), GAMECENTER_ShowTourney(), and GAMECENTER_StartGameCenter().
function INTERFACE_AddAnnounce (Player, Rating, Time, Inc, Category, Rated, Private, MatchId)
References ANNOUNCE_AcceptAnnounce(), ANNOUNCE_CancelAnnounce(), MainData, UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
function INTERFACE_AddCurrentGames (WPlayer, WRating, BPlayer, BRating, Category, GameTime, Rated, Moves, CurrentGamesId)
References CONNECTION_SendJabber(), GAME_StartGame(), MainData, MESSAGE_GameEnterRoom(), MESSAGE_Presence(), UTILS_CreateElement(), UTILS_GetText(), UTILS_ShortString(), and WINDOW_Alert().
Referenced by CurrentGamesObj().
function INTERFACE_AddMatchOffer (Player, Time, Inc, Category, Rated, Private, MatchId)
References CHALLENGE_DeclineChallenge(), UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
function INTERFACE_AddPostpone (Player, Time, Inc, Category, Rating, Date, PostponeId)
References UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
function INTERFACE_CreateGameCenter ()
References GAMECENTER_ShowAnnounce(), GAMECENTER_ShowCurrentGames(), GAMECENTER_ShowMatchOffer(), GAMECENTER_ShowPostpone(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by GameCenterObj().
function INTERFACE_CreateGameCenterAnnounce ()
References ANNOUNCE_AcceptRandomAnnounce(), ANNOUNCE_ClearAnnounce(), CONNECTION_SendJabber(), GAMECENTER_AnnounceSortByCategory(), GAMECENTER_AnnounceSortByInc(), GAMECENTER_AnnounceSortByPrivate(), GAMECENTER_AnnounceSortByRated(), GAMECENTER_AnnounceSortByRating(), GAMECENTER_AnnounceSortByTime(), GAMECENTER_AnnounceSortByUsername(), MESSAGE_GetAnnounceMatch(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_AnnounceWindow().
Referenced by AnnounceObj().
function INTERFACE_CreateGameCenterCurrentGames ()
References CONNECTION_SendJabber(), GAMECENTER_ClearCurrentGames(), GAMECENTER_CurrentGamesSortByBRating(), GAMECENTER_CurrentGamesSortByCategory(), GAMECENTER_CurrentGamesSortByMoves(), GAMECENTER_CurrentGamesSortByRated(), GAMECENTER_CurrentGamesSortByTime(), GAMECENTER_CurrentGamesSortByWRating(), MESSAGE_GameRoomList(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by CurrentGamesObj().
function INTERFACE_CreateGameCenterMatch ()
References CHALLENGE_ClearChallenges(), GAMECENTER_MatchOfferSortByCategory(), GAMECENTER_MatchOfferSortByInc(), GAMECENTER_MatchOfferSortByPrivate(), GAMECENTER_MatchOfferSortByRated(), GAMECENTER_MatchOfferSortByRating(), GAMECENTER_MatchOfferSortByTime(), GAMECENTER_MatchOfferSortByUsername(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by MatchOfferObj().
function INTERFACE_CreateGameCenterPostpone ()
References GAMECENTER_PostponeSortByCategory(), GAMECENTER_PostponeSortByDate(), GAMECENTER_PostponeSortByInc(), GAMECENTER_PostponeSortByRating(), GAMECENTER_PostponeSortByTime(), GAMECENTER_PostponeSortByUsername(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by PostponeObj().
function INTERFACE_HideAnnounceCenter ()
Referenced by AnnounceObj().
function INTERFACE_HideCurrentGamesCenter ()
Referenced by CurrentGamesObj().
function INTERFACE_HideGameCenter ()
Referenced by GameCenterObj().
function INTERFACE_HideMatchCenter ()
Referenced by MatchOfferObj().
function INTERFACE_HideNoAnnounce ()
function INTERFACE_HideNoCurrentGames ()
Referenced by CurrentGamesObj().
function INTERFACE_HideNoMatch ()
function INTERFACE_HideNoPostpone ()
function INTERFACE_HidePostponeCenter ()
Referenced by PostponeObj().
function INTERFACE_RemoveAnnounce (MatchId)
function INTERFACE_RemoveCurrentGames (CurrentGamesId)
Referenced by CurrentGamesObj().
function INTERFACE_RemoveMatchOffer (MatchId)
Referenced by MatchOfferObj().
function INTERFACE_RemovePostpone (PostponeId)
function INTERFACE_ShowAnnounceCenter (Element)
Referenced by AnnounceObj().
function INTERFACE_ShowCurrentGamesCenter (Element)
Referenced by CurrentGamesObj().
function INTERFACE_ShowGameCenter (Element)
Referenced by GameCenterObj().
function INTERFACE_ShowMatchCenter (Element)
Referenced by MatchOfferObj().
function INTERFACE_ShowNoAnnounce ()
function INTERFACE_ShowNoCurrentGames ()
Referenced by CurrentGamesObj().
function INTERFACE_ShowNoMatch ()
function INTERFACE_ShowNoPostpone ()
function INTERFACE_ShowPostponeCenter (Element)
Referenced by PostponeObj().
function INTERFACE_UpdatePostpone (OponentName, OponentStatus)
References CHALLENGE_SendResumeGame().
function MatchOfferObj ()
References INTERFACE_AddMatchOffer(), INTERFACE_CreateGameCenterMatch(), INTERFACE_HideMatchCenter(), INTERFACE_HideNoMatch(), INTERFACE_RemoveMatchOffer(), INTERFACE_ShowMatchCenter(), and INTERFACE_ShowNoMatch().
Referenced by GameCenterObj().
function PostponeObj ()
References INTERFACE_AddPostpone(), INTERFACE_CreateGameCenterPostpone(), INTERFACE_HideNoPostpone(), INTERFACE_HidePostponeCenter(), INTERFACE_RemovePostpone(), INTERFACE_ShowNoPostpone(), INTERFACE_ShowPostponeCenter(), and INTERFACE_UpdatePostpone().
Referenced by GameCenterObj().