XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/game.js File Reference
/home/www/rubens/webclient/scripts/interface/game.js File Reference
Interface functions that control game.
Functions
function INTERFACE_GameBoardObj (GameID, Player1, Player2, YourColor, PieceSize, Observer)
function INTERFACE_ShowGame ()
Show this game in the interface.
function INTERFACE_HideGame ()
Hide this game in the interface.
function INTERFACE_FinishGame ()
Set game as finished.
function INTERFACE_RemoveGame ()
Remove this game.
function INTERFACE_ObserverMode ()
function INTERFACE_OldGameMode ()
function INTERFACE_ClearBoard ()
Remove all pieces from board.
function INTERFACE_SetBoard (BoardArray)
Clean the board and show new board.
function INTERFACE_InsertPiece (Piece, Line, Col)
Display a piece in specified line and column of the board.
function INTERFACE_RemovePiece (Line, Col)
Remove a piece from the board.
function INTERFACE_UpdateBoard (OldBoard, NewBoard)
Update the board on the screen.
function INTERFACE_UndoMove ()
Undo the last move done by you.
function INTERFACE_SetTurn (Color)
Set and show current player turn.
function INTERFACE_DecreaseTime ()
Decrease players time.
function INTERFACE_StartTimer ()
Start timer.
function INTERFACE_StopTimer ()
Stop timer.
function INTERFACE_UpdateWTime (NewTime)
Update white player time value.
function INTERFACE_UpdateBTime (NewTime)
Update black player time value.
function INTERFACE_SetWTime ()
Show white player time on interface.
function INTERFACE_SetBTime ()
Show black player time on interface.
function INTERFACE_SetWPhoto (Img)
Show white player image.
function INTERFACE_SetBPhoto (Img)
Show black player image.
function INTERFACE_AddMove (NumTurn, Move, ShortMove, WTime, BTime)
Show a new move in Move List.
function INTERFACE_RemoveMove ()
Remove last move in Move List.
Detailed Description
Interface functions that control game.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function INTERFACE_AddMove (NumTurn, Move, ShortMove, WTime, BTime)
Show a new move in Move List.
Parameters:
NumTurn Turn number
Move Move done
ShortMove Move done in short format
WTime White player time when move was done
BTime Black time when move was done
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
References MainData, OLDGAME_GotoBoard(), UTILS_AddListener(), and UTILS_CreateElement().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_ClearBoard ()
Remove all pieces from board.
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_DecreaseTime ()
Decrease players time.
Executed in each second and accordly to game turn color
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
References MainData.
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_FinishGame ()
Set game as finished.
Disable options and drag pieces
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_GameBoardObj (GameID, Player1, Player2, YourColor, PieceSize, Observer)
References INTERFACE_AddMove(), INTERFACE_ClearBoard(), INTERFACE_CreateGame(), INTERFACE_DecreaseTime(), INTERFACE_FindBlock(), INTERFACE_FinishGame(), INTERFACE_HideGame(), INTERFACE_HideLeaveUser(), INTERFACE_HideLoadingMove(), INTERFACE_InsertPiece(), INTERFACE_LastMove(), INTERFACE_ObserverMode(), INTERFACE_OldGameMode(), INTERFACE_RemoveBlockBorder(), INTERFACE_RemoveBlockClass(), INTERFACE_RemoveBlockEvents(), INTERFACE_RemoveGame(), INTERFACE_RemoveMove(), INTERFACE_RemovePiece(), INTERFACE_SetBlockBorder(), INTERFACE_SetBlockClass(), INTERFACE_SetBoard(), INTERFACE_SetBPhoto(), INTERFACE_SetBTime(), INTERFACE_SetTurn(), INTERFACE_SetWPhoto(), INTERFACE_SetWTime(), INTERFACE_ShowGame(), INTERFACE_ShowLeaveUser(), INTERFACE_ShowLoadingMove(), INTERFACE_StartTimer(), INTERFACE_StopTimer(), INTERFACE_UndoMove(), INTERFACE_UpdateBoard(), INTERFACE_UpdateBTime(), INTERFACE_UpdateWTime(), MainData, and SetTurn.
Referenced by GAME_StartGame(), GAME_StartObserverGame(), and OLDGAME_StartOldGame().
function INTERFACE_HideGame ()
Hide this game in the interface.
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_InsertPiece (Piece, Line, Col)
Display a piece in specified line and column of the board.
Parameters:
Piece Piece char
Line Line where is the piece will be place
Col Column where is the piece will be place
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
References INTERFACE_NewPiece(), and UTILS_HorizontalIndex().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_ObserverMode ()
References INTERFACE_CreateMoveList(), and INTERFACE_CreateOldGameTab().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_OldGameMode ()
References INTERFACE_CreateOldGameMoveList(), and INTERFACE_CreateOldGameTab().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_RemoveGame ()
Remove this game.
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
References MainData, UTILS_GetText(), and WINDOW_Alert().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_RemoveMove ()
Remove last move in Move List.
This is should be used when players agree to return one move
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_RemovePiece (Line, Col)
Remove a piece from the board.
Parameters:
Line Line where the piece was placed
Col Column where the piece was placed
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
References UTILS_HorizontalIndex().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetBoard (BoardArray)
Clean the board and show new board.
Parameters:
BoardArray Board in arrays format
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetBPhoto (Img)
Show black player image.
Parameters:
Img Image with type concatenated with iamge in base64
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
References IMAGE_ImageDecode().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetBTime ()
Show black player time on interface.
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetTurn (Color)
Set and show current player turn.
Parameters:
Color is the player color
Returns:
void
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetWPhoto (Img)
Show white player image.
Parameters:
Img Image with type concatenated with iamge in base64
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
References IMAGE_ImageDecode().
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_SetWTime ()
Show white player time on interface.
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_ShowGame ()
Show this game in the interface.
Returns:
true if game is showed with sucess, else false
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_StartTimer ()
Start timer.
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_StopTimer ()
Stop timer.
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_UndoMove ()
Undo the last move done by you.
Returns:
True if sucess or false if game not found
Author:
Rubens Suguimoto and Pedro Rocha
References MainData.
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_UpdateBoard (OldBoard, NewBoard)
Update the board on the screen.
Get diff between old board and new board and update
Parameters:
OldBoard Current Board
NewBoard New board that will be show
Returns:
void
Author:
Rubens and Pedro
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_UpdateBTime (NewTime)
Update black player time value.
Parameters:
NewTime New time to be update
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().
function INTERFACE_UpdateWTime (NewTime)
Update white player time value.
Parameters:
NewTime New time to be update
Returns:
none
Author:
Rubens Suguimoto and Pedro Rocha
Referenced by INTERFACE_GameBoardObj().