XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/interface.js File Reference
/home/www/rubens/webclient/scripts/interface/interface.js File Reference
Control interface DOM objects.
Functions
function INTERFACE_CreateInterface ()
Create all object needed to start game enviroment.
function INTERFACE_ShowInterface (Tree)
Show interface in the user screen.
function INTERFACE_StopInterface ()
Remove start enviroment page.
function INTERFACE_CreateLoadingBox (Id, Text)
function INTERFACE_DisableSelect (e)
Disable element selection.
function INTERFACE_ReEnableSelect ()
Enabla element selection.
function INTERFACE_ShowFullName (Obj, FullName)
Create a hint to show full name.
function INTERFACE_CloseFullName ()
Close hint box created by INTERFACE_ShowFullName function.
Detailed Description
Control interface DOM objects.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function INTERFACE_CloseFullName ()
Close hint box created by INTERFACE_ShowFullName function.
Returns:
none
Author:
Danilo Yorinori
Referenced by INTERFACE_AddAnnounce(), INTERFACE_AddMatchOffer(), INTERFACE_AddPostpone(), INTERFACE_CreateRoomInBar(), and INTERFACE_FocusRoom().
function INTERFACE_CreateInterface ()
Create all object needed to start game enviroment.
Returns:
Start main Div
Author:
Pedro Rocha and Rubens Suguimoto
References INTERFACE_CreateChatList(), INTERFACE_CreateLeft(), INTERFACE_CreateTop(), and UTILS_CreateElement().
Referenced by START_Webclient().
function INTERFACE_CreateLoadingBox (Id, Text)
References UTILS_CreateElement().
Referenced by INTERFACE_CreateContactContent(), INTERFACE_CreateOnlineContent(), INTERFACE_CreateRooms(), and INTERFACE_ShowOldGameWindow().
function INTERFACE_DisableSelect (e)
Disable element selection.
Returns:
False
Author:
Danilo Yorinori
Referenced by INTERFACE_HelpDisplay().
function INTERFACE_ReEnableSelect ()
Enabla element selection.
Returns:
True
Author:
Danilo Yorinori
Referenced by INTERFACE_HelpDisplay().
function INTERFACE_ShowFullName (Obj, FullName)
Create a hint to show full name.
Parameters:
Obj Obj that have name shorted
FullName String to be displayed
Returns:
none
Author:
Danilo Yorinori
References UTILS_CreateElement(), UTILS_GetOffset(), and UTILS_GetParentDiv().
Referenced by INTERFACE_AddAnnounce(), INTERFACE_AddMatchOffer(), INTERFACE_AddPostpone(), INTERFACE_CreateRoomInBar(), and INTERFACE_FocusRoom().
function INTERFACE_ShowInterface (Tree)
Show interface in the user screen.
Parameters:
Tree HTML DOM element
Returns:
none
Author:
Pedro Rocha
Referenced by START_Webclient().
function INTERFACE_StopInterface ()
Remove start enviroment page.
Returns:
none
Author:
Pedro Rocha
Referenced by LOGIN_Disconnected(), and START_Restart().