XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/profile.js File Reference
/home/www/rubens/webclient/scripts/interface/profile.js File Reference
Functions
function INTERFACE_ShowProfileWindow (Profile)
Create elements to profile window content object.
function INTERFACE_ShowProfileConfirmWindow ()
Create confirm profile close window content.
function INTERFACE_ProfileSetUser (Username)
Set profile username.
function INTERFACE_ProfileGetUser ()
Get profile username.
function INTERFACE_ProfileSetUserImg (Img)
Set profile user's image.
function INTERFACE_ProfileSetNick (Nick)
Set nick name.
function INTERFACE_ProfileSetDesc (Desc)
Set description.
function INTERFACE_ProfileGetDesc ()
Get user's description.
function INTERFACE_ProfileSetRatings (Ratings)
Set rating lists.
function INTERFACE_ProfileSetTotalTime (Time)
Set total online time.
function INTERFACE_ProfileSetOnlineTime (Time)
Set online time.
function INTERFACE_ProfileSetTitle (Title)
Set user's level.
function INTERFACE_ProfileSetTitleImg (Group)
Set user's type image.
function INTERFACE_ProfileSetGroup (Group)
Set user's Group.
function INTERFACE_ProfileSetImgType (ImgType)
Set user's profile image type.
function INTERFACE_ProfileGetImgType ()
Get user's profile image type.
function INTERFACE_ProfileSetImg64 (Img64)
Set user's image in base64.
function INTERFACE_ProfileGetImg64 ()
Get profile user's image.
function INTERFACE_ProfileSetClose (Bool)
Set status of close confirm window.
function INTERFACE_ProfileGetClose ()
Get CloseConfirm value.
function INTERFACE_ProfileSetAvailable ()
Set Profile window buttons as available.
function INTERFACE_ProfileSetUnavailable ()
Set Profile window buttons as unavailable.
Function Documentation
function INTERFACE_ProfileGetClose ()
Get CloseConfirm value.
Returns:
Boolean (true is window confirm opened or false is window confirm closed)
See also:
INTERFACE_ProfileSetClose
Author:
Danilo Yorinori
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileGetDesc ()
Get user's description.
Returns:
User's desciption string
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileGetImg64 ()
Get profile user's image.
Returns:
User's image string in base64
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileGetImgType ()
Get user's profile image type.
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileGetUser ()
Get profile username.
Returns:
User's name
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetAvailable ()
Set Profile window buttons as available.
Returns:
none
Author:
Danilo Yorinori
References WINDOW_ProfileImage().
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetClose (Bool)
Set status of close confirm window.
Parameters:
Bool (true is window confirm opened or false is window confirm closed)
Returns:
none
Author:
Danilo Yorinori
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetDesc (Desc)
Set description.
Parameters:
Desc User's description
Returns:
none
Author:
Rubens Suguimoto
References MainData, and UTILS_GetText().
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetGroup (Group)
Set user's Group.
Parameters:
Group User's Group
Returns:
none
Author:
Danilo Yorinori
References UTILS_GetText().
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetImg64 (Img64)
Set user's image in base64.
Parameters:
Img64 Image string in base64
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetImgType (ImgType)
Set user's profile image type.
Parameters:
ImgType Image's type
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetNick (Nick)
Set nick name.
Parameters:
Nick User's nickname
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetOnlineTime (Time)
Set online time.
Parameters:
Time Time seconds
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetRatings (Ratings)
Set rating lists.
Parameters:
Ratings Rating's list
Returns:
none
Author:
Rubens Suguimoto
References UTILS_CreateElement().
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetTitle (Title)
Set user's level.
Parameters:
Title User's level
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetTitleImg (Group)
Set user's type image.
Parameters:
Group User's type
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetTotalTime (Time)
Set total online time.
Parameters:
Time Time seconds
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetUnavailable ()
Set Profile window buttons as unavailable.
Returns:
none
Author:
Danilo Yorinori
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetUser (Username)
Set profile username.
Parameters:
Username User's name
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ProfileSetUserImg (Img)
Set profile user's image.
Returns:
none
Author:
Rubens Suguimoto
References IMAGE_ImageDecode().
Referenced by INTERFACE_ShowProfileWindow().
function INTERFACE_ShowProfileConfirmWindow ()
Create confirm profile close window content.
Returns:
Profile confirm main Div and Buttons Array
See also:
WINDOW_ProfileConfirm();
Author:
Danilo Kiyoshi Simizu Yorinori
References PROFILE_SaveMyProfile(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_ProfileConfirm().
function INTERFACE_ShowProfileWindow (Profile)
Create elements to profile window content object.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Parameters:
Profile Object with profile data
Returns:
Profile main Div and Buttons Array
See also:
WINDOW_Profile();
Author:
Danilo Kiyoshi Simizu Yorinori
References INTERFACE_ProfileGetClose(), INTERFACE_ProfileGetDesc(), INTERFACE_ProfileGetImg64(), INTERFACE_ProfileGetImgType(), INTERFACE_ProfileGetUser(), INTERFACE_ProfileSetAvailable(), INTERFACE_ProfileSetClose(), INTERFACE_ProfileSetDesc(), INTERFACE_ProfileSetGroup(), INTERFACE_ProfileSetImg64(), INTERFACE_ProfileSetImgType(), INTERFACE_ProfileSetNick(), INTERFACE_ProfileSetOnlineTime(), INTERFACE_ProfileSetRatings(), INTERFACE_ProfileSetTitle(), INTERFACE_ProfileSetTitleImg(), INTERFACE_ProfileSetTotalTime(), INTERFACE_ProfileSetUnavailable(), INTERFACE_ProfileSetUser(), INTERFACE_ProfileSetUserImg(), MainData, OLDGAME_OpenOldGameWindow(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_ProfileImage().
Referenced by WINDOW_Profile().