XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/room.js File Reference
/home/www/rubens/webclient/scripts/interface/room.js File Reference
Control rooms interface elements.
Functions
function RoomObj (Roomname)
function INTERFACE_CreateRoom (RoomName)
Create a room HTML DOM elements.
function INTERFACE_ShowRoom ()
function INTERFACE_HideRoom ()
function INTERFACE_RemoveRoom ()
function INTERFACE_FocusRoomInput ()
function INTERFACE_ShowRoomUserList ()
function INTERFACE_HideRoomUserList ()
function INTERFACE_AddMsgInRoom (Username, Msg, Timestamp)
function INTERFACE_AddMsgErrorInRoom (Msg)
function INTERFACE_RefreshOccupantsNumber (RoomName)
function INTERFACE_ShowRoomList (Rooms)
Show room's list in the room menu.
function INTERFACE_HideRoomList ()
Hide room list menu.
function INTERFACE_HideGameRoomList ()
Hide game room list menu.
function INTERFACE_ShowGameRoomList (GameId, PW, PB, GameType)
Add a game room list in the room menu.
function INTERFACE_ChangeRoomListVisibility ()
function INTERFACE_RemoveRoomFromList (Room)
Remove a room from room list.
function INTERFACE_ShowEmoticonList (RName)
Show emoticon list.
function INTERFACE_HideEmoticonList ()
Hide emoticon list.
function INTERFACE_FocusRoom (RoomName)
Give focus to a room in change room bar.
function INTERFACE_CreateRoomInBar (RoomName)
function INTERFACE_CloseRoom (RoomName)
Close the room that are displayed as a secondary room.
function INTERFACE_CreateRooms ()
Create rooms HTML DOM Div element.
function INTERFACE_ShowCreateRoomWindow ()
Create HTML DOM elements to create room window content.
function INTERFACE_ShowCancelRoomWindow ()
Detailed Description
Control rooms interface elements.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function INTERFACE_AddMsgErrorInRoom (Msg)
References UTILS_CreateElement().
Referenced by RoomObj().
function INTERFACE_AddMsgInRoom (Username, Msg, Timestamp)
References UTILS_ConvertChatString().
Referenced by RoomObj().
function INTERFACE_ChangeRoomListVisibility ()
Show or hide list of user's rooms
Returns:
True if visibile or false otherwise
References MainData, ROOM_FocusRoom(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_CreateRooms().
function INTERFACE_CloseRoom (RoomName)
Close the room that are displayed as a secondary room.
Parameters:
RoomName Room's name
Returns:
Room's name
Author:
Pedro Rocha
Referenced by ROOM_RemoveRoom().
function INTERFACE_CreateRoom (RoomName)
Create a room HTML DOM elements.
Parameters:
RoomName Room's name
Returns:
Room main HTML DOM Div, Room messages HTML DOM List, Input text box and Show user HTML DOM span
Author:
Pedro Rocha and Rubens Suguimoto
References INTERFACE_ShowEmoticonList(), MainData, ROOM_ErrorMessageLength(), ROOM_SendMessage(), ROOM_ShowHideUserList(), UTILS_CreateElement(), UTILS_GetText(), and UTILS_ReturnKeyCode().
Referenced by RoomObj().
function INTERFACE_CreateRoomInBar (RoomName)
References INTERFACE_CloseFullName(), INTERFACE_ShowFullName(), MainData, ROOM_ExitRoom(), ROOM_FocusRoom(), UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by ROOM_CreateRoom(), and ROOM_RemoveRoom().
function INTERFACE_CreateRooms ()
Create rooms HTML DOM Div element.
Returns:
Rooms HTML DOM Div element
Author:
Pedro Rocha
References INTERFACE_ChangeRoomListVisibility(), INTERFACE_CreateLoadingBox(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_CreateLeft().
function INTERFACE_FocusRoom (RoomName)
Give focus to a room in change room bar.
Parameters:
RoomName Room's name
Returns:
True or null (if room was not founded)
Author:
Pedro Rocha
References INTERFACE_CloseFullName(), INTERFACE_ShowFullName(), MainData, ROOM_ExitRoom(), ROOM_FocusRoom(), and UTILS_ShortString().
Referenced by ROOM_FocusRoom().
function INTERFACE_FocusRoomInput ()
Referenced by RoomObj().
function INTERFACE_HideEmoticonList ()
Hide emoticon list.
Returns:
True or null (if emoticon div exists)
Author:
Pedro Rocha
Referenced by INTERFACE_ShowEmoticonList().
function INTERFACE_HideGameRoomList ()
Hide game room list menu.
Returns:
True or false (if element list node not founded)
Author:
Ulysses
Referenced by INTERFACE_ShowGameRoomMenu().
function INTERFACE_HideRoom ()
Referenced by RoomObj().
function INTERFACE_HideRoomList ()
Hide room list menu.
Returns:
True or false (if element list node not founded)
Author:
Pedro Rocha
Referenced by INTERFACE_ShowRoomMenu().
function INTERFACE_HideRoomUserList ()
References UTILS_GetText().
Referenced by RoomObj().
function INTERFACE_RefreshOccupantsNumber (RoomName)
References MainData.
Referenced by ROOM_FocusRoom(), ROOM_HandleRoomPresence(), and ROOM_RemoveRoom().
function INTERFACE_RemoveRoom ()
Referenced by RoomObj().
function INTERFACE_RemoveRoomFromList (Room)
Remove a room from room list.
Parameters:
Room Room name
Returns:
none
Author:
Rubens
Referenced by ROOM_RemoveRoom().
function INTERFACE_ShowCancelRoomWindow ()
Create elements to cancel room creation window and return divs and array of buttons
TODO -> ACTIVE THIS FUNCTION
Returns:
Div, Array
See also:
WINDOW_CancelRoom();
Author:
Danilo Kiyoshi Simizu Yorinori
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_CancelRoom().
function INTERFACE_ShowCreateRoomWindow ()
Create HTML DOM elements to create room window content.
Returns:
Return divs and array of buttons
See also:
WINDOW_CreateRoom();
Author:
Danilo Kiyoshi Simizu Yorinori
References CONNECTION_SendJabber(), MainData, MESSAGE_Presence(), UTILS_CreateElement(), UTILS_GetText(), UTILS_ReturnKeyCode(), and WINDOW_Alert().
Referenced by WINDOW_CreateRoom().
function INTERFACE_ShowEmoticonList (RName)
Show emoticon list.
Parameters:
RName Room's name
Returns:
none
Author:
Pedro Rocha
References INTERFACE_HideEmoticonList(), MainData, UTILS_AddListener(), UTILS_CreateElement(), and UTILS_RemoveListener().
Referenced by INTERFACE_CreateRoom().
function INTERFACE_ShowGameRoomList (GameId, PW, PB, GameType)
Add a game room list in the room menu.
Parameters:
GameId Current game identification field
PW White player object
PB Black player object
GameType Game category
Returns:
True or false (if element list node not founded)
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONNECTION_SendJabber(), GAME_StartGame(), GAME_StartObserverGame(), MainData, MESSAGE_Presence(), UTILS_Capitalize(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_Alert().
function INTERFACE_ShowRoom ()
Referenced by RoomObj().
function INTERFACE_ShowRoomList (Rooms)
Show room's list in the room menu.
Parameters:
Rooms Array of room names
Returns:
none
Author:
Pedro Rocha
References ROOM_EnterRoom(), and UTILS_CreateElement().
Referenced by ROOM_HandleRoomList().
function INTERFACE_ShowRoomUserList ()
References UTILS_GetText().
Referenced by RoomObj().
function RoomObj (Roomname)
References INTERFACE_AddMsgErrorInRoom(), INTERFACE_AddMsgInRoom(), INTERFACE_CreateRoom(), INTERFACE_FocusRoomInput(), INTERFACE_HideRoom(), INTERFACE_HideRoomUserList(), INTERFACE_RemoveRoom(), INTERFACE_ShowRoom(), INTERFACE_ShowRoomUserList(), ROOM_SortUsersByNick(), ROOM_SortUsersByRating(), and UserListObj().
Referenced by DATA_AddRoom(), DATA_SetCurrentRoom(), and ROOM_CreateRoom().