XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/admin.js File Reference
/home/www/rubens/webclient/scripts/interface/admin.js File Reference
Create window content to show admin options.
Functions
function INTERFACE_UnbanUserWindow ()
Create temporary unban window content.
function INTERFACE_BanUserWindow (Username)
Create temporary ban window content.
function INTERFACE_KickUserWindow (Username)
Create temporary kick window content.
function INTERFACE_CreateAdminWindow ()
Create admin window with administrative tools.
function INTERFACE_AddBannedUser (Username)
Add a banned user in banned list.
Detailed Description
Create window content to show admin options.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Create window contents to admins for ban, kick, unban, etc.
Function Documentation
function INTERFACE_AddBannedUser (Username)
Add a banned user in banned list.
Returns:
True if added or false if list not founded
Author:
Rubens Suguimoto
Deprecated:
See also:
WINDOW_AdminWindow
References ADMIN_UnbanUser(), and UTILS_CreateElement().
function INTERFACE_BanUserWindow (Username)
Create temporary ban window content.
Create temporary ban user window content with a input reason.
Parameters:
Username User's name
Returns:
Content div, Buttons elements and Elements will receive event
Author:
Rubens Suguimoto
See also:
WINDOW_BanUser
References ADMIN_BanUser(), UTILS_AddListener(), and UTILS_CreateElement().
Referenced by WINDOW_BanUser().
function INTERFACE_CreateAdminWindow ()
Create admin window with administrative tools.
Create window content with administrative tools.
Returns:
Content div and Buttons elements
Author:
Rubens Suguimoto
See also:
WINDOW_AdminWindow
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_AdminWindow().
function INTERFACE_KickUserWindow (Username)
Create temporary kick window content.
Create temporary kick user window content with a input reason.
Parameters:
Username User's name
Returns:
Content div, Buttons elements and Elements will receive event
Author:
Rubens Suguimoto
See also:
WINDOW_BanUser
References ADMIN_KickUser(), UTILS_AddListener(), and UTILS_CreateElement().
Referenced by WINDOW_KickUser().
function INTERFACE_UnbanUserWindow ()
Create temporary unban window content.
Create temporary unban window content with a input user name who will be unbaned.
Returns:
Content div, Buttons elements and Elements will receive event
Author:
Rubens Suguimoto
See also:
WINDOW_UnbanUser
References ADMIN_UnbanUser(), UTILS_AddListener(), and UTILS_CreateElement().
Referenced by WINDOW_UnbanUser().