XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/load.js File Reference
/home/www/rubens/webclient/scripts/interface/load.js File Reference
Functions
function LoadObj ()
function INTERFACE_StartLoad ()
Create load box HTML DOM elements.
function INTERFACE_ShowLoad ()
Show load box.
function INTERFACE_HideLoading ()
Hide load box.
function INTERFACE_RemoveLoad ()
Remove load box.
function INTERFACE_SetLabel (Str)
Set load file text.
function LoadingBar ()
function INTERFACE_CreateBar (Id)
function INTERFACE_AddValue (Num)
function INTERFACE_SubValue (Num)
function INTERFACE_ShowLoadingBar (Element)
function INTERFACE_HideLoadingBar ()
function INTERFACE_RemoveLoadingBar ()
Function Documentation
function INTERFACE_AddValue (Num)
Referenced by LoadingBar().
function INTERFACE_CreateBar (Id)
Referenced by LoadingBar().
function INTERFACE_HideLoading ()
Hide load box.
Returns:
none
Author:
Rubens Suguimoto
Referenced by LoadObj().
function INTERFACE_HideLoadingBar ()
Referenced by LoadingBar().
function INTERFACE_RemoveLoad ()
Remove load box.
Returns:
none
Author:
Rubens Suguimoto
Referenced by LoadObj().
function INTERFACE_RemoveLoadingBar ()
Referenced by LoadingBar().
function INTERFACE_SetLabel (Str)
Set load file text.
Returns:
none
Author:
Rubens Suguimoto
Referenced by LoadObj().
function INTERFACE_ShowLoad ()
Show load box.
Returns:
none
Author:
Rubens Suguimoto
Referenced by LoadObj().
function INTERFACE_ShowLoadingBar (Element)
Referenced by LoadingBar().
function INTERFACE_StartLoad ()
Create load box HTML DOM elements.
Returns:
Load main HTML DOM Div, load file text HTML DOM P and load bar HTML DOM Div element
Author:
Pedro Rocha and Rubens Suguimoto
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by LoadObj().
function INTERFACE_SubValue (Num)
Referenced by LoadingBar().
function LoadingBar ()
References INTERFACE_AddValue(), INTERFACE_CreateBar(), INTERFACE_HideLoadingBar(), INTERFACE_RemoveLoadingBar(), INTERFACE_ShowLoadingBar(), and INTERFACE_SubValue().
Referenced by LoadObj().
function LoadObj ()
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
References INTERFACE_HideLoading(), INTERFACE_RemoveLoad(), INTERFACE_SetLabel(), INTERFACE_ShowLoad(), INTERFACE_StartLoad(), and LoadingBar().
Referenced by DATA(), DATA_GetLoadObj(), DATA_SetLoadObj(), LOAD_AppendFiles(), LOAD_EndFile(), LOAD_EndLoad(), LOAD_NextFile(), and LOAD_StartLoad().