XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/user.js File Reference
/home/www/rubens/webclient/scripts/interface/user.js File Reference
Class defition for user list object and some functions assign.
Functions
function UserListObj (Element)
function INTERFACE_ShowUserList ()
Show user list div.
function INTERFACE_HideUserList ()
Hide user list div.
function INTERFACE_AddUser (Username, Status, Rating, Type)
Add one user in list.
function INTERFACE_RemoveUser (Username)
Remove user from list.
function INTERFACE_UpdateUser (Username, NewStatus, Rating, NewType)
Update user status and rating in list.
function INTERFACE_FindUser (Username)
Find user in user list.
function INTERFACE_SetSortUserFunction (Func)
Set sort list by nick function to list.
function INTERFACE_SetSortRatingFunction (Func)
Set sort list by rating function to list.
function INTERFACE_HideSort ()
Hide sort options.
function INTERFACE_ShowSort ()
Show sort options.
function INTERFACE_HideList ()
Hide user list element.
function INTERFACE_ShowList ()
Show user list element.
function INTERFACE_FocusNick ()
Focus sort nick button element.
function INTERFACE_BlurNick ()
Blur sort nick button element.
function INTERFACE_FocusRating ()
Focus sort rating button element.
function INTERFACE_BlurRating ()
Blur sort rating button element.
function INTERFACE_CreateUserList (Element)
Create user list in interface.
function INTERFACE_CreateUser (Username, Status, Rating, Type)
Create a user item and return it.
function INTERFACE_ShowUserMenu (Obj, Options)
Show user menu when click over user list item.
function INTERFACE_HideUserMenu ()
Hide user menu.
function INTERFACE_CreateUserElement (Obj)
Create elements of an user.
function INTERFACE_ShowUserFullName (Obj, UserName)
Create a hint showing complete name.
function INTERFACE_CloseUserFullName ()
function INTERFACE_ShowSearchUserWindow ()
function INTERFACE_SearchUserSetResult (Result)
function INTERFACE_SortSearchUserByNick ()
Change sort order and display result list order by nick.
function INTERFACE_SortSearchUserByName ()
Change sort order and display result list order by name.
Detailed Description
Class defition for user list object and some functions assign.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Create a user list object used in rooms, contact list and online list
Function Documentation
function INTERFACE_AddUser (Username, Status, Rating, Type)
Add one user in list.
Add a user in user list creating a tr element and insert it in (this.users) array.
Parameters:
Username User's name
Status User's status
Rating User's rating that will be show
Type User's type (teacher, admin, robot, etc.)
Returns:
none
Author:
Rubens Suguimoto
See also:
INTERFACE_CreateUser
References INTERFACE_CreateUser().
Referenced by UserListObj().
function INTERFACE_BlurNick ()
Blur sort nick button element.
Show user list in interface
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_BlurRating ()
Blur sort rating button element.
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_CloseUserFullName ()
Referenced by INTERFACE_CreateUser(), INTERFACE_CreateUserBox(), and INTERFACE_CreateUserElement().
function INTERFACE_CreateUser (Username, Status, Rating, Type)
Create a user item and return it.
Create a user tr element, contais username, status/type and rating, and return this element.
Parameters:
Username The user's name
Status The new user's status
Rating The user's rating
Type The new user's type
Author:
Rubens Suguimoto
Returns:
Tr HTML element with username, status/type and rating
References CONTACT_ShowUserMenu(), INTERFACE_CloseUserFullName(), INTERFACE_ShowUserFullName(), UTILS_CreateElement(), and UTILS_ShortString().
Referenced by INTERFACE_AddUser().
function INTERFACE_CreateUserElement (Obj)
Create elements of an user.
Parameters:
Obj User Object
Returns:
Tr HTML element
Author:
Danilo Kiyoshi Simizu Yorinori
References CONTACT_ShowUserMenu(), INTERFACE_CloseUserFullName(), INTERFACE_ShowUserFullName(), UTILS_CreateElement(), and UTILS_ShortString().
Referenced by INTERFACE_SearchUserSetResult(), INTERFACE_SortSearchUserByName(), and INTERFACE_SortSearchUserByNick().
function INTERFACE_CreateUserList (Element)
Create user list in interface.
Create user list HTML, and return div, list parent, sort span, sort rating option;
Parameters:
Element Parent node of list main div
Author:
Rubens Suguimoto
Returns:
Object that contains list main div, user list, sort span and sort rating option
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by UserListObj().
function INTERFACE_FindUser (Username)
Find user in user list.
Search user in array (this.users);
Parameters:
Username User's name
Author:
Rubens Suguimoto
Returns:
null if user is not founded in list, else tr elemente if user item;
Referenced by UserListObj().
function INTERFACE_FocusNick ()
Focus sort nick button element.
Show user list in interface
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_FocusRating ()
Focus sort rating button element.
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_HideList ()
Hide user list element.
Hide user list in interface
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_HideSort ()
Hide sort options.
Hide sort span and option
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_HideUserList ()
Hide user list div.
Hide user list div changing element style display to none.
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_HideUserMenu ()
Hide user menu.
Remove user menu from interface
Returns:
none
Author:
Pedro Rocha
Referenced by CONTACT_ShowUserMenu().
function INTERFACE_RemoveUser (Username)
Remove user from list.
Remove a user from user list and remove from array.
Parameters:
Username User's name
Author:
Rubens Suguimoto
Returns:
false - User is not founded in list, true otherwise
Referenced by UserListObj().
function INTERFACE_SearchUserSetResult (Result)
References INTERFACE_CreateUserElement(), MainData, and UTILS_GetText().
function INTERFACE_SetSortRatingFunction (Func)
Set sort list by rating function to list.
Set sort by rating function when click in sort option
Parameters:
Func Function that contais sort instructions
Returns:
none
Author:
Rubens Suguimoto
References UTILS_AddListener().
Referenced by UserListObj().
function INTERFACE_SetSortUserFunction (Func)
Set sort list by nick function to list.
Set sort by nick function when click in sort span
Parameters:
Func Function that contais sort instructions
Returns:
none
Author:
Rubens Suguimoto
References UTILS_AddListener().
Referenced by UserListObj().
function INTERFACE_ShowList ()
Show user list element.
Show user list in interface
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_ShowSearchUserWindow ()
References UTILS_AddListener(), UTILS_Capitalize(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_SearchUser().
function INTERFACE_ShowSort ()
Show sort options.
Show sort span and option
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_ShowUserFullName (Obj, UserName)
Create a hint showing complete name.
Create a hint showing complete name of an user whose nick was shorted to fit in interface
Parameters:
Obj HTML element Object
UserName User's name string
Author:
Danilo Yorinori
References MainData, UTILS_CreateElement(), UTILS_GetOffset(), and UTILS_GetParentDiv().
Referenced by INTERFACE_CreateUser(), INTERFACE_CreateUserBox(), and INTERFACE_CreateUserElement().
function INTERFACE_ShowUserList ()
Show user list div.
Show user list div changing element style display to block.
Returns:
none
Author:
Rubens Suguimoto
Referenced by UserListObj().
function INTERFACE_ShowUserMenu (Obj, Options)
Show user menu when click over user list item.
Create a menu and show options to challenge, view profile, add/remove contact, admin options, etc.
Parameters:
Obj User list item
Options Array with user menu options;
Returns:
none
Author:
Pedro Rocha
References MainData, UTILS_CreateElement(), UTILS_GetOffset(), UTILS_GetParentDiv(), and UTILS_GetText().
Referenced by CONTACT_ShowUserMenu().
function INTERFACE_SortSearchUserByName ()
Change sort order and display result list order by name.
Returns:
none
Author:
Danilo Yorinori
References INTERFACE_CreateUserElement(), and MainData.
function INTERFACE_SortSearchUserByNick ()
Change sort order and display result list order by nick.
Returns:
none
Author:
Danilo Yorinori
References INTERFACE_CreateUserElement(), and MainData.
function INTERFACE_UpdateUser (Username, NewStatus, Rating, NewType)
Update user status and rating in list.
Update user status and rating in user list. Find the user and set his type status and, if exists rating, update rating;
Parameters:
Username User's name
NewStatus New user's status
Rating User's rating
NewType New user's type
Author:
Rubens Suguimoto
Returns:
False if user was not founded in list, else True
Referenced by UserListObj().
function UserListObj (Element)
References INTERFACE_AddUser(), INTERFACE_BlurNick(), INTERFACE_BlurRating(), INTERFACE_CreateUserList(), INTERFACE_FindUser(), INTERFACE_FocusNick(), INTERFACE_FocusRating(), INTERFACE_HideList(), INTERFACE_HideSort(), INTERFACE_HideUserList(), INTERFACE_RemoveUser(), INTERFACE_SetSortRatingFunction(), INTERFACE_SetSortUserFunction(), INTERFACE_ShowList(), INTERFACE_ShowSort(), INTERFACE_ShowUserList(), and INTERFACE_UpdateUser().
Referenced by ContactObj(), ContactOnlineObj(), INTERFACE_AddContactGroup(), and RoomObj().