XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/oldgame.js File Reference
/home/www/rubens/webclient/scripts/interface/oldgame.js File Reference
Contains all function to create and manage oldgame elements.
Functions
function INTERFACE_ShowOldGameWindow (Id)
Create elements of search old games window content object.
function INTERFACE_Player1Input (User)
function INTERFACE_Player2Input (User)
function INTERFACE_Color (Color)
function INTERFACE_FromInput (From)
function INTERFACE_ToInput (To)
function INTERFACE_OldGameSetResult (Id, GameList, More)
Display result of a old game search.
function INTERFACE_OldGameSetTable (Id, GameList, More)
Set result table of old games search.
function INTERFACE_SetPrevButton (Node)
Set function associated to previous button.
function INTERFACE_SetNextButton (Node)
Set function associated to next button.
function INTERFACE_SetSearchButton (Node)
Set function associated to search button.
function INTERFACE_AddOldGameResult (White, Black, Date, GameType, WinType, Id)
Add a old games in oldgame search list.
function INTERFACE_ShowOldgameLoading ()
Show loading search old game message.
function INTERFACE_HideOldgameLoading ()
Hide loading search old game message.
Detailed Description
Contains all function to create and manage oldgame elements.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function INTERFACE_AddOldGameResult (White, Black, Date, GameType, WinType, Id)
Add a old games in oldgame search list.
Parameters:
White White player
Black Black player
Date Game date and time
GameType Game category
WinType Win type
Id Oldgame identification number
Returns:
Tr HTML DOM element with oldgame information
See also:
WINDOW_SetResult();
Author:
Danilo Kiyoshi Simizu Yorinori
References CONNECTION_SendJabber(), MainData, MESSAGE_FetchOldGame(), UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_Alert().
Referenced by INTERFACE_OldGameSetTable().
function INTERFACE_Color (Color)
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_FromInput (From)
References UTILS_ConvertTimeStamp().
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_HideOldgameLoading ()
Hide loading search old game message.
return none
Author:
Rubens Suguimoto
Referenced by OLDGAME_HandleSearchOldGame().
function INTERFACE_OldGameSetResult (Id, GameList, More)
Display result of a old game search.
Parameters:
Id Window content identification name
GameList Array of old games
More More flag to check if exist more oldgames to search
Returns:
True
See also:
OLDGAME_HandleSearchOldGame();
Author:
Danilo Kiyoshi Simizu Yorinori
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_OldGameSetTable (Id, GameList, More)
Set result table of old games search.
Parameters:
Id Window content identification name
GameList Array of old games
More More flag to check if exist more oldgames to search
Returns:
True
See also:
WINDOW_SetResult();
Author:
Danilo Kiyoshi Simizu Yorinori
References INTERFACE_AddOldGameResult(), MainData, OLDGAME_CloseWindow(), UTILS_BreakString(), UTILS_GetParentDiv(), and WINDOW_RemoveWindow().
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_Player1Input (User)
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_Player2Input (User)
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_SetNextButton (Node)
Set function associated to next button.
Parameters:
Node Oldgame object
Returns:
none
Author:
Danilo Kiyoshi Simizu Yorinori
References CONNECTION_SendJabber(), MESSAGE_GetOldGames(), and UTILS_AddListener().
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_SetPrevButton (Node)
Set function associated to previous button.
Parameters:
Node Oldgame object
Returns:
none
Author:
Danilo Kiyoshi Simizu Yorinori
References CONNECTION_SendJabber(), MESSAGE_GetOldGames(), and UTILS_AddListener().
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_SetSearchButton (Node)
Set function associated to search button.
Parameters:
Node Oldgame object
Returns:
none
Author:
Danilo Kiyoshi Simizu Yorinori
References CONNECTION_SendJabber(), INTERFACE_ShowOldgameLoading(), MESSAGE_GetOldGames(), UTILS_AddListener(), UTILS_ConvertSearchDate(), UTILS_GetText(), and WINDOW_Alert().
Referenced by INTERFACE_ShowOldGameWindow().
function INTERFACE_ShowOldgameLoading ()
Show loading search old game message.
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_SetSearchButton().
function INTERFACE_ShowOldGameWindow (Id)
Create elements of search old games window content object.
Parameters:
Id Window content identification name
Returns:
Oldgame window content Div and Buttons array
See also:
WINDOW_OpeOldGameWindow();
Author:
Danilo Kiyoshi Simizu Yorinori
References INTERFACE_Color(), INTERFACE_CreateLoadingBox(), INTERFACE_FromInput(), INTERFACE_OldGameSetResult(), INTERFACE_OldGameSetTable(), INTERFACE_Player1Input(), INTERFACE_Player2Input(), INTERFACE_SetNextButton(), INTERFACE_SetPrevButton(), INTERFACE_SetSearchButton(), INTERFACE_ToInput(), MainData, UTILS_AddListener(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_OldGame().
function INTERFACE_ToInput (To)
References UTILS_ConvertTimeStamp().
Referenced by INTERFACE_ShowOldGameWindow().