XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/login.js File Reference
/home/www/rubens/webclient/scripts/interface/login.js File Reference
Shows login screen to user.
Functions
function INTERFACE_StartLogin (Lang)
Create login page elements and show to user.
function INTERFACE_EndLogin ()
Remove login screen.
function INTERFACE_CreateLanguage ()
Remove login screen.
function INTERFACE_CreateLangItem (Lang, Name)
Create language links.
function INTERFACE_LoginVerticalAlignMiddle ()
Align login main div in vertical middle.
function INTERFACE_LoginDisableInput ()
Disable input fields.
function INTERFACE_LoginEnableInput ()
Enable input fields.
function INTERFACE_ClearError ()
Remove error messages text.
function INTERFACE_ShowLoginMessage (Msg)
Show authentication login status message.
function INTERFACE_HideLoginMessage ()
Hide authentication login status message.
function INTERFACE_ShowErrorMessage (Msg)
Show error messages.
function INTERFACE_HideErrorMessage ()
Hide error message.
Detailed Description
Shows login screen to user.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function INTERFACE_ClearError ()
Remove error messages text.
Returns:
none
Author:
Rubens Suguimoto
Referenced by LOGIN_Login().
function INTERFACE_CreateLangItem (Lang, Name)
Create language links.
Parameters:
Lang Language (i.e.: en_US, pt_BR, zh_CN,...)
Name Language word
Returns:
HTML DOM List element with languages
References START_ChangeLanguage(), UTILS_Capitalize(), and UTILS_CreateElement().
Referenced by INTERFACE_CreateLanguage().
function INTERFACE_CreateLanguage ()
Remove login screen.
Returns:
Language HTML DOM Div element with languages tag
References INTERFACE_CreateLangItem(), UTILS_CreateElement(), UTILS_GetNodeText(), and UTILS_OpenXMLFile().
Referenced by INTERFACE_StartLogin().
function INTERFACE_EndLogin ()
Remove login screen.
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
Referenced by LOGIN_EndLogin(), and START_ChangeLanguage().
function INTERFACE_HideErrorMessage ()
Hide error message.
Returns:
none
Author:
Rubens Suguimoto
function INTERFACE_HideLoginMessage ()
Hide authentication login status message.
Returns:
none
Author:
Rubens Suguimoto
Referenced by LOGIN_LoginFailed().
function INTERFACE_LoginDisableInput ()
Disable input fields.
Returns:
none
Author:
Rubens Suguimoto
Referenced by LOGIN_Login().
function INTERFACE_LoginEnableInput ()
Enable input fields.
Returns:
none
Author:
Rubens Suguimoto
Referenced by LOGIN_LoginFailed().
function INTERFACE_LoginVerticalAlignMiddle ()
Align login main div in vertical middle.
Returns:
none
Author:
Rubens Suguimoto
Referenced by INTERFACE_StartLogin().
function INTERFACE_ShowErrorMessage (Msg)
Show error messages.
Returns:
Msg Login error message to show
Author:
Rubens Suguimoto
Referenced by LOGIN_LoginFailed().
function INTERFACE_ShowLoginMessage (Msg)
Show authentication login status message.
Parameters:
Msg Login status message to show
Returns:
none
Author:
Rubens Suguimoto
Referenced by LOGIN_LoginMsg().
function INTERFACE_StartLogin (Lang)
Create login page elements and show to user.
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References INTERFACE_CreateLanguage(), INTERFACE_LoginVerticalAlignMiddle(), LOGIN_Login(), MainData, UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetText(), UTILS_ReadCookie(), and UTILS_ReturnEvent().
Referenced by START_ChangeLanguage(), and START_StartPage().