XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/challenge.js File Reference
/home/www/rubens/webclient/scripts/interface/challenge.js File Reference
Functions
function INTERFACE_ShowChallengeWindow (Oponent, RatingObj, GameParameters, Rated, MatchId)
Create elements to challenge invite or challenge offer.
function INTERFACE_HideChallengeList ()
Hide challenge list menu.
Function Documentation
function INTERFACE_HideChallengeList ()
Hide challenge list menu.
Returns:
True if hide or false (if challenge list not founded)
Author:
Ulysses Bomfim
Deprecated:
function INTERFACE_ShowChallengeWindow (Oponent, RatingObj, GameParameters, Rated, MatchId)
Create elements to challenge invite or challenge offer.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Parameters:
Oponent Oponent's nickname
RatingObj Rating object with types and respective value
GameParameters Object that contains the game parameters of a received challenge
MatchId Id of Match
Rated Rated game flag
Returns:
Challenge window content and Array with buttons
See also:
WINDOW_Challenge();
Author:
Danilo Kiyoshi Simizu Yorinori
References CHALLENGE_AcceptChallenge(), CHALLENGE_SendChallenge(), CHALLENGE_SendReChallenge(), MainData, UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_Challenge().