XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/contact.js File Reference
/home/www/rubens/webclient/scripts/interface/contact.js File Reference
Control interface contact list.
Functions
function ContactObj ()
function INTERFACE_AddContactGroup (GroupName)
function INTERFACE_CreateGroup (GroupName)
function INTERFACE_RemoveContactGroup (GroupName)
function INTERFACE_FindContactGroup (GroupName)
function INTERFACE_GetContactGroup (GroupName)
function INTERFACE_FindContactUserGroup (UserName)
function INTERFACE_AddContactUser (GroupName, UserName, Status, Rating, Type)
function INTERFACE_RemoveContactUser (UserName)
function INTERFACE_UpdateContactUser (UserName, Status, Rating, Type)
function INTERFACE_ShowContactList ()
function INTERFACE_HideContactList ()
function INTERFACE_ShowContactLoading ()
function INTERFACE_HideContactLoading ()
function ContactOnlineObj ()
function INTERFACE_ShowOnlineList ()
function INTERFACE_HideOnlineList ()
function INTERFACE_ChangeGroupVisibility (Obj, Id)
Show or hide contact groups.
function INTERFACE_CreateContact ()
Create contact and online HTML DOM div.
function INTERFACE_CreateContactContent ()
function INTERFACE_CreateOnlineContent ()
Create contact online list.
function INTERFACE_RefreshContactOnlineNumber ()
Detailed Description
Control interface contact list.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function ContactObj ()
References CONTACT_SortUsersByNick(), CONTACT_SortUsersByRating(), INTERFACE_AddContactGroup(), INTERFACE_AddContactUser(), INTERFACE_CreateContactContent(), INTERFACE_FindContactGroup(), INTERFACE_FindContactUserGroup(), INTERFACE_GetContactGroup(), INTERFACE_HideContactList(), INTERFACE_HideContactLoading(), INTERFACE_RemoveContactGroup(), INTERFACE_RemoveContactUser(), INTERFACE_ShowContactList(), INTERFACE_ShowContactLoading(), INTERFACE_UpdateContactUser(), and UserListObj().
Referenced by CONTACT_AddUser(), CONTACT_InviteUser(), CONTACT_LoadUserContactList(), CONTACT_ReceiveUnsubscribed(), CONTACT_RemoveUser(), CONTACT_SetUserRating(), CONTACT_SetUserStatus(), CONTACT_SetUserType(), CONTACT_SortUsersByNick(), CONTACT_SortUsersByRating(), CONTACT_StartContactList(), and INTERFACE_CreateContact().
function ContactOnlineObj ()
References INTERFACE_CreateOnlineContent(), INTERFACE_HideContactLoading(), INTERFACE_HideOnlineList(), INTERFACE_ShowContactLoading(), INTERFACE_ShowOnlineList(), ONLINE_SortUserByNick(), ONLINE_SortUserByRating(), and UserListObj().
Referenced by ONLINE_StartOnlineList().
function INTERFACE_AddContactGroup (GroupName)
References INTERFACE_CreateGroup(), and UserListObj().
Referenced by ContactObj().
function INTERFACE_AddContactUser (GroupName, UserName, Status, Rating, Type)
Referenced by ContactObj().
function INTERFACE_ChangeGroupVisibility (Obj, Id)
Show or hide contact groups.
Parameters:
Obj HTML DOM element
Id Group identification field
Returns:
True or False (if group not founded)
Author:
Rubens Suguimoto
function INTERFACE_CreateContact ()
Create contact and online HTML DOM div.
Returns:
HTML DOM Div
Author:
Rubens Suguimoto
References ContactObj(), MainData, UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_CreateLeft().
function INTERFACE_CreateContactContent ()
References INTERFACE_CreateLoadingBox(), UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_SearchUser().
Referenced by ContactObj().
function INTERFACE_CreateGroup (GroupName)
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_AddContactGroup().
function INTERFACE_CreateOnlineContent ()
Create contact online list.
Returns:
Contact online Div and Loading element
Author:
Rubens Suguimoto
References INTERFACE_CreateLoadingBox(), UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetText(), and WINDOW_SearchUser().
Referenced by ContactOnlineObj().
function INTERFACE_FindContactGroup (GroupName)
Referenced by ContactObj().
function INTERFACE_FindContactUserGroup (UserName)
Referenced by ContactObj().
function INTERFACE_GetContactGroup (GroupName)
Referenced by ContactObj().
function INTERFACE_HideContactList ()
Referenced by ContactObj().
function INTERFACE_HideContactLoading ()
Referenced by ContactObj(), and ContactOnlineObj().
function INTERFACE_HideOnlineList ()
Referenced by ContactOnlineObj().
function INTERFACE_RefreshContactOnlineNumber ()
References MainData.
Referenced by CONTACT_SetUserStatus().
function INTERFACE_RemoveContactGroup (GroupName)
Referenced by ContactObj().
function INTERFACE_RemoveContactUser (UserName)
Referenced by ContactObj().
function INTERFACE_ShowContactList ()
Referenced by ContactObj().
function INTERFACE_ShowContactLoading ()
Referenced by ContactObj(), and ContactOnlineObj().
function INTERFACE_ShowOnlineList ()
Referenced by ContactOnlineObj().
function INTERFACE_UpdateContactUser (UserName, Status, Rating, Type)
Referenced by ContactObj().