XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/announce.js File Reference
/home/www/rubens/webclient/scripts/interface/announce.js File Reference
Functions
function INTERFACE_AnnounceWindow ()
Create elements to announce a match window content.
Function Documentation
function INTERFACE_AnnounceWindow ()
Create elements to announce a match window content.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Returns:
Div content for announce window and Buttons elements
Author:
Danilo Kiyoshi Simizu Yorinori
References ANNOUNCE_ClearAnnounce(), ANNOUNCE_GetAnnounceGames(), ANNOUNCE_SendAnnounce(), MainData, UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_AnnounceWindow().