XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/contact/invite.js File Reference
/home/www/rubens/webclient/scripts/contact/invite.js File Reference
Contais all functions to add a user in your contact list.
Functions
function CONTACT_InviteUser (Username)
Send a invite message to 'Username'.
function CONTACT_SendRemoveUser (Username)
Send a message to remove 'Username'.
function CONTACT_ReceiveSubscribe (Username)
Handle subscribe message.
function CONTACT_ReceiveSubscribed (Username)
Handle subscribed message.
function CONTACT_ReceiveUnsubscribed (Username)
Handle unsubscribed message.
Detailed Description
Contais all functions to add a user in your contact list.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function CONTACT_InviteUser (Username)
Send a invite message to 'Username'.
Parameters:
Username User's name
Returns:
none
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONNECTION_SendJabber(), CONTACT_AddUser(), ContactObj(), MainData, and MESSAGE_Invite().
Referenced by CONTACT_ShowUserMenu().
function CONTACT_ReceiveSubscribe (Username)
Handle subscribe message.
Parameters:
Username User's name
Returns:
Empty string
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONNECTION_SendJabber(), CONTACT_AddUser(), MainData, MESSAGE_Invite(), MESSAGE_InviteAccept(), MESSAGE_InviteDeny(), UTILS_Capitalize(), UTILS_GetText(), and WINDOW_Confirm().
Referenced by CONTACT_HandleUserPresence().
function CONTACT_ReceiveSubscribed (Username)
Handle subscribed message.
Parameters:
Username User's name
Returns:
XMPP message
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONTACT_AddUser(), MainData, and MESSAGE_Info().
Referenced by CONTACT_HandleUserPresence().
function CONTACT_ReceiveUnsubscribed (Username)
Handle unsubscribed message.
Parameters:
Username User's name
Returns:
XMPP message
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONTACT_SetUserStatus(), ContactObj(), MainData, and MESSAGE_RemoveContact().
Referenced by CONTACT_HandleUserPresence().
function CONTACT_SendRemoveUser (Username)
Send a message to remove 'Username'.
Parameters:
Username User's name
Returns:
none
Author:
Ulysses Bomfim and Rubens Suguimoto
References CONNECTION_SendJabber(), and MESSAGE_RemoveContact().
Referenced by CONTACT_ShowUserMenu().