XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/left.js File Reference
/home/www/rubens/webclient/scripts/interface/left.js File Reference
Create elements of the left side of game enviromemnt.
Functions
function INTERFACE_CreateLeft ()
function INTERFACE_CreateUserBox ()
Create user box (left side of the screen).
function INTERFACE_SetUserImage (Img)
Change user's image.
Detailed Description
Create elements of the left side of game enviromemnt.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function INTERFACE_CreateLeft ()
References INTERFACE_CreateContact(), INTERFACE_CreateRooms(), INTERFACE_CreateUserBox(), and UTILS_CreateElement().
Referenced by INTERFACE_CreateInterface().
function INTERFACE_CreateUserBox ()
Create user box (left side of the screen).
Returns:
User HTML DOM Div element
Author:
Pedro Rocha and Rubens Suguimoto
References CONTACT_ChangeStatus(), INTERFACE_CloseUserFullName(), INTERFACE_ShowUserFullName(), MainData, PROFILE_StartProfile(), UTILS_AddListener(), UTILS_Capitalize(), UTILS_CreateElement(), UTILS_GetText(), and UTILS_ShortString().
Referenced by INTERFACE_CreateLeft().
function INTERFACE_SetUserImage (Img)
Change user's image.
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References IMAGE_ImageDecode().
Referenced by PROFILE_HandleVCardProfile().