XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/load/load.js File Reference
/home/www/rubens/webclient/scripts/load/load.js File Reference
Load scripts and css used in the interface from server.
Functions
function LOAD_StartLoad ()
Show load screen to user, and begin to load scripts.
function LOAD_EndLoad ()
Remove load box from screen.
function LOAD_LoadFiles ()
Build scripts and css files array and start load.
function LOAD_AppendFiles (Files, NumFiles)
function LOAD_NextFile (Files, NumFiles)
function LOAD_EndFile (Files, NumFiles)
function LOAD_ReloadFiles ()
function LOAD_IECssFile ()
Detailed Description
Load scripts and css used in the interface from server.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function LOAD_AppendFiles (Files, NumFiles)
References LOAD_EndFile(), LOAD_NextFile(), LoadObj(), MainData, and UTILS_CreateElement().
Referenced by LOAD_LoadFiles(), and LOAD_NextFile().
function LOAD_EndFile (Files, NumFiles)
References LoadObj(), and MainData.
Referenced by LOAD_AppendFiles().
function LOAD_EndLoad ()
Remove load box from screen.
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References LoadObj(), and MainData.
Referenced by START_Webclient().
function LOAD_IECssFile ()
References UTILS_CreateElement().
Referenced by START_Restart().
function LOAD_LoadFiles ()
Build scripts and css files array and start load.
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References LOAD_AppendFiles(), and MainData.
Referenced by LOAD_StartLoad().
function LOAD_NextFile (Files, NumFiles)
References LOAD_AppendFiles(), LoadObj(), and MainData.
Referenced by LOAD_AppendFiles().
function LOAD_ReloadFiles ()
References UTILS_CreateElement().
Referenced by START_Restart().
function LOAD_StartLoad ()
Show load screen to user, and begin to load scripts.
Returns:
none
Author:
Pedro Rocha and Rubens Suguimoto
References LOAD_LoadFiles(), LoadObj(), LOGIN_EndLogin(), and MainData.
Referenced by CONNECTION_ReceiveConnection().