XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/xmpp_messages/message.js File Reference
/home/www/rubens/webclient/scripts/xmpp_messages/message.js File Reference
Contain all functions to create XMPP messages.
Functions
function MESSAGE_MakeXMPP (Msg)
Append XMPP body to messages (used to BOSH control).
function MESSAGE_EndConnection (Unavailable)
Create a terminate connection with BOSH message.
function MESSAGE_Wait ()
Create a wait message.
function MESSAGE_StartConnection ()
Create first message to open a connection with Jabber.
function MESSAGE_SendUsername ()
Create message with first authentication step.
function MESSAGE_SendPasswd ()
Create message with second authentication step.
function MESSAGE_UserList ()
Create a messate to ask for user's jabber contact list.
function MESSAGE_RoomList ()
Create a message to ask for room list to jabber.
function MESSAGE_Presence (To)
Create a message with Jabber presence.
function MESSAGE_ChangeStatus (NewStatus, RoomName)
Create a message to change user's status.
function MESSAGE_Unavailable (RoomName)
Create message to logout on jabber or leave from some room.
function MESSAGE_Chat (To, Message)
Create a chat message.
function MESSAGE_GroupChat (To, Message)
Create a groupchat message.
function MESSAGE_Info (User)
Create message to get user's ratings.
function MESSAGE_InfoProfile (User)
Create message to get user's ratings profile.
function MESSAGE_Invite (To)
Create message to send a invite to add some user to contact list.
function MESSAGE_InviteAccept (To)
Create message to send a accept invite to other user.
function MESSAGE_InviteDeny (To)
Create message to send a resign invite to other user.
function MESSAGE_RemoveContact (User)
Create message to remove user from your contact list.
function MESSAGE_Challenge (ChallengeID, Category, Rated, Players, MatchID)
Create message to send a challenge message.
function MESSAGE_ChallengeAccept (ChallengeID)
Create a accept a challenge message.
function MESSAGE_ChallengeDecline (ChallengeID)
Create a decline a challenge message.
function MESSAGE_ChallengeGetAdjournList (Num, Offset)
Create a message to get a adjourn games list.
function MESSAGE_ChallengeResumeGame (Id, ChallengeId)
Create a message to resume some adjourned game.
function MESSAGE_GameRoomList ()
Create message to get the list of all games been played.
function MESSAGE_GameRoomInfoList (Room)
Create message to get the list information of all games been played.
function MESSAGE_GameEnterRoom (Room)
Create message used to check if some game exists.
function MESSAGE_GameMove (Move, GameID, Promotion)
Create a message to send a game move.
function MESSAGE_GameRequestDraw (GameID)
Make a draw request.
function MESSAGE_GameRequestCancel (GameID)
Make a cancel request.
function MESSAGE_GameRequestAdjourn (GameID)
Make a adjourn request.
function MESSAGE_GameResign (GameID)
Make a resign message.
function MESSAGE_GameRequests (Action, GameID)
Create the game action requests messages to opponent.
function MESSAGE_GameDrawAccept (GameID)
Make a draw accept.
function MESSAGE_GameDrawDeny (GameID)
Make a draw deny.
function MESSAGE_GameCancelAccept (GameID)
Make a cancel accept.
function MESSAGE_GameCancelDeny (GameID)
Make a cancel deny.
function MESSAGE_GameAdjournAccept (GameID)
Make a adjourn accept.
function MESSAGE_GameAdjournDeny (GameID)
Make a adjourn deny.
function MESSAGE_GameResponse (Action, GameID, Response)
Create the game actions response messages.
function MESSAGE_GameSearchCurrentGame ()
Create message to search for your's current games.
function MESSAGE_SearchUser (Username, Option)
Make a search user message.
function MESSAGE_KickUserRoom (Room, To, Role, Reason)
Create a message to admin kick a user from some room.
function MESSAGE_KickUser (Username, Reason)
Create a message to kick a user from jabber.
function MESSAGE_BanUser (Username, Reason)
Create a message to ban a user from jabber.
function MESSAGE_UnbanUser (Username, Reason)
Create message to unban user from jabber.
function MESSAGE_GetBanList ()
Create message to get a list of all banned users.
function MESSAGE_GetBannedWords ()
Create message to get a list of banned words.
function MESSAGE_AddBannedWord (Word)
Create a message to ban one word.
function MESSAGE_RemoveBannedWord (Word)
Create a message to unban some word.
function MESSAGE_GetProfile (Username, Id)
Create a message to get profile of some user.
function MESSAGE_SetProfile (Username, FullName, Desc, ImgType, Img64)
Create a message to set your profile in Jabber.
function MESSAGE_GetOldGames (Id, Jid1, Jid2, NumGames, Offset, Color, To, From)
Create a message to get old games list with some filters.
function MESSAGE_FetchOldGame (OldGameId)
Create a message to see some old game.
function MESSAGE_AnnounceMatch (Player, Rated, Category, Min, Max, Autoflag)
Create a message to announce a match.
function MESSAGE_GetAnnounceMatch (Offset, NumResult, MinTime, MaxTime, Category, User)
Create a message get announced matchs list with some parameters.
function MESSAGE_RemoveAnnounceMatch (Id)
Create a message cancel one of your announced match.
function MESSAGE_AcceptAnnounceMatch (Id)
Create a message accept some announced match.
Detailed Description
Contain all functions to create XMPP messages.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Create all messages used both Jabber and Chess Server (see Chess server XMPP protocol)
Function Documentation
function MESSAGE_AcceptAnnounceMatch (Id)
Create a message accept some announced match.
Parameters:
Id Announce match identification number
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ANNOUNCE_AcceptAnnounce().
function MESSAGE_AddBannedWord (Word)
Create a message to ban one word.
Parameters:
Word Word string
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ADMIN_BanWord().
function MESSAGE_AnnounceMatch (Player, Rated, Category, Min, Max, Autoflag)
Create a message to announce a match.
Parameters:
Player Player Object(Username, color, time, increment)
Rated Rated game flag
Category Game category
Min Minimum rating interval
Max Maximun rating interval
Autoflag Flag to set game over when some player time's end
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ANNOUNCE_SendAnnounce().
function MESSAGE_BanUser (Username, Reason)
Create a message to ban a user from jabber.
Parameters:
Username User's name
Reason Reason to ban this user
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ADMIN_BanUser().
function MESSAGE_Challenge (ChallengeID, Category, Rated, Players, MatchID)
Create message to send a challenge message.
Should be extended to support Bughouse with more two players. The Player's structure has the following fields:
Name
Color
Inc
Time The 'Color' field must contain just the first letter of color
Parameters:
ChallengeID Challenge identification number (integer)
Category Game cateory
Rated Game rated flag
Players List of Players Object(with username, color, increment, time)
MatchID Match identification number (integer)
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by CHALLENGE_SendChallenge(), and CHALLENGE_SendReChallenge().
function MESSAGE_ChallengeAccept (ChallengeID)
Create a accept a challenge message.
Parameters:
ChallengeID Challenge identification number (integer)
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by CHALLENGE_AcceptChallenge().
function MESSAGE_ChallengeDecline (ChallengeID)
Create a decline a challenge message.
Parameters:
ChallengeID Challenge identification number (integer)
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by CHALLENGE_DeclineChallenge().
function MESSAGE_ChallengeGetAdjournList (Num, Offset)
Create a message to get a adjourn games list.
Parameters:
Num Number of adjourned games to get (integer)
Offset Offset base of adjourn list
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by CHALLENGE_GetAdjournGames(), and GAMECENTER_ShowPostpone().
function MESSAGE_ChallengeResumeGame (Id, ChallengeId)
Create a message to resume some adjourned game.
Parameters:
Id Adjourned game identification number (integer)
ChallengeId XMPP challenge identification number (integer)
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by CHALLENGE_SendResumeGame().
function MESSAGE_ChangeStatus (NewStatus, RoomName)
Create a message to change user's status.
Parameters:
NewStatus New user's status
RoomName Room's name
Returns:
XMPP message
See also:
scripts/contact/status.js for user's status types
Author:
Ulysses Bomfim
References MainData.
Referenced by CHALLENGE_HandleAccept(), and CONTACT_ChangeStatus().
function MESSAGE_Chat (To, Message)
Create a chat message.
Parameters:
To Message user destiny
Message Chat text
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by CHAT_SendMessage().
function MESSAGE_EndConnection (Unavailable)
Create a terminate connection with BOSH message.
Parameters:
Unavailable Message with presence unavailable to Jabber or rooms
Returns:
XMPP message
Author:
Pedro Rocha
References MainData.
Referenced by LOGIN_LeavePage(), and LOGIN_Logout().
function MESSAGE_FetchOldGame (OldGameId)
Create a message to see some old game.
Parameters:
OldGameId Oldgame identification number (integer)
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_AddOldGameResult().
function MESSAGE_GameAdjournAccept (GameID)
Make a adjourn accept.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameResponse().
Referenced by GAME_HandleAdjourn().
function MESSAGE_GameAdjournDeny (GameID)
Make a adjourn deny.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameResponse().
Referenced by GAME_HandleAdjourn().
function MESSAGE_GameCancelAccept (GameID)
Make a cancel accept.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameResponse().
Referenced by GAME_HandleCancel().
function MESSAGE_GameCancelDeny (GameID)
Make a cancel deny.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameResponse().
Referenced by GAME_HandleCancel().
function MESSAGE_GameDrawAccept (GameID)
Make a draw accept.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameResponse().
Referenced by GAME_HandleDraw().
function MESSAGE_GameDrawDeny (GameID)
Make a draw deny.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameResponse().
Referenced by GAME_HandleDraw().
function MESSAGE_GameEnterRoom (Room)
Create message used to check if some game exists.
Parameters:
Room Room's name
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_AddCurrentGames().
function MESSAGE_GameMove (Move, GameID, Promotion)
Create a message to send a game move.
Parameters:
Move Chess Move
GameID Game room name Identification
Promotion Promotion piece used to change pawn
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by GAME_SendMove().
function MESSAGE_GameRequestAdjourn (GameID)
Make a adjourn request.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameRequests().
Referenced by GAME_SendAdjourn().
function MESSAGE_GameRequestCancel (GameID)
Make a cancel request.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameRequests().
Referenced by GAME_SendCancel().
function MESSAGE_GameRequestDraw (GameID)
Make a draw request.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameRequests().
Referenced by GAME_SendDraw().
function MESSAGE_GameRequests (Action, GameID)
Create the game action requests messages to opponent.
Action can be "Draw", "Cancel", "Adjourn" and "Resign".
Parameters:
Action String with action to do when playing some game
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by MESSAGE_GameRequestAdjourn(), MESSAGE_GameRequestCancel(), MESSAGE_GameRequestDraw(), and MESSAGE_GameResign().
function MESSAGE_GameResign (GameID)
Make a resign message.
Parameters:
GameID Game room name Identification
Returns:
XMPP message
Author:
Rubens Suguimoto
References MESSAGE_GameRequests().
Referenced by GAME_SendResign().
function MESSAGE_GameResponse (Action, GameID, Response)
Create the game actions response messages.
Action can be "Draw", "Cancel" and "Adjourn".
Parameters:
Action String with action to do when playing some game
GameID Game room name Identification
Response Create a response with accept ou decline ("" = accept or "-decline" = decline)
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by MESSAGE_GameAdjournAccept(), MESSAGE_GameAdjournDeny(), MESSAGE_GameCancelAccept(), MESSAGE_GameCancelDeny(), MESSAGE_GameDrawAccept(), and MESSAGE_GameDrawDeny().
function MESSAGE_GameRoomInfoList (Room)
Create message to get the list information of all games been played.
Parameters:
Room Room's name
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by CURRENTGAME_HandleGameRoomList().
function MESSAGE_GameRoomList ()
Create message to get the list of all games been played.
Returns:
XMPP message
Author:
Ulysses Bomfim
References MainData.
Referenced by GAMECENTER_ShowCurrentGames(), and INTERFACE_CreateGameCenterCurrentGames().
function MESSAGE_GameSearchCurrentGame ()
Create message to search for your's current games.
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by GAME_SearchCurrentGame().
function MESSAGE_GetAnnounceMatch (Offset, NumResult, MinTime, MaxTime, Category, User)
Create a message get announced matchs list with some parameters.
Parameters:
Offset List off set of announced matchs
NumResult Number of announced matchs to be get
Category Game category
MinTime Minimum time interval
MaxTime Maximun time interval
User Flag to check if you want to get your's own announces
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ANNOUNCE_GetAnnounceGames(), and INTERFACE_CreateGameCenterAnnounce().
function MESSAGE_GetBanList ()
Create message to get a list of all banned users.
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ADMIN_GetBanList().
function MESSAGE_GetBannedWords ()
Create message to get a list of banned words.
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ADMIN_GetBannedWords().
function MESSAGE_GetOldGames (Id, Jid1, Jid2, NumGames, Offset, Color, To, From)
Create a message to get old games list with some filters.
Parameters:
Id Oldgame window Id (Quick fix)
Jid1 First player username
Jid2 Second player username
NumGames Number of games to be search
Offset List off set of old games
Color First player color (if not defined, search for all colors)
From Date begin interval (if not defined, is considerate infinit)
To Date end interval (if not defined, is considerate infinit)
Returns:
XMPP message
Author:
Rubens Suguimoto and Danilo Yorinori
References MainData.
Referenced by INTERFACE_SetNextButton(), INTERFACE_SetPrevButton(), INTERFACE_SetSearchButton(), and OLDGAME_OpenOldGameWindow().
function MESSAGE_GetProfile (Username, Id)
Create a message to get profile of some user.
Parameters:
Username User's name
Id XMPP identification attribute
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by GAME_StartGame(), GAME_StartObserverGame(), OLDGAME_StartOldGame(), PROFILE_SaveMyProfile(), PROFILE_StartProfile(), and START_Webclient().
function MESSAGE_GroupChat (To, Message)
Create a groupchat message.
Parameters:
To Room's JID
Message Room chat text
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ROOM_SendMessage().
function MESSAGE_Info (User)
Create message to get user's ratings.
Parameters:
User User's name
Returns:
XMPP message
Author:
Rubens Suguimoto
Deprecated:
References MainData.
Referenced by CONTACT_ReceiveSubscribed().
function MESSAGE_InfoProfile (User)
Create message to get user's ratings profile.
Parameters:
User User's name
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by PROFILE_StartProfile(), and USER_UpdateUserList().
function MESSAGE_Invite (To)
Create message to send a invite to add some user to contact list.
Parameters:
To User's name to invite destiny
Returns:
XMPP message
Author:
Ulysses Bomfim
References MainData.
Referenced by CONTACT_InviteUser(), and CONTACT_ReceiveSubscribe().
function MESSAGE_InviteAccept (To)
Create message to send a accept invite to other user.
Parameters:
To User's name to accept invite
Returns:
XMPP message
Author:
Ulysses Bomfim
References MainData.
Referenced by CONTACT_HandleContactUserList(), and CONTACT_ReceiveSubscribe().
function MESSAGE_InviteDeny (To)
Create message to send a resign invite to other user.
Parameters:
To User's name to resign invite
Returns:
XMPP message
Author:
Ulysses Bomfim
References MainData.
Referenced by CONTACT_ReceiveSubscribe().
function MESSAGE_KickUser (Username, Reason)
Create a message to kick a user from jabber.
Parameters:
Username User's name
Reason Reason to kick this user
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ADMIN_KickUser().
function MESSAGE_KickUserRoom (Room, To, Role, Reason)
Create a message to admin kick a user from some room.
Parameters:
Room The room that the target user is
To Nick name of the target user in room
Role User's privilege in room
Reason Why the user will be kicked
Returns:
XMPP message
Author:
Ulysses Bomfim
References MainData.
function MESSAGE_MakeXMPP (Msg)
Append XMPP body to messages (used to BOSH control).
Parameters:
Msg XMPP message to send
Returns:
XMPP message with body tag
Author:
Pedro Rocha
References MainData.
Referenced by CONNECTION_SendJabber().
function MESSAGE_Presence (To)
Create a message with Jabber presence.
If 'To' isn't passed, send your presence to jabber, otherwise send presence to 'To' destiny
Parameters:
To Room's JID
Returns:
XMPP message
Author:
Ulysses Bomfim
References MainData.
Referenced by ANNOUNCE_HandleAnnounceGame(), GAME_HandleGameResult(), INTERFACE_AddCurrentGames(), INTERFACE_ShowCreateRoomWindow(), INTERFACE_ShowGameRoomList(), ROOM_EnterRoom(), ROOM_EnterRoomGame(), and START_Webclient().
function MESSAGE_RemoveAnnounceMatch (Id)
Create a message cancel one of your announced match.
Parameters:
Id Announce match identification number
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ANNOUNCE_CancelAnnounce().
function MESSAGE_RemoveBannedWord (Word)
Create a message to unban some word.
Parameters:
Word Word string
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ADMIN_RemoveBannedWord().
function MESSAGE_RemoveContact (User)
Create message to remove user from your contact list.
Parameters:
User User's name to resign invite
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by CONTACT_ReceiveUnsubscribed(), and CONTACT_SendRemoveUser().
function MESSAGE_RoomList ()
Create a message to ask for room list to jabber.
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ROOM_ShowRoomList().
function MESSAGE_SearchUser (Username, Option)
Make a search user message.
Parameters:
Username User's name
Option Option to select by username or full name(0 = username or 1 = full name)
Returns:
XMPP message
Author:
Danilo Kiyoshi Simizu Yorinori
References MainData.
function MESSAGE_SendPasswd ()
Create message with second authentication step.
Send username again, password and resource.
Returns:
XMPP message
Author:
Pedro Rocha
References MainData.
Referenced by CONNECTION_ConnectJabber().
function MESSAGE_SendUsername ()
Create message with first authentication step.
This message contais the first message to authenticate a user. Send username.
Returns:
XMPP message
Author:
Pedro Rocha
References MainData.
Referenced by CONNECTION_ConnectJabber().
function MESSAGE_SetProfile (Username, FullName, Desc, ImgType, Img64)
Create a message to set your profile in Jabber.
Parameters:
Username User's name
FullName User's full name
Desc User's description
ImgType User's image type (png, jpg, bmp...)
Img64 User's image in base 64
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by PROFILE_CreateProfile(), and PROFILE_SaveMyProfile().
function MESSAGE_StartConnection ()
Create first message to open a connection with Jabber.
Returns:
XMPP message
Author:
Pedro Rocha
References MainData.
Referenced by CONNECTION_ConnectJabber().
function MESSAGE_Unavailable (RoomName)
Create message to logout on jabber or leave from some room.
Parameters:
RoomName Room's name
Returns:
XMPP message
Author:
Ulysses Bomfim
References MainData.
Referenced by GAME_StartGame(), LOGIN_LeavePage(), LOGIN_Logout(), and ROOM_ExitRoom().
function MESSAGE_UnbanUser (Username, Reason)
Create message to unban user from jabber.
Parameters:
Username User's name
Reason Reason to unban this user
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by ADMIN_UnbanUser().
function MESSAGE_UserList ()
Create a messate to ask for user's jabber contact list.
Returns:
XMPP message
Author:
Rubens Suguimoto
References MainData.
Referenced by START_Webclient().
function MESSAGE_Wait ()
Create a wait message.
This message is used to make a pesistent conection to BOSH. In certain interval of time, this message is send to notificate BOSH that client is still connected.
Returns:
Empty string
Author:
Pedro Rocha
Referenced by CONNECTION_ReceiveConnection(), and CONNECTION_ReceiveXml().