XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/contact/online_info.js File Reference
/home/www/rubens/webclient/scripts/contact/online_info.js File Reference
Handle user information to online user's list(rating an type).
Functions
function ONLINE_HandleInfo (XML)
Receive a info message and update new information in online list.
function ONLINE_SetUserType (Username, NewType)
Change user's type of 'Username' in online user list object.
function ONLINE_SetUserRating (Username, Category, Rating)
Change user's rating of 'Username' in online user list object.
Detailed Description
Handle user information to online user's list(rating an type).
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software Control user information (rating an type)
Function Documentation
function ONLINE_HandleInfo (XML)
Receive a info message and update new information in online list.
Parameters:
XML XMPP with chess server user's info
Returns:
Empty string
Author:
Rubens Suguimoto
References MainData, ONLINE_SetUserRating(), and ONLINE_SetUserType().
Referenced by PARSER_ParseIq().
function ONLINE_SetUserRating (Username, Category, Rating)
Change user's rating of 'Username' in online user list object.
Parameters:
Username User's name
Category Rating game category
Rating Rating value to be update
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by ONLINE_HandleInfo().
function ONLINE_SetUserType (Username, NewType)
Change user's type of 'Username' in online user list object.
Parameters:
Username User's name
NewType User's type
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by ONLINE_HandleInfo().