XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/contact/online.js File Reference
/home/www/rubens/webclient/scripts/contact/online.js File Reference
Handle all messages and functions to user's online list.
Functions
function ONLINE_StartOnlineList ()
Create online list object and show online list.
function ONLINE_HandleOnlinePresence (XML)
Handle all presence to online list.
function ONLINE_AddUser (User, Status)
Add a user with status in online list.
function ONLINE_RemoveUser (Username)
Remove some user from online list.
function ONLINE_SortUserByNick ()
Sort online list by nick name.
function ONLINE_SortUserByRating (Category)
Sort online list by rating category.
Detailed Description
Handle all messages and functions to user's online list.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function ONLINE_AddUser (User, Status)
Add a user with status in online list.
Parameters:
User User's name
Status User's status
Author:
Rubens Suguimoto
References MainData.
Referenced by ONLINE_HandleOnlinePresence().
function ONLINE_HandleOnlinePresence (XML)
Handle all presence to online list.
Handle general room messages for check online user's
Parameters:
XML The xml come from server with tag presence
Returns:
Empty string
Author:
Ulysses Bonfim
References MainData, ONLINE_AddUser(), ONLINE_RemoveUser(), and UTILS_GetNodeText().
Referenced by PARSER_ParsePresence().
function ONLINE_RemoveUser (Username)
Remove some user from online list.
Parameters:
Username User's name
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by ONLINE_HandleOnlinePresence().
function ONLINE_SortUserByNick ()
Sort online list by nick name.
Sort in MainData before and for each user in MainData online user list, remove and insert it.
Returns:
True
Author:
Rubens Suguimoto
References MainData.
Referenced by ContactOnlineObj().
function ONLINE_SortUserByRating (Category)
Sort online list by rating category.
Sort in MainData before and for each user in MainData online user, remove and insert it.
Parameters:
Category Rating game category
Returns:
True
Author:
Rubens Suguimoto
References MainData.
Referenced by ContactOnlineObj().
function ONLINE_StartOnlineList ()
Create online list object and show online list.
Returns:
none
Author:
Rubens Suguimoto
References ContactOnlineObj(), and MainData.
Referenced by START_Webclient().