XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/parser/parser_iq.js File Reference
/home/www/rubens/webclient/scripts/parser/parser_iq.js File Reference
Functions
function PARSER_ParseIq (XML)
Parse Iq's received from jabber.
function PARSER_ParseIqById (XML)
Parse Iq's messages by Iq id.
Function Documentation
function PARSER_ParseIq (XML)
Parse Iq's received from jabber.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
Parameters:
XML XMPP with Iq message
Returns:
XMPP message to send
Author:
Ulysses Bomfim
References ADMIN_HandleAdmin(), ADMIN_HandleAdminError(), ADMIN_HandleInfo(), ADMIN_HandleRoomAdmin(), ADMIN_HandleUserNotification(), ANNOUNCE_HandleAnnounce(), ANNOUNCE_HandleAnnounceError(), ANNOUNCE_HandleAnnounceGame(), CHALLENGE_HandleAdjourn(), CHALLENGE_HandleChallenge(), CHALLENGE_HandleErrorChallenge(), CONTACT_HandleContactUserList(), CONTACT_HandleInfo(), CONTACT_HandleSearchUser(), CONTACT_HandleSetSubscribe(), CURRENTGAME_HandleGameRoomInfoError(), CURRENTGAME_HandleGameRoomInfoList(), CURRENTGAME_HandleGameRoomList(), GAME_HandleGame(), GAME_HandleGameError(), GAME_HandleGameResult(), GAME_HandleVCardPhoto(), MainData, OLDGAME_FetchOldGame(), OLDGAME_HandleSearchOldGame(), OLDGAME_HandleVCardPhoto(), ONLINE_HandleInfo(), PARSER_ParseIqById(), PROFILE_HandleInfoProfile(), PROFILE_HandleVCardProfile(), ROOM_HandleInfo(), ROOM_HandleRoomList(), USER_HandleContactUserList(), and USER_HandleInfo().
Referenced by PARSER_ParseXml().
function PARSER_ParseIqById (XML)
Parse Iq's messages by Iq id.
Parameters:
XML XMPP messages with Iq tag
Returns:
XMPP message to send
Author:
Rubens Suguimoto
References MainData, and PROFILE_CreateProfile().
Referenced by PARSER_ParseIq().