XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/parser/parser.js File Reference
/home/www/rubens/webclient/scripts/parser/parser.js File Reference
Parse XMPP received from jabber.
Functions
function PARSER_ParseXml (XML)
Receive and forward XML to controllers.
Detailed Description
Parse XMPP received from jabber.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
Function Documentation
function PARSER_ParseXml (XML)
Receive and forward XML to controllers.
Parameters:
XML XMPP message
Returns:
XMPP to send
Author:
Ulysses Bomfim
References LOGIN_Disconnected(), MainData, PARSER_ParseChat(), PARSER_ParseIq(), PARSER_ParsePresence(), START_Restart(), and UTILS_GetText().
Referenced by CONNECTION_ReceiveXml().