XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/postpone.js File Reference
/home/www/rubens/webclient/scripts/interface/postpone.js File Reference
Functions
function INTERFACE_ShowPostponeWindow (Oponent, RatingObj, GameParameters, Rated, MatchId)
Create elements to postpone invite window content.
Function Documentation
function INTERFACE_ShowPostponeWindow (Oponent, RatingObj, GameParameters, Rated, MatchId)
Create elements to postpone invite window content.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Parameters:
Oponent Oponent's name
RatingObj Oponent's rating object
GameParameters Object that contains the game parameters
Rated Rated game flag
MatchId Postponed game identification number
Returns:
Postpone window content Div and Buttons Array
Author:
Danilo Kiyoshi Simizu Yorinori
References CHALLENGE_AcceptChallenge(), CHALLENGE_DeclineChallenge(), CHAT_OpenChat(), MainData, UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_Postpone().