XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/profile/profile.js File Reference
/home/www/rubens/webclient/scripts/profile/profile.js File Reference
Functions
function PROFILE_HandleVCardProfile (XML)
Handle Jabber vCard User.
function PROFILE_HandleInfoProfile (XML)
Handle info profile user.
function PROFILE_HandleRatings (Username, RatingNodes)
Create an array with ratings and return it.
function PROFILE_StartProfile (Username)
Create profile in data Struct and show Profile window.
function PROFILE_RemoveProfile (Username)
Remove Profile from data struct.
function PROFILE_SaveMyProfile ()
Save changes of your profile.
function PROFILE_CreateProfile ()
Return a default message to create a profile.
function PROFILE_ResetUpdateProfile ()
function PROFILE_ConvertUserRatingList (RatingList)
function PROFILE_ChangeVerification (Elements)
Verify if any change occurs in profile's data.
Function Documentation
function PROFILE_ChangeVerification (Elements)
Verify if any change occurs in profile's data.
Parameters:
Elements Profile window content elements object
Returns:
True if is there some change or false
Author:
Danilo Yorinori
References MainData.
Referenced by WINDOW_Profile().
function PROFILE_ConvertUserRatingList (RatingList)
Referenced by PROFILE_StartProfile().
function PROFILE_CreateProfile ()
Return a default message to create a profile.
Returns:
XMPP message to set profile
Author:
Pedro Rocha
References MainData, and MESSAGE_SetProfile().
Referenced by PARSER_ParseIqById().
function PROFILE_HandleInfoProfile (XML)
Handle info profile user.
Parameters:
XML is the xml that contais profile informations
Returns:
Empty string
Author:
Rubens Suguimoto
References MainData, and PROFILE_HandleRatings().
Referenced by PARSER_ParseIq().
function PROFILE_HandleRatings (Username, RatingNodes)
Create an array with ratings and return it.
Parameters:
Username User's name
RatingNodes Array of ratings with data
Returns:
Array in format: each line is a rating type [1] lightning [2] blitz [3] Standard each column is a data [1] category [2] current rating [3] max rating [4] max rating date [5] number of games in category [6] number of wins [7] number of losses [8] numeber of draws
See also:
CONTACT_HandleInfo(XML);
Author:
Danilo Yorinori
References UTILS_ConvertTimeStamp().
Referenced by PROFILE_HandleInfoProfile().
function PROFILE_HandleVCardProfile (XML)
Handle Jabber vCard User.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Parameters:
XML is the xml that contais vCard information
Returns:
Empty string
Author:
Rubens Suguimoto
References INTERFACE_SetUserImage(), MainData, and UTILS_GetNodeText().
Referenced by PARSER_ParseIq().
function PROFILE_RemoveProfile (Username)
Remove Profile from data struct.
Parameters:
Username User's name
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by WINDOW_Profile(), and WINDOW_ProfileConfirm().
function PROFILE_ResetUpdateProfile ()
References MainData.
function PROFILE_SaveMyProfile ()
Save changes of your profile.
Returns:
True if success or false if some field was not correctly
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, MESSAGE_GetProfile(), MESSAGE_SetProfile(), UTILS_GetText(), and WINDOW_Alert().
Referenced by INTERFACE_ShowProfileConfirmWindow(), and WINDOW_Profile().
function PROFILE_StartProfile (Username)
Create profile in data Struct and show Profile window.
Parameters:
Username User's name
Returns:
True
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, MESSAGE_GetProfile(), MESSAGE_InfoProfile(), PROFILE_ConvertUserRatingList(), USER_AddUser(), and WINDOW_Profile().
Referenced by CONTACT_ShowUserMenu(), and INTERFACE_CreateUserBox().