XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/room/room.js File Reference
/home/www/rubens/webclient/scripts/room/room.js File Reference
Room controller.
Functions
function ROOM_HandleRoomPresence (XML)
Handle all presence from a room.
function ROOM_HandleMessage (XML)
Handle group chat messages.
function ROOM_HandleRoomList (XML)
Handle room list in top menu.
function ROOM_HandleInfo (XML)
function ROOM_SendMessage (RoomName, Message)
Send a chat message to room.
function ROOM_ShowRoomList (OffsetLeft)
Get Room list from server and show in pop down in top menu.
function ROOM_EnterRoom (RoomName)
Send presence to a room (enter in some room).
function ROOM_ExitRoom (RoomName)
Exit a room.
function ROOM_EnterRoomGame (RoomName)
Send presence to a room game(enter room game).
function ROOM_ShowMessage (RoomName, From, Message, Stamp)
function ROOM_ErrorMessageLength (RoomName)
function ROOM_AddUser (RoomName, Jid, Status, Role, Affiliation)
Insert user in room list.
function ROOM_RemoveUser (RoomName, UserName)
function ROOM_CreateRoom (RoomName)
function ROOM_FocusRoom (RoomName)
function ROOM_RemoveRoom (RoomName)
function ROOM_SortUsersByNick ()
function ROOM_SortUsersByRating (Category)
function ROOM_ShowHideUserList (RoomName)
Detailed Description
Room controller.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function ROOM_AddUser (RoomName, Jid, Status, Role, Affiliation)
Insert user in room list.
Parameters:
RoomName Room's name
Jid User's name
Status User's status
Role User's room role status
Affiliation User's room affilitation status
Returns:
Empty string
Author:
Pedro Rocha and Rubens Suguimoto
References MainData.
Referenced by ROOM_HandleRoomPresence().
function ROOM_CreateRoom (RoomName)
References INTERFACE_CreateRoomInBar(), MainData, ROOM_FocusRoom(), and RoomObj().
Referenced by ROOM_HandleRoomPresence().
function ROOM_EnterRoom (RoomName)
Send presence to a room (enter in some room).
Parameters:
RoomName Room's nama
Returns:
Empty string
Author:
Ulysses Bomfim and Danilo Yorinori
References CONNECTION_SendJabber(), MainData, MESSAGE_Presence(), and ROOM_FocusRoom().
Referenced by INTERFACE_ShowRoomList().
function ROOM_EnterRoomGame (RoomName)
Send presence to a room game(enter room game).
Parameters:
RoomName Room's name
Returns:
True
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, and MESSAGE_Presence().
Referenced by GAME_StartObserverGame().
function ROOM_ErrorMessageLength (RoomName)
References MainData, and UTILS_GetText().
Referenced by INTERFACE_CreateRoom().
function ROOM_ExitRoom (RoomName)
Exit a room.
Parameters:
RoomName Room's name
Returns:
XMPP with presence unavailable to a room
Author:
Pedro Rocha and Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, MESSAGE_Unavailable(), UTILS_GetText(), and WINDOW_Alert().
Referenced by GAME_RemoveGame(), INTERFACE_CreateRoomInBar(), INTERFACE_FocusRoom(), and OLDGAME_RemoveOldGame().
function ROOM_FocusRoom (RoomName)
References INTERFACE_FocusRoom(), INTERFACE_RefreshOccupantsNumber(), and MainData.
Referenced by INTERFACE_ChangeRoomListVisibility(), INTERFACE_CreateRoomInBar(), INTERFACE_FocusRoom(), ROOM_CreateRoom(), ROOM_EnterRoom(), and ROOM_RemoveRoom().
function ROOM_HandleInfo (XML)
References MainData.
Referenced by PARSER_ParseIq().
function ROOM_HandleMessage (XML)
Handle group chat messages.
Parameters:
XML XML message from server with tag message
Returns:
Empty string
Author:
Ulysses Bomfim
References ROOM_ShowMessage(), and UTILS_GetNodeText().
Referenced by PARSER_ParseChat().
function ROOM_HandleRoomList (XML)
Handle room list in top menu.
Parameters:
XML XML message with opened rooms
Returns:
XMPP to send
Author:
Ulysses Bomfim
References INTERFACE_RemoveLoadBox(), INTERFACE_ShowRoomList(), MainData, and UTILS_GetText().
Referenced by PARSER_ParseIq().
function ROOM_HandleRoomPresence (XML)
Handle all presence from a room.
Parameters:
XML XML message from server with tag presence
Returns:
XMPP to send
Author:
Ulysses Bomfim and Rubens Suguimoto
References INTERFACE_RefreshOccupantsNumber(), MainData, ROOM_AddUser(), ROOM_CreateRoom(), ROOM_RemoveRoom(), ROOM_RemoveUser(), and UTILS_GetNodeText().
Referenced by PARSER_ParsePresence().
function ROOM_RemoveRoom (RoomName)
References INTERFACE_CloseRoom(), INTERFACE_CreateRoomInBar(), INTERFACE_RefreshOccupantsNumber(), INTERFACE_RemoveRoomFromList(), MainData, and ROOM_FocusRoom().
Referenced by ROOM_HandleRoomPresence().
function ROOM_RemoveUser (RoomName, UserName)
References MainData.
Referenced by ROOM_HandleRoomPresence().
function ROOM_SendMessage (RoomName, Message)
Send a chat message to room.
Parameters:
RoomName Room's name
Message Chat message text that will be send
Returns:
True if sucess or false if room not founded
Author:
Rubens
References CONNECTION_SendJabber(), MainData, MESSAGE_GroupChat(), and UTILS_ConvertChatString().
Referenced by INTERFACE_CreateRoom().
function ROOM_ShowHideUserList (RoomName)
References MainData.
Referenced by INTERFACE_CreateRoom().
function ROOM_ShowMessage (RoomName, From, Message, Stamp)
References MainData, and UTILS_BannedWords().
Referenced by ROOM_HandleMessage().
function ROOM_ShowRoomList (OffsetLeft)
Get Room list from server and show in pop down in top menu.
Parameters:
OffsetLeft Offset left position in pixels
Returns:
none
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), INTERFACE_ShowRoomMenu(), and MESSAGE_RoomList().
Referenced by INTERFACE_CreateTop().
function ROOM_SortUsersByNick ()
References MainData.
Referenced by RoomObj().
function ROOM_SortUsersByRating (Category)
References MainData.
Referenced by RoomObj().