XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/contact/status.js File Reference
/home/www/rubens/webclient/scripts/contact/status.js File Reference
Handle user's status.
Functions
function CONTACT_ChangeStatus (NewStatus, DontSend)
Change User Status.
function CONTACT_SetUserStatus (Username, NewStatus)
Change status of 'Username' in structure and interface.
function CONTACT_StartAwayCounter ()
Start away counter.
function CONTACT_SetAwayStatus ()
Countdown away counter, and set away status if away counter less than zero.
function CONTACT_ResetAwayStatus ()
Reset away counter and set status to available.
function CONTACT_StopAwayStatus ()
Stop away counter.
Detailed Description
Handle user's status.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Status types: "available", "unavailable", "busy", "away", "playing", "offline" TODO --> Split change status to online list, rooms and contact lists
Function Documentation
function CONTACT_ChangeStatus (NewStatus, DontSend)
Change User Status.
Parameters:
NewStatus New user's status
DontSend Flag to send or just return XML
Returns:
XMPP message accordly to flag DontSend
Author:
Rubens Suguimoto
References CONNECTION_SendJabber(), MainData, MESSAGE_ChangeStatus(), UTILS_Capitalize(), UTILS_CreateElement(), and UTILS_GetText().
Referenced by ANNOUNCE_HandleAnnounceGame(), CONTACT_ResetAwayStatus(), CONTACT_SetAwayStatus(), GAME_End(), GAME_StartGame(), and INTERFACE_CreateUserBox().
function CONTACT_ResetAwayStatus ()
Reset away counter and set status to available.
Returns:
none
Author:
Rubens Suguimoto
References CONTACT_ChangeStatus(), and MainData.
function CONTACT_SetAwayStatus ()
Countdown away counter, and set away status if away counter less than zero.
Returns:
none
Author:
Rubens Suguimoto
References CONTACT_ChangeStatus(), and MainData.
function CONTACT_SetUserStatus (Username, NewStatus)
Change status of 'Username' in structure and interface.
Parameters:
Username User's name
NewStatus New user's status
Returns:
Empty String
Author:
Rubens Suguimoto
References ContactObj(), INTERFACE_RefreshContactOnlineNumber(), and MainData.
Referenced by CONTACT_HandleUserPresence(), and CONTACT_ReceiveUnsubscribed().
function CONTACT_StartAwayCounter ()
Start away counter.
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by START_Webclient().
function CONTACT_StopAwayStatus ()
Stop away counter.
Returns:
none
Author:
Rubens Suguimoto
References MainData.
Referenced by START_Restart().