XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/top.js File Reference
/home/www/rubens/webclient/scripts/interface/top.js File Reference
Functions
function INTERFACE_CreateTop ()
Create element of top of the screen.
function INTERFACE_ShowRoomMenu (OffsetLeft)
Show rooms list.
function INTERFACE_ShowGameRoomMenu (OffsetLeft)
Show rooms menu.
function INTERFACE_ShowLoadBox ()
function INTERFACE_RemoveLoadBox ()
function INTERFACE_NoGamesInGameList ()
function INTERFACE_ShowAdminIcon ()
Function Documentation
function INTERFACE_CreateTop ()
Create element of top of the screen.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Returns:
Top HTML DOM Div
Author:
Pedro Rocha and Rubens Suguimoto
References LOGIN_Logout(), OLDGAME_OpenOldGameWindow(), ROOM_ShowRoomList(), UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetOffset(), UTILS_GetText(), WINDOW_Alert(), and WINDOW_Help().
Referenced by INTERFACE_CreateInterface().
function INTERFACE_NoGamesInGameList ()
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by CURRENTGAME_HandleGameRoomList().
function INTERFACE_RemoveLoadBox ()
Referenced by ROOM_HandleRoomList().
function INTERFACE_ShowAdminIcon ()
References UTILS_AddListener(), UTILS_GetText(), and WINDOW_CreateAdminCenter().
Referenced by ADMIN_HandleInfo().
function INTERFACE_ShowGameRoomMenu (OffsetLeft)
Show rooms menu.
Parameters:
OffsetLeft Position off set left
Returns:
True if created menu with success or null (if room list was opened)
See also:
room/room.js: ROOM_HandleGameRoomInfoList to load list itens
Author:
Ulysses Bomfim and Rubens Suguimoto
References INTERFACE_HideGameRoomList(), INTERFACE_ShowLoadBox(), UTILS_AddListener(), UTILS_CreateElement(), and UTILS_RemoveListener().
function INTERFACE_ShowLoadBox ()
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by INTERFACE_ShowGameRoomMenu(), and INTERFACE_ShowRoomMenu().
function INTERFACE_ShowRoomMenu (OffsetLeft)
Show rooms list.
Parameters:
OffsetLeft Position off set left
Returns:
True if created menu with success or null (if room list was opened)
Author:
Pedro Rocha and Rubens Suguimoto
References INTERFACE_HideRoomList(), INTERFACE_ShowLoadBox(), UTILS_AddListener(), UTILS_CreateElement(), UTILS_GetText(), UTILS_RemoveListener(), and WINDOW_CreateRoom().
Referenced by ROOM_ShowRoomList().