XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/tourney.js File Reference
/home/www/rubens/webclient/scripts/interface/tourney.js File Reference
Functions
function INTERFACE_ShowCreateTourneyWindow ()
Create elements to create tourney window content.
Function Documentation
function INTERFACE_ShowCreateTourneyWindow ()
Create elements to create tourney window content.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Returns:
Tourney main HTML DOM Div and Buttons array
Author:
Danilo Kiyoshi Simizu Yorinori
References UTILS_CreateElement(), and UTILS_GetText().
Referenced by WINDOW_CreateTourney().