XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/utils/utils.js File Reference
/home/www/rubens/webclient/scripts/utils/utils.js File Reference
Utils and auxiliars functions.
Functions
function UTILS_IdentifyBrowser ()
Identify client web browser and return a value.
function UTILS_OpenXMLFile (Url)
Open a XML file, create and return XML DOM Tree.
function UTILS_GetTag (XML, TagName)
Find and return node in XML tree with TagName and return this node content.
function UTILS_GetText (TagName)
Get text from language selected. If TagName was not founded in language seleted, then found in Default language text. We assume that default language has all tags.
function UTILS_GetNodeText (Node)
Get element content in any browser.
function UTILS_CreateElement (Element, Id, ClassName, Inner)
Create a DOM element.
function UTILS_CreateCookie (CookieName, CookieValue, Days)
Create webclient cookies.
function UTILS_ReadCookie (CookieName)
Read webclient cookies.
function UTILS_DeleteCookie (CookieName)
Remove webclient cookies from browser.
function UTILS_ValidateUsername (Username)
Check if username is a valid checking characters.
function UTILS_Capitalize (Word)
Capitalize a word.
function UTILS_BreakString (Obj, Width)
Set breaklines inside texts Put a "<br />" tag at Obj.innerHTML if it pass the Width limit.
function UTILS_ShortString (Word, NumChars)
Remove NumChars characteres of Word.
function UTILS_BannedWords (Str)
Check if string has some banned words. If exist replace all characters to '*' and return new string.
function UTILS_AddListener (Element, Type, Expression, Bubbling)
Add an event listener from element Return true if event has added or false if event hasn't added Code from: http://snipplr.com/view/561/add-event-listener/.
function UTILS_RemoveListener (Element, Type, Expression, Bubbling)
Remove an event listener from element Return true if event has removed or false if event hasn't removed.
function UTILS_ReturnEvent (event)
Check web browser type and return event object.
function UTILS_ReturnKeyCode (event)
Check web browser type and return event key code correctly.
function UTILS_GetTime (Timestamp)
Convert timestamp format to new format (XXhXX).
function UTILS_ConvertTimeStamp (TimeStamp)
Return the max_timestamp from rating to format(dd-mm-yyyy).
function UTILS_ConvertSearchDate (TimeStamp, Type)
Return the date-time string to search old games.
function UTILS_GetOffset (Obj)
function UTILS_GetParentDiv (Obj)
Get the first parent div in DOM tree, starting from some element.
function UTILS_HorizontalIndex (CharNum)
Convert horizontal board index. If param is a number convert to repesctive char else convert to respective number.
function UTILS_String2Board (BoardString)
Convert a string board to a array (8x8) board.
function UTILS_ConvertChatString (Str)
Convert a chat string to a format that can't be interpretated.
Detailed Description
Utils and auxiliars functions.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
Function Documentation
function UTILS_AddListener (Element, Type, Expression, Bubbling)
Add an event listener from element Return true if event has added or false if event hasn't added Code from: http://snipplr.com/view/561/add-event-listener/.
Parameters:
Element DOM element
Type Event type
Expression Function or action to add
Bubbling Transmite event to others elements overlayed
Returns:
True or false
Author:
Rubens Suguimoto
Referenced by CONTACT_ShowUserMenu(), INTERFACE_AddMove(), INTERFACE_AddOldGameResult(), INTERFACE_BanUserWindow(), INTERFACE_CreateContactContent(), INTERFACE_CreateGameOptions(), INTERFACE_CreateOnlineContent(), INTERFACE_CreateTab(), INTERFACE_CreateTop(), INTERFACE_CreateUserBox(), INTERFACE_KickUserWindow(), INTERFACE_SetNextButton(), INTERFACE_SetPrevButton(), INTERFACE_SetSearchButton(), INTERFACE_SetSortRatingFunction(), INTERFACE_SetSortUserFunction(), INTERFACE_ShowAdminIcon(), INTERFACE_ShowEmoticonList(), INTERFACE_ShowGameRoomMenu(), INTERFACE_ShowOldGameWindow(), INTERFACE_ShowRoomMenu(), INTERFACE_ShowSearchUserWindow(), INTERFACE_StartLogin(), INTERFACE_UnbanUserWindow(), WINDOW_AdminWindow(), WINDOW_Alert(), WINDOW_AnnounceWindow(), WINDOW_BanUser(), WINDOW_CancelRoom(), WINDOW_Challenge(), WINDOW_Confirm(), WINDOW_CreateAdminCenter(), WINDOW_CreateConfirm(), WINDOW_CreateRoom(), WINDOW_CreateTourney(), WINDOW_CreateWindow(), WINDOW_Help(), WINDOW_Invite(), WINDOW_KickUser(), WINDOW_NewWindow(), WINDOW_OldGame(), WINDOW_Postpone(), WINDOW_Profile(), WINDOW_ProfileConfirm(), WINDOW_ProfileImage(), WINDOW_SearchUser(), and WINDOW_UnbanUser().
function UTILS_BannedWords (Str)
Check if string has some banned words. If exist replace all characters to '*' and return new string.
Parameters:
Str String with some text
Returns:
New string with words changed
Author:
Rubens Suguimoto
References AdminCenterObj(), and MainData.
Referenced by CHAT_ReceiveMessage(), CHAT_SendMessage(), and ROOM_ShowMessage().
function UTILS_BreakString (Obj, Width)
Set breaklines inside texts Put a "<br />" tag at Obj.innerHTML if it pass the Width limit.
Parameters:
Obj Cell table's object
Width max Base object
Returns:
String
Author:
Danilo Kiyoshi Simizu Yorinori
References MainData.
Referenced by INTERFACE_OldGameSetTable().
function UTILS_Capitalize (Word)
Capitalize a word.
Parameters:
Word String
Returns:
String with first character changed to upper case
Author:
Danilo Kiyoshi Simizu Yorinori
Referenced by CONTACT_ChangeStatus(), CONTACT_ReceiveSubscribe(), INTERFACE_CreateLangItem(), INTERFACE_CreateUserBox(), INTERFACE_ShowGameRoomList(), and INTERFACE_ShowSearchUserWindow().
function UTILS_ConvertChatString (Str)
Convert a chat string to a format that can't be interpretated.
Parameters:
Str string to be some characters replace
Returns:
string with '<' , '>', '&' and '"' replaced
Author:
Rubens Suguimoto
Referenced by CHAT_HandleMessage(), CHAT_SendMessage(), INTERFACE_AddMsgInRoom(), and ROOM_SendMessage().
function UTILS_ConvertSearchDate (TimeStamp, Type)
Return the date-time string to search old games.
Parameters:
TimeStamp Date string (dd/mm/yyyy)
Type begin or end (yyyy-mm-ddTnn:nn:nnZ)
Returns:
String
See also:
INTERFACE_SetSearchButton(Node)
Author:
Danilo Yorinori
Referenced by INTERFACE_SetSearchButton().
function UTILS_ConvertTimeStamp (TimeStamp)
Return the max_timestamp from rating to format(dd-mm-yyyy).
Parameters:
TimeStamp Timestamp integer value
Returns:
String with date format in dd-mm-yyyy
See also:
PROFILE_HandleRatings()
Author:
Danilo Yorinori
Referenced by INTERFACE_FromInput(), INTERFACE_ToInput(), OLDGAME_HandleSearchOldGame(), PROFILE_HandleRatings(), and USER_HandleInfo().
function UTILS_CreateCookie (CookieName, CookieValue, Days)
Create webclient cookies.
Parameters:
CookieName String
CookieValue Data to be store in cookie
Days Cookie expire period
Author:
Pedro Rocha
Referenced by LOGIN_Login(), START_ChangeLanguage(), and UTILS_DeleteCookie().
function UTILS_CreateElement (Element, Id, ClassName, Inner)
Create a DOM element.
Parameters:
Element Element tag name
Id Element identification attribute
ClassName Element class name attribute
Inner Element content
Returns:
New element with some attributes set up
Author:
Pedro Rocha
Referenced by CONTACT_ChangeStatus(), INTERFACE_AddAdjourn(), INTERFACE_AddAdminLevel(), INTERFACE_AddAnnounce(), INTERFACE_AddBannedUser(), INTERFACE_AddChatMessage(), INTERFACE_AddChatMessageError(), INTERFACE_AddCurrentGames(), INTERFACE_AddLevel(), INTERFACE_AddMatchOffer(), INTERFACE_AddMove(), INTERFACE_AddMsgErrorInRoom(), INTERFACE_AddOldGameResult(), INTERFACE_AddPostpone(), INTERFACE_AddPunish(), INTERFACE_AddWords(), INTERFACE_AnnounceWindow(), INTERFACE_BanUserWindow(), INTERFACE_ChangeRoomListVisibility(), INTERFACE_CreateAdminCenter(), INTERFACE_CreateAdminCenterAdjourn(), INTERFACE_CreateAdminCenterAdminLevel(), INTERFACE_CreateAdminCenterLevel(), INTERFACE_CreateAdminCenterPunish(), INTERFACE_CreateAdminCenterWords(), INTERFACE_CreateAdminWindow(), INTERFACE_CreateBoard(), INTERFACE_CreateChallengeMenu(), INTERFACE_CreateChat(), INTERFACE_CreateChatList(), INTERFACE_CreateContact(), INTERFACE_CreateContactContent(), INTERFACE_CreateGame(), INTERFACE_CreateGameCenter(), INTERFACE_CreateGameCenterAnnounce(), INTERFACE_CreateGameCenterCurrentGames(), INTERFACE_CreateGameCenterMatch(), INTERFACE_CreateGameCenterPostpone(), INTERFACE_CreateGameOptions(), INTERFACE_CreateGroup(), INTERFACE_CreateHelpContent(), INTERFACE_CreateHorizontalIndex(), INTERFACE_CreateInterface(), INTERFACE_CreateLangItem(), INTERFACE_CreateLanguage(), INTERFACE_CreateLeft(), INTERFACE_CreateLoadingBox(), INTERFACE_CreateMoveList(), INTERFACE_CreateOldGameMoveList(), INTERFACE_CreateOldGameTab(), INTERFACE_CreateOnlineContent(), INTERFACE_CreatePhoto(), INTERFACE_CreateRoom(), INTERFACE_CreateRoomInBar(), INTERFACE_CreateRooms(), INTERFACE_CreateTab(), INTERFACE_CreateTimer(), INTERFACE_CreateTop(), INTERFACE_CreateUser(), INTERFACE_CreateUserBox(), INTERFACE_CreateUserElement(), INTERFACE_CreateUserList(), INTERFACE_CreateVerticalIndex(), INTERFACE_CreateWelcome(), INTERFACE_HelpWindow(), INTERFACE_KickUserWindow(), INTERFACE_NewPiece(), INTERFACE_NoGamesInGameList(), INTERFACE_ProfileSetRatings(), INTERFACE_SetBlockBorder(), INTERFACE_ShowCancelRoomWindow(), INTERFACE_ShowChallengeWindow(), INTERFACE_ShowCreateAdminCenterWindow(), INTERFACE_ShowCreateRoomWindow(), INTERFACE_ShowCreateTourneyWindow(), INTERFACE_ShowEmoticonList(), INTERFACE_ShowFullName(), INTERFACE_ShowGameRoomList(), INTERFACE_ShowGameRoomMenu(), INTERFACE_ShowLoadBox(), INTERFACE_ShowOldGameWindow(), INTERFACE_ShowPostponeWindow(), INTERFACE_ShowProfileConfirmWindow(), INTERFACE_ShowProfileWindow(), INTERFACE_ShowRoomList(), INTERFACE_ShowRoomMenu(), INTERFACE_ShowSearchUserWindow(), INTERFACE_ShowUserFullName(), INTERFACE_ShowUserMenu(), INTERFACE_StartLoad(), INTERFACE_StartLogin(), INTERFACE_UnbanUserWindow(), LOAD_AppendFiles(), LOAD_IECssFile(), LOAD_ReloadFiles(), WINDOW_CreateAlert(), WINDOW_CreateConfirm(), and WINDOW_CreateImageSend().
function UTILS_DeleteCookie (CookieName)
Remove webclient cookies from browser.
Parameters:
CookieName String
Author:
Pedro Rocha
References UTILS_CreateCookie().
Referenced by LOGIN_Login().
function UTILS_GetNodeText (Node)
Get element content in any browser.
Parameters:
Node DOM element
Returns:
Node content string
Author:
Rubens Suguimoto
Referenced by ADMIN_HandleBanList(), ADMIN_HandleUserNotification(), CHAT_HandleAnnounceMessage(), CHAT_HandleMessage(), CONTACT_HandleContactUserList(), CONTACT_HandleSearchUser(), CONTACT_HandleSetSubscribe(), CONTACT_HandleUserPresence(), GAME_HandleVCardPhoto(), INTERFACE_CreateLanguage(), INTERFACE_CreateWelcome(), OLDGAME_HandleVCardPhoto(), ONLINE_HandleOnlinePresence(), PROFILE_HandleVCardProfile(), ROOM_HandleMessage(), ROOM_HandleRoomPresence(), USER_HandlePresence(), USER_HandleRoomPresence(), and UTILS_GetTag().
function UTILS_GetOffset (Obj)
Referenced by INTERFACE_CreateTop(), INTERFACE_ShowFullName(), INTERFACE_ShowUserFullName(), INTERFACE_ShowUserMenu(), and UTILS_StartDragPiece().
function UTILS_GetParentDiv (Obj)
Get the first parent div in DOM tree, starting from some element.
Parameters:
Obj DOM element
Returns:
First parent div in DOM tree
Author:
Pedro Rocha
Referenced by INTERFACE_OldGameSetTable(), INTERFACE_ShowFullName(), INTERFACE_ShowUserFullName(), and INTERFACE_ShowUserMenu().
function UTILS_GetTag (XML, TagName)
Find and return node in XML tree with TagName and return this node content.
Parameters:
XML XML tree
TagName String used to find node
Returns:
Node content string
Author:
Rubens Suguimoto
References UTILS_GetNodeText().
Referenced by DATA(), REGISTER_GetError(), REGISTER_Labels(), REGISTER_ParseError(), REGISTER_SucessMessage(), START_StartPage(), and UTILS_GetText().
function UTILS_GetText (TagName)
Get text from language selected. If TagName was not founded in language seleted, then found in Default language text. We assume that default language has all tags.
Parameters:
TagName Text tag
Returns:
Text content of node with TagName
Author:
Rubens Suguimoto
References MainData, and UTILS_GetTag().
Referenced by ADMIN_HandleUserNotification(), ADMIN_Notification(), ANNOUNCE_AcceptRandomAnnounce(), ANNOUNCE_HandleAnnounceError(), ANNOUNCE_SendAnnounce(), CHALLENGE_HandleErrorChallenge(), CHAT_ErrorMessageLength(), CHAT_OpenChat(), CONNECTION_ConnectJabber(), CONNECTION_ReceiveConnection(), CONNECTION_ReceiveXml(), CONTACT_ChangeStatus(), CONTACT_ReceiveSubscribe(), CONTACT_ShowUserMenu(), CURRENTGAME_HandleGameRoomInfoError(), GAME_End(), GAME_HandleAdjourn(), GAME_HandleCancel(), GAME_HandleDraw(), GAME_HandleGameError(), GAME_RemoveGame(), GAME_SendResign(), IMAGE_B64Img(), INTERFACE_AddAdjourn(), INTERFACE_AddAdminLevel(), INTERFACE_AddAnnounce(), INTERFACE_AddCurrentGames(), INTERFACE_AddLevel(), INTERFACE_AddMatchOffer(), INTERFACE_AddOldGameResult(), INTERFACE_AddPostpone(), INTERFACE_AddPunish(), INTERFACE_AddWords(), INTERFACE_AnnounceWindow(), INTERFACE_ChangeRoomListVisibility(), INTERFACE_CreateAdminCenter(), INTERFACE_CreateAdminCenterAdjourn(), INTERFACE_CreateAdminCenterAdminLevel(), INTERFACE_CreateAdminCenterLevel(), INTERFACE_CreateAdminCenterPunish(), INTERFACE_CreateAdminCenterWords(), INTERFACE_CreateAdminWindow(), INTERFACE_CreateChallengeMenu(), INTERFACE_CreateContact(), INTERFACE_CreateContactContent(), INTERFACE_CreateGame(), INTERFACE_CreateGameCenter(), INTERFACE_CreateGameCenterAnnounce(), INTERFACE_CreateGameCenterCurrentGames(), INTERFACE_CreateGameCenterMatch(), INTERFACE_CreateGameCenterPostpone(), INTERFACE_CreateGameOptions(), INTERFACE_CreateGroup(), INTERFACE_CreateOldGameMoveList(), INTERFACE_CreateOldGameTab(), INTERFACE_CreateOnlineContent(), INTERFACE_CreateRoom(), INTERFACE_CreateRoomInBar(), INTERFACE_CreateRooms(), INTERFACE_CreateTab(), INTERFACE_CreateTop(), INTERFACE_CreateUserBox(), INTERFACE_CreateUserList(), INTERFACE_CreateWelcome(), INTERFACE_HelpWindow(), INTERFACE_HideRoomUserList(), INTERFACE_NewPiece(), INTERFACE_NoGamesInGameList(), INTERFACE_ProfileSetDesc(), INTERFACE_ProfileSetGroup(), INTERFACE_RemoveGame(), INTERFACE_SearchUserSetResult(), INTERFACE_SetSearchButton(), INTERFACE_ShowAdminIcon(), INTERFACE_ShowCancelRoomWindow(), INTERFACE_ShowChallengeWindow(), INTERFACE_ShowCreateRoomWindow(), INTERFACE_ShowCreateTourneyWindow(), INTERFACE_ShowGameRoomList(), INTERFACE_ShowLeaveUser(), INTERFACE_ShowLoadBox(), INTERFACE_ShowOldGameWindow(), INTERFACE_ShowPostponeWindow(), INTERFACE_ShowProfileConfirmWindow(), INTERFACE_ShowProfileWindow(), INTERFACE_ShowRoomMenu(), INTERFACE_ShowRoomUserList(), INTERFACE_ShowSearchUserWindow(), INTERFACE_ShowUserMenu(), INTERFACE_StartLoad(), INTERFACE_StartLogin(), LOGIN_Login(), OLDGAME_GameResult(), OLDGAME_LoadGameHistory(), PARSER_ParsePresence(), PARSER_ParseXml(), PROFILE_SaveMyProfile(), REGISTER_GetDatabaseError(), ROOM_ErrorMessageLength(), ROOM_ExitRoom(), ROOM_HandleRoomList(), WINDOW_AnnounceWindow(), WINDOW_CancelRoom(), WINDOW_Challenge(), WINDOW_CreateImageSend(), WINDOW_CreateRoom(), WINDOW_CreateTourney(), WINDOW_Help(), WINDOW_Invite(), WINDOW_OldGame(), WINDOW_Postpone(), WINDOW_Profile(), WINDOW_ProfileConfirm(), WINDOW_ProfileImage(), and WINDOW_SearchUser().
function UTILS_GetTime (Timestamp)
Convert timestamp format to new format (XXhXX).
If timestamp is null, return current time.
Parameters:
Timestamp Timestamp integer value
Returns:
Timestamp in (XXhXX) format.
Author:
Danilo Yorinori
Referenced by INTERFACE_AddChatMessage().
function UTILS_HorizontalIndex (CharNum)
Convert horizontal board index. If param is a number convert to repesctive char else convert to respective number.
Parameters:
CharNum Character or integer number
Returns:
Character or integer number (depend of param)
Author:
Rubens Suguimoto
Referenced by GAME_RemoveBlockBorder(), GAME_RemoveBlockClass(), GAME_SendMove(), GAME_SetBlockBorder(), GAME_SetBlockClass(), INTERFACE_CreateBoard(), INTERFACE_CreateHorizontalIndex(), INTERFACE_InsertPiece(), INTERFACE_LastMove(), INTERFACE_RemoveBlockClass(), and INTERFACE_RemovePiece().
function UTILS_IdentifyBrowser ()
Identify client web browser and return a value.
Returns:
Browser Number (-1=Not identified, 0=IE, 1=FF2[gecko != 1.9], 2=FF3[gecko1.9])
Author:
Rubens Suguimoto
Referenced by DATA().
function UTILS_OpenXMLFile (Url)
Open a XML file, create and return XML DOM Tree.
Parameters:
Url XML file path
Returns:
XML DOM tree
Author:
Rubens Suguimoto
Referenced by DATA(), INTERFACE_CreateLanguage(), REGISTER_GetError(), REGISTER_Labels(), REGISTER_ParseError(), REGISTER_SucessMessage(), START_ChangeLanguage(), and START_StartPage().
function UTILS_ReadCookie (CookieName)
Read webclient cookies.
Parameters:
CookieName String
Author:
Pedro Rocha
Referenced by INTERFACE_StartLogin(), and START_StartPage().
function UTILS_RemoveListener (Element, Type, Expression, Bubbling)
Remove an event listener from element Return true if event has removed or false if event hasn't removed.
Parameters:
Element DOM element
Type Event type
Expression Function or action to remove
Bubbling Transmite event to others elements overlayed
Returns:
True or false
Author:
Rubens Suguimoto
Referenced by CONTACT_ShowUserMenu(), INTERFACE_ShowEmoticonList(), INTERFACE_ShowGameRoomMenu(), and INTERFACE_ShowRoomMenu().
function UTILS_ReturnEvent (event)
Check web browser type and return event object.
Parameters:
event Javascript event
Returns:
Return event according to web browser
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_StartLogin().
function UTILS_ReturnKeyCode (event)
Check web browser type and return event key code correctly.
Parameters:
event Javascript event
Returns:
Key code number (integer)
Author:
Rubens Suguimoto
References MainData.
Referenced by INTERFACE_CreateChat(), INTERFACE_CreateRoom(), and INTERFACE_ShowCreateRoomWindow().
function UTILS_ShortString (Word, NumChars)
Remove NumChars characteres of Word.
If word has more than number of characteres defined in NumChars, remove excced characters, else do nothing;
Parameters:
Word String with some text
NumChars Max numbers of characters
Returns:
New string with words changed
Author:
Rubens Suguimoto
Referenced by INTERFACE_AddAdjourn(), INTERFACE_AddAdminLevel(), INTERFACE_AddAnnounce(), INTERFACE_AddCurrentGames(), INTERFACE_AddLevel(), INTERFACE_AddMatchOffer(), INTERFACE_AddPostpone(), INTERFACE_AddPunish(), INTERFACE_CreatePhoto(), INTERFACE_CreateRoomInBar(), INTERFACE_CreateUser(), INTERFACE_CreateUserBox(), INTERFACE_CreateUserElement(), and INTERFACE_FocusRoom().
function UTILS_String2Board (BoardString)
Convert a string board to a array (8x8) board.
Returns:
Array x Array (8x8) of char
Author:
Rubens Suguimoto
Referenced by GAME_UpdateBoard(), and OLDGAME_UpdateBoard().
function UTILS_ValidateUsername (Username)
Check if username is a valid checking characters.
Parameters:
Username String
Returns:
True or False
Author:
Pedro Rocha
Referenced by LOGIN_Login().