XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/interface/welcome.js File Reference
/home/www/rubens/webclient/scripts/interface/welcome.js File Reference
Functions
function INTERFACE_CreateWelcome ()
function INTERFACE_RemoveWelcome ()
Function Documentation
function INTERFACE_CreateWelcome ()
References INTERFACE_RemoveWelcome(), MainData, UTILS_CreateElement(), UTILS_GetNodeText(), and UTILS_GetText().
function INTERFACE_RemoveWelcome ()
Referenced by INTERFACE_CreateWelcome().