XadrezLivre_WebClient: /home/www/rubens/webclient/scripts/window/window.js File Reference
/home/www/rubens/webclient/scripts/window/window.js File Reference
Control Windows.
Functions
function WINDOW_NewWindow (WinSize, Div, DivButtons, Title, Top, Left)
Create new window element.
function WINDOW_Focus (WindowObj)
Set focus to some window.
function WINDOW_RemoveWindow (WindowObj)
Remove window.
function WINDOW_Alert (Title, Text)
Open Alert window.
function WINDOW_Confirm (Title, Text, Button1, Button2)
Open Confirm Window.
function WINDOW_Challenge (User, RatingObj, GameParameters, Rated, MatchId)
Open Challenge window.
function WINDOW_CreateRoom ()
Open Create Room window.
function WINDOW_CancelRoom ()
function WINDOW_Invite (User)
Open Invite User window.
function WINDOW_SearchUser ()
Open Search User window.
function WINDOW_Profile (Profile)
Open Profile window.
function WINDOW_ProfileConfirm (WinObj, Profile, Elements)
Open Profile Close Confirmation window.
function WINDOW_ProfileImage ()
Open change profile image.
function WINDOW_OldGame (Id)
function WINDOW_UnbanUser ()
function WINDOW_BanUser (Username)
function WINDOW_KickUser (Username)
function WINDOW_AdminWindow ()
function WINDOW_AnnounceWindow (Username, Rating)
function WINDOW_Help ()
function WINDOW_Postpone (User, RatingObj, GameParameters, Rated, MatchId)
function WINDOW_CreateTourney ()
function WINDOW_CreateAdminCenter ()
Detailed Description
Control Windows.
CHESSD - WebClient
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
C3SL - Center for Scientific Computing and Free Software
Function Documentation
function WINDOW_AdminWindow ()
References INTERFACE_CreateAdminWindow(), UTILS_AddListener(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
function WINDOW_Alert (Title, Text)
Open Alert window.
Parameters:
Title Window title
Text Window text
Returns:
none
Author:
Danilo Yorinori
References UTILS_AddListener(), WINDOW_CreateAlert(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by ADMIN_HandleAddWord(), ADMIN_HandleRemoveWord(), ADMIN_Notification(), ANNOUNCE_AcceptRandomAnnounce(), ANNOUNCE_HandleAnnounceError(), ANNOUNCE_SendAnnounce(), CHALLENGE_HandleErrorChallenge(), CHAT_HandleAnnounceMessage(), CHAT_OpenChat(), CURRENTGAME_HandleGameRoomInfoError(), GAME_End(), GAME_HandleAdjourn(), GAME_HandleCancel(), GAME_HandleDraw(), GAME_HandleGameError(), GAME_RemoveGame(), IMAGE_B64Img(), INTERFACE_AddCurrentGames(), INTERFACE_AddOldGameResult(), INTERFACE_CreateGameOptions(), INTERFACE_CreateTop(), INTERFACE_RemoveGame(), INTERFACE_SetSearchButton(), INTERFACE_ShowCreateRoomWindow(), INTERFACE_ShowGameRoomList(), OLDGAME_LoadGameHistory(), PARSER_ParsePresence(), PROFILE_SaveMyProfile(), and ROOM_ExitRoom().
function WINDOW_AnnounceWindow (Username, Rating)
References INTERFACE_AnnounceWindow(), UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by INTERFACE_CreateChallengeMenu(), and INTERFACE_CreateGameCenterAnnounce().
function WINDOW_BanUser (Username)
References INTERFACE_BanUserWindow(), UTILS_AddListener(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by CONTACT_ShowUserMenu().
function WINDOW_CancelRoom ()
Open Cancel Room window
Author:
Danilo
References INTERFACE_ShowCancelRoomWindow(), UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
function WINDOW_Challenge (User, RatingObj, GameParameters, Rated, MatchId)
Open Challenge window.
Parameters:
User User's name
RatingObj Rating object with all ratings
GameParameters Challenge parameters
Rated Rated game flag
MatchId Challenge identification number
Returns:
none
Author:
Danilo Yorinori
References CHALLENGE_DeclineChallenge(), CHAT_OpenChat(), INTERFACE_ShowChallengeWindow(), MainData, UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by CHALLENGE_HandleOffer(), and CONTACT_ShowUserMenu().
function WINDOW_Confirm (Title, Text, Button1, Button2)
Open Confirm Window.
Parameters:
Title Window title
Text Window text
Button1 First button action
Button2 Second button action
Returns:
none
Author:
Danilo Yorinori
References UTILS_AddListener(), WINDOW_CreateConfirm(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by CONTACT_ReceiveSubscribe(), CONTACT_ShowUserMenu(), GAME_HandleAdjourn(), GAME_HandleCancel(), GAME_HandleDraw(), and GAME_SendResign().
function WINDOW_CreateAdminCenter ()
References INTERFACE_ShowCreateAdminCenterWindow(), UTILS_AddListener(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by INTERFACE_ShowAdminIcon().
function WINDOW_CreateRoom ()
Open Create Room window.
Returns:
none
Author:
Danilo Yorinori
References INTERFACE_ShowCreateRoomWindow(), UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by INTERFACE_ShowRoomMenu().
function WINDOW_CreateTourney ()
References INTERFACE_ShowCreateTourneyWindow(), UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
function WINDOW_Focus (WindowObj)
Set focus to some window.
Parameters:
WindowObj Window object
Returns:
none
Author:
Rubens Suguimoto
References MainData, and WindowObj().
Referenced by WINDOW_NewWindow().
function WINDOW_Help ()
References INTERFACE_HelpWindow(), UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by INTERFACE_CreateTop().
function WINDOW_Invite (User)
Open Invite User window.
Parameters:
User User's name
Returns:
none
Author:
Danilo Yorinori
References UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
function WINDOW_KickUser (Username)
References INTERFACE_KickUserWindow(), UTILS_AddListener(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by CONTACT_ShowUserMenu().
function WINDOW_NewWindow (WinSize, Div, DivButtons, Title, Top, Left)
Create new window element.
Window Object is defined in interface/windows.js
Parameters:
WinSize Window width
Div Window content div
DivButtons Window content buttons
Title Window Title
Top Window top position
Left Window left position
Returns:
Window object
Author:
Rubens Suguimoto
References MainData, UTILS_AddListener(), WINDOW_Focus(), and WindowObj().
Referenced by WINDOW_AdminWindow(), WINDOW_Alert(), WINDOW_AnnounceWindow(), WINDOW_BanUser(), WINDOW_CancelRoom(), WINDOW_Challenge(), WINDOW_Confirm(), WINDOW_CreateAdminCenter(), WINDOW_CreateRoom(), WINDOW_CreateTourney(), WINDOW_Help(), WINDOW_Invite(), WINDOW_KickUser(), WINDOW_OldGame(), WINDOW_Postpone(), WINDOW_Profile(), WINDOW_ProfileConfirm(), WINDOW_ProfileImage(), WINDOW_SearchUser(), and WINDOW_UnbanUser().
function WINDOW_OldGame (Id)
References INTERFACE_ShowOldGameWindow(), OLDGAME_CloseWindow(), UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by OLDGAME_OpenOldGameWindow().
function WINDOW_Postpone (User, RatingObj, GameParameters, Rated, MatchId)
References CHALLENGE_DeclineChallenge(), INTERFACE_ShowPostponeWindow(), MainData, UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by CHALLENGE_HandleOffer().
function WINDOW_Profile (Profile)
Open Profile window.
Returns:
Elements Profile's HTML DOM elements array
Author:
Danilo Yorinori
References INTERFACE_ShowProfileWindow(), PROFILE_ChangeVerification(), PROFILE_RemoveProfile(), PROFILE_SaveMyProfile(), UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_ProfileConfirm(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by PROFILE_StartProfile().
function WINDOW_ProfileConfirm (WinObj, Profile, Elements)
Open Profile Close Confirmation window.
Open if any changes occurs in user's profile
Parameters:
WinObj Paraent window object
Profile Profile window confirm content
Elements HTML DOM elements array
Returns:
none
Author:
Danilo Yorinori
References INTERFACE_ShowProfileConfirmWindow(), PROFILE_RemoveProfile(), UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by WINDOW_Profile().
function WINDOW_ProfileImage ()
Open change profile image.
Returns:
none
Author:
Rubens Suguimoto
References UTILS_AddListener(), UTILS_GetText(), WINDOW_CreateImageSend(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by INTERFACE_ProfileSetAvailable(), and INTERFACE_ShowProfileWindow().
function WINDOW_RemoveWindow (WindowObj)
Remove window.
Parameters:
WindowObj Window Object
Returns:
none
Author:
Rubens Suguimoto
References MainData, and WindowObj().
Referenced by CHALLENGE_HandleDecline(), INTERFACE_OldGameSetTable(), WINDOW_AdminWindow(), WINDOW_Alert(), WINDOW_AnnounceWindow(), WINDOW_BanUser(), WINDOW_CancelRoom(), WINDOW_Challenge(), WINDOW_Confirm(), WINDOW_CreateAdminCenter(), WINDOW_CreateRoom(), WINDOW_CreateTourney(), WINDOW_Help(), WINDOW_Invite(), WINDOW_KickUser(), WINDOW_OldGame(), WINDOW_Postpone(), WINDOW_Profile(), WINDOW_ProfileConfirm(), WINDOW_ProfileImage(), WINDOW_SearchUser(), and WINDOW_UnbanUser().
function WINDOW_SearchUser ()
Open Search User window.
Returns:
none
Author:
Danilo Yorinori
References INTERFACE_ShowSearchUserWindow(), MainData, UTILS_AddListener(), UTILS_GetText(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().
Referenced by INTERFACE_CreateContactContent(), and INTERFACE_CreateOnlineContent().
function WINDOW_UnbanUser ()
References INTERFACE_UnbanUserWindow(), UTILS_AddListener(), WINDOW_NewWindow(), WINDOW_RemoveWindow(), and WindowObj().